using System;

// Token: 0x02000003 RID: 3
internal static class ApplicationServicesStrings
{
	// Token: 0x0400002A RID: 42
	internal const string Can_not_use_encrypted_passwords_with_autogen_keys = "You must specify a non-autogenerated machine key to store passwords in the encrypted format. Either specify a different passwordFormat, or change the machineKey configuration to use a non-autogenerated decryption key.";

	// Token: 0x0400002B RID: 43
	internal const string CustomLoader_ForbiddenByHost = "The host forbids the use of custom loaders.";

	// Token: 0x0400002C RID: 44
	internal const string CustomLoader_MustImplementICustomLoader = "The provided type '{0}' must implement the ICustomLoader interface.";

	// Token: 0x0400002D RID: 45
	internal const string CustomLoader_NoAttributeFound = "The assembly '{0}' did not contain an assembly-level CustomLoaderAttribute.";

	// Token: 0x0400002E RID: 46
	internal const string CustomLoader_NotInFullTrust = "Custom loaders can only be used by fully-trusted applications (<trust level=\"Full\" />).";

	// Token: 0x0400002F RID: 47
	internal const string Membership_DuplicateEmail = "The E-mail address is already in use.";

	// Token: 0x04000030 RID: 48
	internal const string Membership_DuplicateProviderUserKey = "The provider user key is already in use.";

	// Token: 0x04000031 RID: 49
	internal const string Membership_DuplicateUserName = "The username is already in use.";

	// Token: 0x04000032 RID: 50
	internal const string Membership_InvalidAnswer = "The password-answer supplied is invalid.";

	// Token: 0x04000033 RID: 51
	internal const string Membership_InvalidEmail = "The E-mail supplied is invalid.";

	// Token: 0x04000034 RID: 52
	internal const string Membership_InvalidPassword = "The password supplied is invalid.  Passwords must conform to the password strength requirements configured for the default provider.";

	// Token: 0x04000035 RID: 53
	internal const string Membership_InvalidProviderUserKey = "The provider user key supplied is invalid. It must be of type System.Guid.";

	// Token: 0x04000036 RID: 54
	internal const string Membership_InvalidQuestion = "The password-question supplied is invalid.  Note that the current provider configuration requires a valid password question and answer.  As a result, a CreateUser overload that accepts question and answer parameters must also be used.";

	// Token: 0x04000037 RID: 55
	internal const string Membership_InvalidUserName = "The username supplied is invalid.";

	// Token: 0x04000038 RID: 56
	internal const string Membership_no_error = "No Error.";

	// Token: 0x04000039 RID: 57
	internal const string Membership_provider_name_invalid = "The membership provider name specified is invalid.";

	// Token: 0x0400003A RID: 58
	internal const string Membership_UserRejected = "The user was rejected.";

	// Token: 0x0400003B RID: 59
	internal const string Parameter_can_not_be_empty = "The parameter '{0}' must not be empty.";

	// Token: 0x0400003C RID: 60
	internal const string Platform_not_supported = "This member is not supported on the .NET Framework Client Profile.";

	// Token: 0x0400003D RID: 61
	internal const string Provider_Error = "The Provider encountered an unknown error.";

	// Token: 0x0400003E RID: 62
	internal const string Provider_must_implement_type = "Provider must implement the class '{0}'.";
}
