using System;
using System.Collections;

namespace System.Data.Odbc
{
	/// <summary>Collects all errors generated by the <see cref="T:System.Data.Odbc.OdbcDataAdapter" />. This class cannot be inherited.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x0200029E RID: 670
	[Serializable]
	public sealed class OdbcErrorCollection : ICollection, IEnumerable
	{
		// Token: 0x06001C87 RID: 7303 RVA: 0x0008DB32 File Offset: 0x0008BD32
		internal OdbcErrorCollection()
		{
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.SyncRoot" />.</summary>
		/// <returns>An object that can be used to synchronize access to the <see cref="T:System.Collections.ICollection" />.</returns>
		// Token: 0x1700053F RID: 1343
		// (get) Token: 0x06001C88 RID: 7304 RVA: 0x00005D82 File Offset: 0x00003F82
		object ICollection.SyncRoot
		{
			get
			{
				return this;
			}
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.IsSynchronized" />.</summary>
		/// <returns>true if access to the <see cref="T:System.Collections.ICollection" /> is synchronized (thread safe); otherwise, false.</returns>
		// Token: 0x17000540 RID: 1344
		// (get) Token: 0x06001C89 RID: 7305 RVA: 0x000061D5 File Offset: 0x000043D5
		bool ICollection.IsSynchronized
		{
			get
			{
				return false;
			}
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000541 RID: 1345
		// (get) Token: 0x06001C8A RID: 7306 RVA: 0x0008DB45 File Offset: 0x0008BD45
		public int Count
		{
			get
			{
				return this._items.Count;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>An <see cref="T:System.Data.Odbc.OdbcError" /> that contains the error at the specified index. </returns>
		/// <param name="i">The zero-based index of the error to retrieve. </param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x17000542 RID: 1346
		public OdbcError this[int i]
		{
			get
			{
				return (OdbcError)this._items[i];
			}
		}

		// Token: 0x06001C8C RID: 7308 RVA: 0x0008DB65 File Offset: 0x0008BD65
		internal void Add(OdbcError error)
		{
			this._items.Add(error);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> into an array, starting at the specified index within the array.</summary>
		/// <param name="array">The array into which to copy the elements. </param>
		/// <param name="i">The starting index of <paramref name="array" />. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> is greater than the length of the array. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001C8D RID: 7309 RVA: 0x0008DB74 File Offset: 0x0008BD74
		public void CopyTo(Array array, int i)
		{
			this._items.CopyTo(array, i);
		}

		/// <summary>Copies all the elements of the current <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> to the specified <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> starting at the specified destination index.</summary>
		/// <param name="array">The <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> that is the destination of the elements copied from the current <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</param>
		/// <param name="i">A 32-bit integer that represents the index in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> at which copying starts.</param>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001C8E RID: 7310 RVA: 0x0008DB74 File Offset: 0x0008BD74
		public void CopyTo(OdbcError[] array, int i)
		{
			this._items.CopyTo(array, i);
		}

		/// <summary>Returns an object that implements the <see cref="T:" /><see cref="System.Collections.IEnumerator" /> interface and that can iterate through the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> objects in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</summary>
		/// <returns>An object that implements the <see cref="T:" /><see cref="System.Collections.IEnumerator" /> interface and that can iterate through the <see cref="T:System.Data.Odbc.OdbcErrorCollection" /> objects in the <see cref="T:System.Data.Odbc.OdbcErrorCollection" />.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x06001C8F RID: 7311 RVA: 0x0008DB83 File Offset: 0x0008BD83
		public IEnumerator GetEnumerator()
		{
			return this._items.GetEnumerator();
		}

		// Token: 0x06001C90 RID: 7312 RVA: 0x0008DB90 File Offset: 0x0008BD90
		internal void SetSource(string Source)
		{
			foreach (object obj in this._items)
			{
				((OdbcError)obj).SetSource(Source);
			}
		}

		// Token: 0x04001540 RID: 5440
		private ArrayList _items = new ArrayList();
	}
}
