using System;
using System.Collections;
using System.Collections.Generic;
using System.Security.Permissions;
using System.Web.Services.Protocols;
using System.Xml;
using System.Xml.Serialization;

namespace System.Web.Services.Description
{
	/// <summary>Provides common functionality across communication protocols for creating <see cref="T:System.Web.Services.Description.ServiceDescription" /> objects from classes that are identified as Web services.</summary>
	// Token: 0x020000E3 RID: 227
	[PermissionSet(SecurityAction.InheritanceDemand, Name = "FullTrust")]
	[PermissionSet(SecurityAction.LinkDemand, Name = "FullTrust")]
	public abstract class ProtocolReflector
	{
		// Token: 0x060005E0 RID: 1504 RVA: 0x0001A9C1 File Offset: 0x00018BC1
		internal void Initialize(ServiceDescriptionReflector reflector)
		{
			this.reflector = reflector;
		}

		// Token: 0x1700018F RID: 399
		// (get) Token: 0x060005E1 RID: 1505 RVA: 0x0001A9CA File Offset: 0x00018BCA
		internal bool IsEmptyBinding
		{
			get
			{
				return this.emptyBinding;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) service that the protocol reflector is currently generating to contain a reference to the binding being generated.</summary>
		/// <returns>The Web Services Description Language (WSDL) service that the protocol reflector is currently generating to contain a reference to the binding being generated.</returns>
		// Token: 0x17000190 RID: 400
		// (get) Token: 0x060005E2 RID: 1506 RVA: 0x0001A9D2 File Offset: 0x00018BD2
		public Service Service
		{
			get
			{
				return this.reflector.Service;
			}
		}

		/// <summary>Gets the <see cref="T:System.Web.Services.Description.ServiceDescription" /> object currently being created to contain the binding being generated.</summary>
		/// <returns>The <see cref="T:System.Web.Services.Description.ServiceDescription" /> object currently being created to contain the binding being generated.</returns>
		// Token: 0x17000191 RID: 401
		// (get) Token: 0x060005E3 RID: 1507 RVA: 0x0001A9DF File Offset: 0x00018BDF
		public ServiceDescription ServiceDescription
		{
			get
			{
				return this.reflector.ServiceDescription;
			}
		}

		/// <summary>Gets the <see cref="T:System.Web.Services.Description.ServiceDescription" /> objects that have so far been created and added to the corresponding to the <see cref="T:System.Web.Services.Description.ServiceDescriptionCollection" /> obtained through the <see cref="P:System.Web.Services.Description.ServiceDescriptionReflector.ServiceDescriptions" /> property of the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance. </summary>
		/// <returns>The <see cref="T:System.Web.Services.Description.ServiceDescription" /> objects that have so far been created and added to the corresponding to the <see cref="T:System.Web.Services.Description.ServiceDescriptionCollection" /> obtained through the <see cref="P:System.Web.Services.Description.ServiceDescriptionReflector.ServiceDescriptions" /> property of the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</returns>
		// Token: 0x17000192 RID: 402
		// (get) Token: 0x060005E4 RID: 1508 RVA: 0x0001A9EC File Offset: 0x00018BEC
		public ServiceDescriptionCollection ServiceDescriptions
		{
			get
			{
				return this.reflector.ServiceDescriptions;
			}
		}

		// Token: 0x17000193 RID: 403
		// (get) Token: 0x060005E5 RID: 1509 RVA: 0x0001A9F9 File Offset: 0x00018BF9
		internal List<Action<Uri>> UriFixups
		{
			get
			{
				return this.reflector.UriFixups;
			}
		}

		/// <summary>Gets the XML schemas being generated by the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</summary>
		/// <returns>The XML schemas being generated by the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</returns>
		// Token: 0x17000194 RID: 404
		// (get) Token: 0x060005E6 RID: 1510 RVA: 0x0001AA06 File Offset: 0x00018C06
		public XmlSchemas Schemas
		{
			get
			{
				return this.reflector.Schemas;
			}
		}

		/// <summary>Gets the <see cref="T:System.Xml.Serialization.XmlSchemaExporter" /> instance being used by the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</summary>
		/// <returns>The <see cref="T:System.Xml.Serialization.XmlSchemaExporter" /> instance being used by the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</returns>
		// Token: 0x17000195 RID: 405
		// (get) Token: 0x060005E7 RID: 1511 RVA: 0x0001AA13 File Offset: 0x00018C13
		public XmlSchemaExporter SchemaExporter
		{
			get
			{
				return this.reflector.SchemaExporter;
			}
		}

		/// <summary>Gets the <see cref="T:System.Xml.Serialization.XmlReflectionImporter" /> instance being used by the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</summary>
		/// <returns>The <see cref="T:System.Xml.Serialization.XmlReflectionImporter" /> instance being used by the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> instance.</returns>
		// Token: 0x17000196 RID: 406
		// (get) Token: 0x060005E8 RID: 1512 RVA: 0x0001AA20 File Offset: 0x00018C20
		public XmlReflectionImporter ReflectionImporter
		{
			get
			{
				return this.reflector.ReflectionImporter;
			}
		}

		/// <summary>Gets the default namespace, as identified by the associated <see cref="T:System.Web.Services.Description.ServiceDescription" /> object's <see cref="F:System.Web.Services.Description.ServiceDescription.Namespace" /> property.</summary>
		/// <returns>The default namespace, as identified by the associated <see cref="T:System.Web.Services.Description.ServiceDescription" /> object's <see cref="F:System.Web.Services.Description.ServiceDescription.Namespace" /> property.</returns>
		// Token: 0x17000197 RID: 407
		// (get) Token: 0x060005E9 RID: 1513 RVA: 0x0001AA2D File Offset: 0x00018C2D
		public string DefaultNamespace
		{
			get
			{
				return this.reflector.ServiceAttribute.Namespace;
			}
		}

		/// <summary>Gets the endpoint of the associated Web service as a Uniform Resource Locator (URL), obtained from the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> object.</summary>
		/// <returns>The endpoint of the associated Web service as a Uniform Resource Locator (URL), obtained from the associated <see cref="T:System.Web.Services.Description.ServiceDescriptionReflector" /> object.</returns>
		// Token: 0x17000198 RID: 408
		// (get) Token: 0x060005EA RID: 1514 RVA: 0x0001AA3F File Offset: 0x00018C3F
		public string ServiceUrl
		{
			get
			{
				return this.reflector.ServiceUrl;
			}
		}

		/// <summary>Gets the type of the Web service class being reflected to produce <see cref="T:System.Web.Services.Description.ServiceDescription" /> objects.</summary>
		/// <returns>The type of the Web service class being reflected to produce <see cref="T:System.Web.Services.Description.ServiceDescription" /> objects.</returns>
		// Token: 0x17000199 RID: 409
		// (get) Token: 0x060005EB RID: 1515 RVA: 0x0001AA4C File Offset: 0x00018C4C
		public Type ServiceType
		{
			get
			{
				return this.reflector.ServiceType;
			}
		}

		/// <summary>Gets the Web service method that the protocol reflector is currently processing to generate a Web Services Description Language (WSDL) operation to be placed in the generated <see cref="T:System.Web.Services.Description.ServiceDescription" />.</summary>
		/// <returns>The Web service method that the protocol reflector is currently processing to generate a Web Services Description Language (WSDL) operation to be placed in the generated <see cref="T:System.Web.Services.Description.ServiceDescription" />.</returns>
		// Token: 0x1700019A RID: 410
		// (get) Token: 0x060005EC RID: 1516 RVA: 0x0001AA59 File Offset: 0x00018C59
		public LogicalMethodInfo Method
		{
			get
			{
				return this.method;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) binding currently being generated and added to the associated <see cref="T:System.Web.Services.Description.ServiceDescription" />.</summary>
		/// <returns>The Web Services Description Language (WSDL) binding currently being generated and added to the associated <see cref="T:System.Web.Services.Description.ServiceDescription" />.</returns>
		// Token: 0x1700019B RID: 411
		// (get) Token: 0x060005ED RID: 1517 RVA: 0x0001AA61 File Offset: 0x00018C61
		public Binding Binding
		{
			get
			{
				return this.binding;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) portType that the protocol reflector is currently generating to be implemented by the binding being generated.</summary>
		/// <returns>The Web Services Description Language (WSDL) portType that the protocol reflector is currently generating to be implemented by the binding being generated.</returns>
		// Token: 0x1700019C RID: 412
		// (get) Token: 0x060005EE RID: 1518 RVA: 0x0001AA69 File Offset: 0x00018C69
		public PortType PortType
		{
			get
			{
				return this.portType;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) port that the protocol reflector is currently generating to contain a reference to the binding being generated.</summary>
		/// <returns>The Web Services Description Language (WSDL) port that the protocol reflector is currently generating to contain a reference to the binding being generated.</returns>
		// Token: 0x1700019D RID: 413
		// (get) Token: 0x060005EF RID: 1519 RVA: 0x0001AA71 File Offset: 0x00018C71
		public Port Port
		{
			get
			{
				return this.port;
			}
		}

		/// <summary>Gets the abstract Web Services Description Language (WSDL) operation that the protocol reflector is currently generating from a Web service method.</summary>
		/// <returns>The abstract Web Services Description Language (WSDL) operation that the protocol reflector is currently generating from a Web service method</returns>
		// Token: 0x1700019E RID: 414
		// (get) Token: 0x060005F0 RID: 1520 RVA: 0x0001AA79 File Offset: 0x00018C79
		public Operation Operation
		{
			get
			{
				return this.operation;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) operation binding that the protocol importer is currently generating from a Web service method.</summary>
		/// <returns>The Web Services Description Language (WSDL) operation binding that the protocol importer is currently generating from a Web service method.</returns>
		// Token: 0x1700019F RID: 415
		// (get) Token: 0x060005F1 RID: 1521 RVA: 0x0001AA81 File Offset: 0x00018C81
		public OperationBinding OperationBinding
		{
			get
			{
				return this.operationBinding;
			}
		}

		/// <summary>Gets the <see cref="T:System.Web.Services.WebMethodAttribute" /> for the method that the protocol reflector is currently processing to generate a Web Services Description Language (WSDL) operation to be placed in the generated <see cref="T:System.Web.Services.Description.ServiceDescription" />.</summary>
		/// <returns>The <see cref="T:System.Web.Services.WebMethodAttribute" /> for the method that the protocol reflector is currently processing to generate a Web Services Description Language (WSDL) operation to be placed in the generated <see cref="T:System.Web.Services.Description.ServiceDescription" /></returns>
		// Token: 0x170001A0 RID: 416
		// (get) Token: 0x060005F2 RID: 1522 RVA: 0x0001AA89 File Offset: 0x00018C89
		public WebMethodAttribute MethodAttribute
		{
			get
			{
				return this.methodAttr;
			}
		}

		/// <summary>Gets the Web service methods belonging to the Web service class, as identified by the associated <see cref="T:System.Web.Services.Description.ProtocolReflector" /> object's <see cref="P:System.Web.Services.Description.ProtocolReflector.Methods" /> property.</summary>
		/// <returns>The Web service methods belonging to the Web service class, as identified by the associated <see cref="T:System.Web.Services.Description.ProtocolReflector" /> object's <see cref="P:System.Web.Services.Description.ProtocolReflector.Methods" /> property.</returns>
		// Token: 0x170001A1 RID: 417
		// (get) Token: 0x060005F3 RID: 1523 RVA: 0x0001AA91 File Offset: 0x00018C91
		public LogicalMethodInfo[] Methods
		{
			get
			{
				return this.reflector.Methods;
			}
		}

		// Token: 0x170001A2 RID: 418
		// (get) Token: 0x060005F4 RID: 1524 RVA: 0x0001AA9E File Offset: 0x00018C9E
		internal Hashtable ReflectionContext
		{
			get
			{
				return this.reflector.ReflectionContext;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) input message for the abstract operation that the protocol reflector is currently generating from a Web service method.</summary>
		/// <returns>The Web Services Description Language (WSDL) input message for the abstract operation that the protocol reflector is currently generating from a Web service method.</returns>
		// Token: 0x170001A3 RID: 419
		// (get) Token: 0x060005F5 RID: 1525 RVA: 0x0001AAAC File Offset: 0x00018CAC
		public Message InputMessage
		{
			get
			{
				if (this.inputMessage == null)
				{
					string text = XmlConvert.EncodeLocalName((this.methodAttr.MessageName.Length == 0) ? this.Method.Name : this.methodAttr.MessageName);
					bool flag = text != this.Method.Name;
					this.inputMessage = new Message();
					this.inputMessage.Name = text + this.ProtocolName + "In";
					OperationInput operationInput = new OperationInput();
					if (flag)
					{
						operationInput.Name = text;
					}
					operationInput.Message = new XmlQualifiedName(this.inputMessage.Name, this.bindingServiceDescription.TargetNamespace);
					this.operation.Messages.Add(operationInput);
					this.OperationBinding.Input = new InputBinding();
					if (flag)
					{
						this.OperationBinding.Input.Name = text;
					}
				}
				return this.inputMessage;
			}
		}

		/// <summary>Gets the Web Services Description Language (WSDL) output message for the abstract operation that the protocol reflector is currently generating from a Web service method.</summary>
		/// <returns>The Web Services Description Language (WSDL) output message for the abstract operation that the protocol reflector is currently generating from a Web service method.</returns>
		// Token: 0x170001A4 RID: 420
		// (get) Token: 0x060005F6 RID: 1526 RVA: 0x0001AB98 File Offset: 0x00018D98
		public Message OutputMessage
		{
			get
			{
				if (this.outputMessage == null)
				{
					string text = XmlConvert.EncodeLocalName((this.methodAttr.MessageName.Length == 0) ? this.Method.Name : this.methodAttr.MessageName);
					bool flag = text != this.Method.Name;
					this.outputMessage = new Message();
					this.outputMessage.Name = text + this.ProtocolName + "Out";
					OperationOutput operationOutput = new OperationOutput();
					if (flag)
					{
						operationOutput.Name = text;
					}
					operationOutput.Message = new XmlQualifiedName(this.outputMessage.Name, this.bindingServiceDescription.TargetNamespace);
					this.operation.Messages.Add(operationOutput);
					this.OperationBinding.Output = new OutputBinding();
					if (flag)
					{
						this.OperationBinding.Output.Name = text;
					}
				}
				return this.outputMessage;
			}
		}

		/// <summary>Gets SOAP header message definitions to be added to the associated <see cref="T:System.Web.Services.Description.ServiceDescription" /> object.</summary>
		/// <returns>SOAP header message definitions to be added to the associated <see cref="T:System.Web.Services.Description.ServiceDescription" /> object.</returns>
		// Token: 0x170001A5 RID: 421
		// (get) Token: 0x060005F7 RID: 1527 RVA: 0x0001AC84 File Offset: 0x00018E84
		public MessageCollection HeaderMessages
		{
			get
			{
				if (this.headerMessages == null)
				{
					this.headerMessages = new MessageCollection(this.bindingServiceDescription);
				}
				return this.headerMessages;
			}
		}

		// Token: 0x060005F8 RID: 1528 RVA: 0x0001ACA5 File Offset: 0x00018EA5
		private void MoveToMethod(LogicalMethodInfo method)
		{
			this.method = method;
			this.methodAttr = method.MethodAttribute;
		}

		// Token: 0x060005F9 RID: 1529 RVA: 0x0001ACBC File Offset: 0x00018EBC
		internal void Reflect()
		{
			this.emptyBinding = false;
			Hashtable hashtable = new Hashtable();
			Hashtable hashtable2 = new Hashtable();
			for (int i = 0; i < this.reflector.Methods.Length; i++)
			{
				this.MoveToMethod(this.reflector.Methods[i]);
				string text = this.ReflectMethodBinding();
				if (text == null)
				{
					text = string.Empty;
				}
				ProtocolReflector.ReflectedBinding reflectedBinding = (ProtocolReflector.ReflectedBinding)hashtable2[text];
				if (reflectedBinding == null)
				{
					reflectedBinding = new ProtocolReflector.ReflectedBinding();
					reflectedBinding.bindingAttr = WebServiceBindingReflector.GetAttribute(this.method, text);
					if (reflectedBinding.bindingAttr == null || (text.Length == 0 && reflectedBinding.bindingAttr.Location.Length > 0))
					{
						reflectedBinding.bindingAttr = new WebServiceBindingAttribute();
					}
					hashtable2.Add(text, reflectedBinding);
				}
				if (reflectedBinding.bindingAttr.Location.Length == 0)
				{
					if (reflectedBinding.methodList == null)
					{
						reflectedBinding.methodList = new ArrayList();
					}
					reflectedBinding.methodList.Add(this.method);
					hashtable[reflectedBinding.bindingAttr.Name] = this.method;
				}
				else
				{
					this.AddImport(reflectedBinding.bindingAttr.Namespace, reflectedBinding.bindingAttr.Location);
				}
			}
			foreach (object obj in hashtable2.Values)
			{
				ProtocolReflector.ReflectedBinding reflectedBinding2 = (ProtocolReflector.ReflectedBinding)obj;
				this.ReflectBinding(reflectedBinding2);
			}
			if (hashtable2.Count == 0)
			{
				this.emptyBinding = true;
				ProtocolReflector.ReflectedBinding reflectedBinding3 = null;
				foreach (WebServiceBindingAttribute webServiceBindingAttribute in this.ServiceType.GetCustomAttributes(typeof(WebServiceBindingAttribute), false))
				{
					if (hashtable[webServiceBindingAttribute.Name] == null)
					{
						if (reflectedBinding3 != null)
						{
							reflectedBinding3 = null;
							break;
						}
						reflectedBinding3 = new ProtocolReflector.ReflectedBinding(webServiceBindingAttribute);
					}
				}
				if (reflectedBinding3 != null)
				{
					this.ReflectBinding(reflectedBinding3);
				}
			}
			Type[] interfaces = this.ServiceType.GetInterfaces();
			for (int k = 0; k < interfaces.Length; k++)
			{
				foreach (WebServiceBindingAttribute webServiceBindingAttribute2 in interfaces[k].GetCustomAttributes(typeof(WebServiceBindingAttribute), false))
				{
					if (hashtable[webServiceBindingAttribute2.Name] == null)
					{
						this.ReflectBinding(new ProtocolReflector.ReflectedBinding(webServiceBindingAttribute2));
					}
				}
			}
			this.ReflectDescription();
		}

		// Token: 0x060005FA RID: 1530 RVA: 0x0001AF3C File Offset: 0x0001913C
		private void AddImport(string ns, string location)
		{
			foreach (object obj in this.ServiceDescription.Imports)
			{
				Import import = (Import)obj;
				if (import.Namespace == ns && import.Location == location)
				{
					return;
				}
			}
			Import import2 = new Import();
			import2.Namespace = ns;
			import2.Location = location;
			this.ServiceDescription.Imports.Add(import2);
		}

		/// <summary>Gets a <see cref="T:System.Web.Services.Description.ServiceDescription" /> object for a given XML namespace and the applicable communication protocol.</summary>
		/// <returns>A <see cref="T:System.Web.Services.Description.ServiceDescription" /> object for a given XML namespace and the applicable communication protocol.</returns>
		/// <param name="ns">The <see cref="T:System.Web.Services.Description.ServiceDescription" /> instance obtained subsequently gets populated with objects that correspond to Web Services Description Language (WSDL) entities that are reflected from the input Web service class.</param>
		// Token: 0x060005FB RID: 1531 RVA: 0x0001AFD8 File Offset: 0x000191D8
		public ServiceDescription GetServiceDescription(string ns)
		{
			ServiceDescription serviceDescription = this.ServiceDescriptions[ns];
			if (serviceDescription == null)
			{
				serviceDescription = new ServiceDescription();
				serviceDescription.TargetNamespace = ns;
				this.ServiceDescriptions.Add(serviceDescription);
			}
			return serviceDescription;
		}

		// Token: 0x060005FC RID: 1532 RVA: 0x0001B010 File Offset: 0x00019210
		private void ReflectBinding(ProtocolReflector.ReflectedBinding reflectedBinding)
		{
			string text = XmlConvert.EncodeLocalName(reflectedBinding.bindingAttr.Name);
			string text2 = reflectedBinding.bindingAttr.Namespace;
			if (text.Length == 0)
			{
				text = this.Service.Name + this.ProtocolName;
			}
			if (text2.Length == 0)
			{
				text2 = this.ServiceDescription.TargetNamespace;
			}
			WsiProfiles wsiProfiles = WsiProfiles.None;
			if (reflectedBinding.bindingAttr.Location.Length > 0)
			{
				this.portType = null;
				this.binding = null;
			}
			else
			{
				this.bindingServiceDescription = this.GetServiceDescription(text2);
				CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
				foreach (object obj in this.bindingServiceDescription.Bindings)
				{
					Binding binding = (Binding)obj;
					codeIdentifiers.AddReserved(binding.Name);
				}
				text = codeIdentifiers.AddUnique(text, this.binding);
				this.portType = new PortType();
				this.binding = new Binding();
				this.portType.Name = text;
				this.binding.Name = text;
				this.binding.Type = new XmlQualifiedName(this.portType.Name, text2);
				wsiProfiles = reflectedBinding.bindingAttr.ConformsTo & this.ConformsTo;
				if (reflectedBinding.bindingAttr.EmitConformanceClaims && wsiProfiles != WsiProfiles.None)
				{
					ServiceDescription.AddConformanceClaims(this.binding.GetDocumentationElement(), wsiProfiles);
				}
				this.bindingServiceDescription.Bindings.Add(this.binding);
				this.bindingServiceDescription.PortTypes.Add(this.portType);
			}
			if (this.portNames == null)
			{
				this.portNames = new CodeIdentifiers();
				foreach (object obj2 in this.Service.Ports)
				{
					Port port = (Port)obj2;
					this.portNames.AddReserved(port.Name);
				}
			}
			this.port = new Port();
			this.port.Binding = new XmlQualifiedName(text, text2);
			this.port.Name = this.portNames.AddUnique(text, this.port);
			this.Service.Ports.Add(this.port);
			this.BeginClass();
			if (reflectedBinding.methodList != null && reflectedBinding.methodList.Count > 0)
			{
				foreach (object obj3 in reflectedBinding.methodList)
				{
					LogicalMethodInfo logicalMethodInfo = (LogicalMethodInfo)obj3;
					this.MoveToMethod(logicalMethodInfo);
					this.operation = new Operation();
					this.operation.Name = XmlConvert.EncodeLocalName(logicalMethodInfo.Name);
					if (this.methodAttr.Description != null && this.methodAttr.Description.Length > 0)
					{
						this.operation.Documentation = this.methodAttr.Description;
					}
					this.operationBinding = new OperationBinding();
					this.operationBinding.Name = this.operation.Name;
					this.inputMessage = null;
					this.outputMessage = null;
					this.headerMessages = null;
					if (this.ReflectMethod())
					{
						if (this.inputMessage != null)
						{
							this.bindingServiceDescription.Messages.Add(this.inputMessage);
						}
						if (this.outputMessage != null)
						{
							this.bindingServiceDescription.Messages.Add(this.outputMessage);
						}
						if (this.headerMessages != null)
						{
							foreach (object obj4 in this.headerMessages)
							{
								Message message = (Message)obj4;
								this.bindingServiceDescription.Messages.Add(message);
							}
						}
						this.binding.Operations.Add(this.operationBinding);
						this.portType.Operations.Add(this.operation);
					}
				}
			}
			if (this.binding != null && wsiProfiles == WsiProfiles.BasicProfile1_1 && this.ProtocolName == "Soap")
			{
				BasicProfileViolationCollection basicProfileViolationCollection = new BasicProfileViolationCollection();
				WebServicesInteroperability.AnalyzeBinding(this.binding, this.bindingServiceDescription, this.ServiceDescriptions, basicProfileViolationCollection);
				if (basicProfileViolationCollection.Count > 0)
				{
					throw new InvalidOperationException(Res.GetString("WebWsiViolation", new object[]
					{
						this.ServiceType.FullName,
						basicProfileViolationCollection.ToString()
					}));
				}
			}
			this.EndClass();
		}

		// Token: 0x170001A6 RID: 422
		// (get) Token: 0x060005FD RID: 1533 RVA: 0x00002B51 File Offset: 0x00000D51
		internal virtual WsiProfiles ConformsTo
		{
			get
			{
				return WsiProfiles.None;
			}
		}

		/// <summary>When overridden in a derived class, gets the name of the protocol being used.</summary>
		/// <returns>The name of the protocol being used.</returns>
		// Token: 0x170001A7 RID: 423
		// (get) Token: 0x060005FE RID: 1534
		public abstract string ProtocolName { get; }

		/// <summary>When overridden in a derived class, performs processing before <see cref="T:System.Web.Services.Description.ProtocolReflector" /> calls the <see cref="M:System.Web.Services.Description.ProtocolReflector.ReflectMethod" /> method for each of the methods for a binding.</summary>
		// Token: 0x060005FF RID: 1535 RVA: 0x0000210D File Offset: 0x0000030D
		protected virtual void BeginClass()
		{
		}

		/// <summary>When overridden in a derived class, generates method-specific information that gets placed in a <see cref="T:System.Web.Services.Description.ServiceDescription" /> object corresponding to a binding.</summary>
		/// <returns>Method-specific information that gets placed in a <see cref="T:System.Web.Services.Description.ServiceDescription" /> object corresponding to a binding.</returns>
		// Token: 0x06000600 RID: 1536
		protected abstract bool ReflectMethod();

		/// <summary>When overridden in a derived class, returns the name of the binding that a method belongs to.</summary>
		/// <returns>The name of the binding that a method belongs to.</returns>
		// Token: 0x06000601 RID: 1537 RVA: 0x0001B514 File Offset: 0x00019714
		protected virtual string ReflectMethodBinding()
		{
			return string.Empty;
		}

		/// <summary>When overridden in a derived class, performs processing after <see cref="ProtocolReflector" /> has called the <see cref="M:System.Web.Services.Description.ProtocolReflector.ReflectMethod" /> method for each of the methods for a binding.</summary>
		// Token: 0x06000602 RID: 1538 RVA: 0x0000210D File Offset: 0x0000030D
		protected virtual void EndClass()
		{
		}

		/// <summary>When overridden in a derived class, generates service-specific description information that gets placed in a <see cref="T:System.Web.Services.Description.ServiceDescription" /> object that corresponds to a binding.</summary>
		// Token: 0x06000603 RID: 1539 RVA: 0x0000210D File Offset: 0x0000030D
		protected virtual void ReflectDescription()
		{
		}

		// Token: 0x040003B8 RID: 952
		private ServiceDescriptionReflector reflector;

		// Token: 0x040003B9 RID: 953
		private LogicalMethodInfo method;

		// Token: 0x040003BA RID: 954
		private Operation operation;

		// Token: 0x040003BB RID: 955
		private OperationBinding operationBinding;

		// Token: 0x040003BC RID: 956
		private Port port;

		// Token: 0x040003BD RID: 957
		private PortType portType;

		// Token: 0x040003BE RID: 958
		private Binding binding;

		// Token: 0x040003BF RID: 959
		private WebMethodAttribute methodAttr;

		// Token: 0x040003C0 RID: 960
		private Message inputMessage;

		// Token: 0x040003C1 RID: 961
		private Message outputMessage;

		// Token: 0x040003C2 RID: 962
		private MessageCollection headerMessages;

		// Token: 0x040003C3 RID: 963
		private ServiceDescription bindingServiceDescription;

		// Token: 0x040003C4 RID: 964
		private CodeIdentifiers portNames;

		// Token: 0x040003C5 RID: 965
		private bool emptyBinding;

		// Token: 0x020000E4 RID: 228
		private class ReflectedBinding
		{
			// Token: 0x06000605 RID: 1541 RVA: 0x0000210F File Offset: 0x0000030F
			internal ReflectedBinding()
			{
			}

			// Token: 0x06000606 RID: 1542 RVA: 0x0001B51B File Offset: 0x0001971B
			internal ReflectedBinding(WebServiceBindingAttribute bindingAttr)
			{
				this.bindingAttr = bindingAttr;
			}

			// Token: 0x040003C6 RID: 966
			public WebServiceBindingAttribute bindingAttr;

			// Token: 0x040003C7 RID: 967
			public ArrayList methodList;
		}
	}
}
