using System;

namespace System.Web.Services.Description
{
	/// <summary>Specifies the type of warnings produced by <see cref="M:System.Web.Services.Description.ServiceDescriptionImporter.Import(System.CodeDom.CodeNamespace,System.CodeDom.CodeCompileUnit)" />.</summary>
	// Token: 0x0200010D RID: 269
	[Flags]
	public enum ServiceDescriptionImportWarnings
	{
		/// <summary>Specifies that no proxy class was generated by the <see cref="M:System.Web.Services.Description.ServiceDescriptionImporter.Import(System.CodeDom.CodeNamespace,System.CodeDom.CodeCompileUnit)" /> method.</summary>
		// Token: 0x04000423 RID: 1059
		NoCodeGenerated = 1,
		/// <summary>Specifies that at least one optional <see cref="T:System.Web.Services.Description.ServiceDescriptionFormatExtension" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported has been ignored.</summary>
		// Token: 0x04000424 RID: 1060
		OptionalExtensionsIgnored = 2,
		/// <summary>Specifies that at least one required <see cref="T:System.Web.Services.Description.ServiceDescriptionFormatExtension" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported has been ignored.</summary>
		// Token: 0x04000425 RID: 1061
		RequiredExtensionsIgnored = 4,
		/// <summary>Specifies that at least one <see cref="T:System.Web.Services.Description.Operation" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported is of an unsupported type and has been ignored.</summary>
		// Token: 0x04000426 RID: 1062
		UnsupportedOperationsIgnored = 8,
		/// <summary>Specifies that at least one <see cref="T:System.Web.Services.Description.Binding" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported is of an unsupported type and has been ignored.</summary>
		// Token: 0x04000427 RID: 1063
		UnsupportedBindingsIgnored = 16,
		/// <summary>Specifies that the proxy class generated by the <see cref="M:System.Web.Services.Description.ServiceDescriptionImporter.Import(System.CodeDom.CodeNamespace,System.CodeDom.CodeCompileUnit)" /> method includes no methods.</summary>
		// Token: 0x04000428 RID: 1064
		NoMethodsGenerated = 32,
		/// <summary>Specifies that the <see cref="T:System.Web.Services.Description.ServiceDescription" /> schema is invalid.</summary>
		// Token: 0x04000429 RID: 1065
		SchemaValidation = 64,
		/// <summary>Specifies that the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported does not conform to the WS-I Basic Profile.</summary>
		// Token: 0x0400042A RID: 1066
		WsiConformance = 128
	}
}
