using System;
using System.Runtime.CompilerServices;
using System.Web.Compilation;
using Unity;

namespace System.Web.UI
{
	/// <summary>Represents a control property that is data-bound to an expression.</summary>
	// Token: 0x020001A6 RID: 422
	public class BoundPropertyEntry : PropertyEntry
	{
		// Token: 0x06001032 RID: 4146 RVA: 0x0002C94E File Offset: 0x0002AB4E
		internal BoundPropertyEntry()
		{
		}

		/// <summary>Gets or sets the ID of the control that contains this binding.</summary>
		/// <returns>A <see cref="T:System.String" /> with the <see cref="P:System.Web.UI.Control.ID" /> of the control that contains this binding.</returns>
		// Token: 0x17000549 RID: 1353
		// (get) Token: 0x06001033 RID: 4147 RVA: 0x0002C956 File Offset: 0x0002AB56
		// (set) Token: 0x06001034 RID: 4148 RVA: 0x0002C95E File Offset: 0x0002AB5E
		public string ControlID { get; set; }

		/// <summary>Gets or sets the type of the control that is being bound to at run time.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the control bound by the expression.</returns>
		// Token: 0x1700054A RID: 1354
		// (get) Token: 0x06001035 RID: 4149 RVA: 0x0002C967 File Offset: 0x0002AB67
		// (set) Token: 0x06001036 RID: 4150 RVA: 0x0002C96F File Offset: 0x0002AB6F
		public Type ControlType { get; set; }

		/// <summary>Gets or sets the value representing an expression during page parsing.</summary>
		/// <returns>A <see cref="T:System.String" /> that contains the expression.</returns>
		// Token: 0x1700054B RID: 1355
		// (get) Token: 0x06001037 RID: 4151 RVA: 0x0002C978 File Offset: 0x0002AB78
		// (set) Token: 0x06001038 RID: 4152 RVA: 0x0002C980 File Offset: 0x0002AB80
		public string Expression { get; set; }

		/// <summary>Gets or sets the object used for evaluating the expression during page parsing.</summary>
		/// <returns>An <see cref="T:System.Web.Compilation.ExpressionBuilder" /> for evaluating this expression.</returns>
		// Token: 0x1700054C RID: 1356
		// (get) Token: 0x06001039 RID: 4153 RVA: 0x0002C989 File Offset: 0x0002AB89
		// (set) Token: 0x0600103A RID: 4154 RVA: 0x0002C991 File Offset: 0x0002AB91
		public ExpressionBuilder ExpressionBuilder { get; set; }

		/// <summary>Gets or sets the prefix for this expression.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the prefix.</returns>
		// Token: 0x1700054D RID: 1357
		// (get) Token: 0x0600103B RID: 4155 RVA: 0x0002C99A File Offset: 0x0002AB9A
		// (set) Token: 0x0600103C RID: 4156 RVA: 0x0002C9A2 File Offset: 0x0002ABA2
		public string ExpressionPrefix { get; set; }

		/// <summary>Gets or sets the name of the data field bound to by the expression.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the data field name.</returns>
		// Token: 0x1700054E RID: 1358
		// (get) Token: 0x0600103D RID: 4157 RVA: 0x0002C9AB File Offset: 0x0002ABAB
		// (set) Token: 0x0600103E RID: 4158 RVA: 0x0002C9B3 File Offset: 0x0002ABB3
		public string FieldName { get; set; }

		/// <summary>Gets or sets the format specifier characters that indicate how a value is to be displayed.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the format specifier characters that indicate how a value is to be displayed.</returns>
		// Token: 0x1700054F RID: 1359
		// (get) Token: 0x0600103F RID: 4159 RVA: 0x0002C9BC File Offset: 0x0002ABBC
		// (set) Token: 0x06001040 RID: 4160 RVA: 0x0002C9C4 File Offset: 0x0002ABC4
		public string FormatString { get; set; }

		/// <summary>Gets or sets a value indicating whether the expression was generated by the parser.</summary>
		/// <returns>true if the expression was generated by the parser; otherwise, false.</returns>
		// Token: 0x17000550 RID: 1360
		// (get) Token: 0x06001041 RID: 4161 RVA: 0x0002C9CD File Offset: 0x0002ABCD
		// (set) Token: 0x06001042 RID: 4162 RVA: 0x0002C9D5 File Offset: 0x0002ABD5
		public bool Generated { get; set; }

		/// <summary>Gets or sets the data retrieved from an expression builder object during page parsing.</summary>
		/// <returns>An <see cref="T:System.Object" /> containing the data retrieved from an <see cref="T:System.Web.Compilation.ExpressionBuilder" /> after it has called <see cref="M:System.Web.Compilation.ExpressionBuilder.ParseExpression(System.String,System.Type,System.Web.Compilation.ExpressionBuilderContext)" />.</returns>
		// Token: 0x17000551 RID: 1361
		// (get) Token: 0x06001043 RID: 4163 RVA: 0x0002C9DE File Offset: 0x0002ABDE
		// (set) Token: 0x06001044 RID: 4164 RVA: 0x0002C9E6 File Offset: 0x0002ABE6
		public object ParsedExpressionData { get; set; }

		/// <summary>Gets or sets a value indicating whether the property contains a set accessor.</summary>
		/// <returns>true if the property does not contain a set accessor, which indicates that the property is ReadOnly; otherwise, false.</returns>
		// Token: 0x17000552 RID: 1362
		// (get) Token: 0x06001045 RID: 4165 RVA: 0x0002C9EF File Offset: 0x0002ABEF
		// (set) Token: 0x06001046 RID: 4166 RVA: 0x0002C9F7 File Offset: 0x0002ABF7
		public bool ReadOnlyProperty { get; set; }

		/// <summary>Gets or sets a value indicating whether the expression is bound to a control that allows for inserting, updating, or deleting data.</summary>
		/// <returns>true if the expression is bound to a control that allows for inserting, updating, or deleting data; otherwise, false.</returns>
		// Token: 0x17000553 RID: 1363
		// (get) Token: 0x06001047 RID: 4167 RVA: 0x0002CA00 File Offset: 0x0002AC00
		// (set) Token: 0x06001048 RID: 4168 RVA: 0x0002CA08 File Offset: 0x0002AC08
		public bool TwoWayBound { get; set; }

		/// <summary>Gets or sets a value indicating whether a control's SetAttribute method can be called.</summary>
		/// <returns>true if the SetAttribute method can be called; otherwise, false.</returns>
		// Token: 0x17000554 RID: 1364
		// (get) Token: 0x06001049 RID: 4169 RVA: 0x0002CA11 File Offset: 0x0002AC11
		// (set) Token: 0x0600104A RID: 4170 RVA: 0x0002CA19 File Offset: 0x0002AC19
		public bool UseSetAttribute { get; set; }

		/// <summary>Gets or sets a value that indicates whether the value of the control property is encoded.</summary>
		/// <returns>true if the value of the control property is encoded; otherwise, false.</returns>
		// Token: 0x17000555 RID: 1365
		// (get) Token: 0x0600104B RID: 4171 RVA: 0x0002CA24 File Offset: 0x0002AC24
		// (set) Token: 0x0600104C RID: 4172 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public bool IsEncoded
		{
			[CompilerGenerated]
			get
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
				return default(bool);
			}
			[CompilerGenerated]
			set
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
			}
		}
	}
}
