using System;
using Unity;

namespace System.Web.UI
{
	/// <summary>Supports the parsing and persisting of an expression-binding instance. This class cannot be inherited.</summary>
	// Token: 0x020001CC RID: 460
	public sealed class ExpressionBinding
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Web.UI.ExpressionBinding" /> class.</summary>
		/// <param name="propertyName">A string indicating the name of the property of the object to which the <paramref name="expression" /> parameter is applied.</param>
		/// <param name="propertyType">A <see cref="T:System.Type" /> indicating the type of the property of the object to which the <paramref name="expression" /> parameter is applied.</param>
		/// <param name="expressionPrefix">A string representing the expression's prefix value.</param>
		/// <param name="expression">A string representing the value of the expression in its declarative syntax.</param>
		// Token: 0x060012BF RID: 4799 RVA: 0x00033156 File Offset: 0x00031356
		public ExpressionBinding(string propertyName, Type propertyType, string expressionPrefix, string expression)
		{
			this.propertyName = propertyName;
			this.propertyType = propertyType;
			this.prefix = expressionPrefix;
			this.expression = expression;
			this.generated = false;
		}

		/// <summary>Gets or sets a value of the expression in its declarative syntax.</summary>
		/// <returns>A string that is used with the <see cref="P:System.Web.UI.ExpressionBinding.ExpressionPrefix" /> property to perform an action.</returns>
		// Token: 0x17000601 RID: 1537
		// (get) Token: 0x060012C0 RID: 4800 RVA: 0x00033182 File Offset: 0x00031382
		// (set) Token: 0x060012C1 RID: 4801 RVA: 0x0003318A File Offset: 0x0003138A
		public string Expression
		{
			get
			{
				return this.expression;
			}
			set
			{
				this.expression = value;
			}
		}

		/// <summary>Gets or sets a value for the prefix of an expression in its declarative syntax.</summary>
		/// <returns>A string that represents the expression prefix.</returns>
		// Token: 0x17000602 RID: 1538
		// (get) Token: 0x060012C2 RID: 4802 RVA: 0x00033193 File Offset: 0x00031393
		// (set) Token: 0x060012C3 RID: 4803 RVA: 0x0003319B File Offset: 0x0003139B
		public string ExpressionPrefix
		{
			get
			{
				return this.prefix;
			}
			set
			{
				this.prefix = value;
			}
		}

		/// <summary>Gets a value indicating whether the expression was implicitly generated by the parser. </summary>
		/// <returns>true if the expression was implicitly generated by the parser; otherwise, false.</returns>
		// Token: 0x17000603 RID: 1539
		// (get) Token: 0x060012C4 RID: 4804 RVA: 0x000331A4 File Offset: 0x000313A4
		public bool Generated
		{
			get
			{
				return this.generated;
			}
		}

		/// <summary>Gets a value indicating the name of the property of the object to which the expression is applied.</summary>
		/// <returns>A value that represents the name of the property of the object to which the expression is applied.</returns>
		// Token: 0x17000604 RID: 1540
		// (get) Token: 0x060012C5 RID: 4805 RVA: 0x000331AC File Offset: 0x000313AC
		public string PropertyName
		{
			get
			{
				return this.propertyName;
			}
		}

		/// <summary>Gets a value indicating the <see cref="T:System.Type" /> of the property of the object to which the expression is applied.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the property of the object to which the expression is applied.</returns>
		// Token: 0x17000605 RID: 1541
		// (get) Token: 0x060012C6 RID: 4806 RVA: 0x000331B4 File Offset: 0x000313B4
		public Type PropertyType
		{
			get
			{
				return this.propertyType;
			}
		}

		/// <summary>Determines whether the specified object is the same instance as the current <see cref="T:System.Web.UI.ExpressionBinding" /> object.</summary>
		/// <returns>true if the specified object is the same instance as the current <see cref="T:System.Web.UI.ExpressionBinding" />; otherwise, false.</returns>
		/// <param name="obj">The object to compare with the current <see cref="T:System.Web.UI.ExpressionBinding" />.</param>
		// Token: 0x060012C7 RID: 4807 RVA: 0x000331BC File Offset: 0x000313BC
		public override bool Equals(object obj)
		{
			if (!(obj is ExpressionBinding))
			{
				return false;
			}
			ExpressionBinding expressionBinding = (ExpressionBinding)obj;
			return expressionBinding.Expression == this.expression && expressionBinding.ExpressionPrefix == this.prefix && expressionBinding.PropertyName == this.propertyName && expressionBinding.PropertyType == this.propertyType;
		}

		/// <summary>Serves as a hash function for the current <see cref="T:System.Web.UI.ExpressionBinding" /> object; suitable for hashing algorithms and data structures, such as a hash table.</summary>
		/// <returns>A hash code for the current <see cref="T:System.Web.UI.ExpressionBinding" />.</returns>
		// Token: 0x060012C8 RID: 4808 RVA: 0x00033226 File Offset: 0x00031426
		public override int GetHashCode()
		{
			return this.propertyName.GetHashCode() + (this.propertyType.GetHashCode() << 1) + (this.prefix.GetHashCode() << 2) + (this.expression.GetHashCode() << 3);
		}

		/// <summary>Gets an object representing the data from an expression as created through the <see cref="M:System.Web.Compilation.ExpressionBuilder.ParseExpression(System.String,System.Type,System.Web.Compilation.ExpressionBuilderContext)" /> method.</summary>
		/// <returns>The object representing the data from an expression as created by calling the <see cref="M:System.Web.Compilation.ExpressionBuilder.ParseExpression(System.String,System.Type,System.Web.Compilation.ExpressionBuilderContext)" /> method.</returns>
		// Token: 0x17000606 RID: 1542
		// (get) Token: 0x060012C9 RID: 4809 RVA: 0x0000E80B File Offset: 0x0000CA0B
		public object ParsedExpressionData
		{
			get
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
				return null;
			}
		}

		// Token: 0x04001431 RID: 5169
		private string propertyName;

		// Token: 0x04001432 RID: 5170
		private Type propertyType;

		// Token: 0x04001433 RID: 5171
		private string expression;

		// Token: 0x04001434 RID: 5172
		private string prefix;

		// Token: 0x04001435 RID: 5173
		private bool generated;
	}
}
