using System;

namespace System.Net
{
	/// <summary>The HTTP headers that can be specified in a server response.</summary>
	// Token: 0x0200042A RID: 1066
	public enum HttpResponseHeader
	{
		/// <summary>The Cache-Control header, which specifies caching directives that must be obeyed by all caching mechanisms along the request/response chain.</summary>
		// Token: 0x04001C45 RID: 7237
		CacheControl,
		/// <summary>The Connection header, which specifies options that are desired for a particular connection.</summary>
		// Token: 0x04001C46 RID: 7238
		Connection,
		/// <summary>The Date header, which specifies the date and time at which the response originated.</summary>
		// Token: 0x04001C47 RID: 7239
		Date,
		/// <summary>The Keep-Alive header, which specifies a parameter to be used to maintain a persistent connection.</summary>
		// Token: 0x04001C48 RID: 7240
		KeepAlive,
		/// <summary>The Pragma header, which specifies implementation-specific directives that might apply to any agent along the request/response chain.</summary>
		// Token: 0x04001C49 RID: 7241
		Pragma,
		/// <summary>The Trailer header, which specifies that the indicated header fields are present in the trailer of a message that is encoded with chunked transfer-coding.</summary>
		// Token: 0x04001C4A RID: 7242
		Trailer,
		/// <summary>The Transfer-Encoding header, which specifies what (if any) type of transformation has been applied to the message body.</summary>
		// Token: 0x04001C4B RID: 7243
		TransferEncoding,
		/// <summary>The Upgrade header, which specifies additional communications protocols that the client supports.</summary>
		// Token: 0x04001C4C RID: 7244
		Upgrade,
		/// <summary>The Via header, which specifies intermediate protocols to be used by gateway and proxy agents.</summary>
		// Token: 0x04001C4D RID: 7245
		Via,
		/// <summary>The Warning header, which specifies additional information about that status or transformation of a message that might not be reflected in the message.</summary>
		// Token: 0x04001C4E RID: 7246
		Warning,
		/// <summary>The Allow header, which specifies the set of HTTP methods that are supported.</summary>
		// Token: 0x04001C4F RID: 7247
		Allow,
		/// <summary>The Content-Length header, which specifies the length, in bytes, of the accompanying body data.</summary>
		// Token: 0x04001C50 RID: 7248
		ContentLength,
		/// <summary>The Content-Type header, which specifies the MIME type of the accompanying body data.</summary>
		// Token: 0x04001C51 RID: 7249
		ContentType,
		/// <summary>The Content-Encoding header, which specifies the encodings that have been applied to the accompanying body data.</summary>
		// Token: 0x04001C52 RID: 7250
		ContentEncoding,
		/// <summary>The Content-Langauge header, which specifies the natural language or languages of the accompanying body data.</summary>
		// Token: 0x04001C53 RID: 7251
		ContentLanguage,
		/// <summary>The Content-Location header, which specifies a URI from which the accompanying body can be obtained.</summary>
		// Token: 0x04001C54 RID: 7252
		ContentLocation,
		/// <summary>The Content-MD5 header, which specifies the MD5 digest of the accompanying body data, for the purpose of providing an end-to-end message integrity check.</summary>
		// Token: 0x04001C55 RID: 7253
		ContentMd5,
		/// <summary>The Range header, which specifies the subrange or subranges of the response that the client requests be returned in lieu of the entire response.</summary>
		// Token: 0x04001C56 RID: 7254
		ContentRange,
		/// <summary>The Expires header, which specifies the date and time after which the accompanying body data should be considered stale.</summary>
		// Token: 0x04001C57 RID: 7255
		Expires,
		/// <summary>The Last-Modified header, which specifies the date and time at which the accompanying body data was last modified.</summary>
		// Token: 0x04001C58 RID: 7256
		LastModified,
		/// <summary>The Accept-Ranges header, which specifies the range that is accepted by the server.</summary>
		// Token: 0x04001C59 RID: 7257
		AcceptRanges,
		/// <summary>The Age header, which specifies the time, in seconds, since the response was generated by the originating server.</summary>
		// Token: 0x04001C5A RID: 7258
		Age,
		/// <summary>The Etag header, which specifies the current value for the requested variant. </summary>
		// Token: 0x04001C5B RID: 7259
		ETag,
		/// <summary>The Location header, which specifies a URI to which the client is redirected to obtain the requested resource.</summary>
		// Token: 0x04001C5C RID: 7260
		Location,
		/// <summary>The Proxy-Authenticate header, which specifies that the client must authenticate itself to a proxy.</summary>
		// Token: 0x04001C5D RID: 7261
		ProxyAuthenticate,
		/// <summary>The Retry-After header, which specifies a time (in seconds), or a date and time, after which the client can retry its request.</summary>
		// Token: 0x04001C5E RID: 7262
		RetryAfter,
		/// <summary>The Server header, which specifies information about the originating server agent.</summary>
		// Token: 0x04001C5F RID: 7263
		Server,
		/// <summary>The Set-Cookie header, which specifies cookie data that is presented to the client.</summary>
		// Token: 0x04001C60 RID: 7264
		SetCookie,
		/// <summary>The Vary header, which specifies the request headers that are used to determine whether a cached response is fresh.</summary>
		// Token: 0x04001C61 RID: 7265
		Vary,
		/// <summary>The WWW-Authenticate header, which specifies that the client must authenticate itself to the server.</summary>
		// Token: 0x04001C62 RID: 7266
		WwwAuthenticate
	}
}
