using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace System.Web.Properties
{
	// Token: 0x020000EE RID: 238
	[DebuggerNonUserCode]
	[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[CompilerGenerated]
	internal class Resources
	{
		// Token: 0x06000CC6 RID: 3270 RVA: 0x00002050 File Offset: 0x00000250
		internal Resources()
		{
		}

		// Token: 0x1700045D RID: 1117
		// (get) Token: 0x06000CC7 RID: 3271 RVA: 0x00022E85 File Offset: 0x00021085
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static ResourceManager ResourceManager
		{
			get
			{
				if (Resources.resourceMan == null)
				{
					Resources.resourceMan = new ResourceManager("TranslationResources", typeof(Resources).Assembly);
				}
				return Resources.resourceMan;
			}
		}

		// Token: 0x1700045E RID: 1118
		// (get) Token: 0x06000CC8 RID: 3272 RVA: 0x00022EB1 File Offset: 0x000210B1
		// (set) Token: 0x06000CC9 RID: 3273 RVA: 0x00022EB8 File Offset: 0x000210B8
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static CultureInfo Culture
		{
			get
			{
				return Resources.resourceCulture;
			}
			set
			{
				Resources.resourceCulture = value;
			}
		}

		// Token: 0x1700045F RID: 1119
		// (get) Token: 0x06000CCA RID: 3274 RVA: 0x00022EC0 File Offset: 0x000210C0
		internal static string ErrArgumentNull
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrArgumentNull", Resources.resourceCulture);
			}
		}

		// Token: 0x17000460 RID: 1120
		// (get) Token: 0x06000CCB RID: 3275 RVA: 0x00022ED6 File Offset: 0x000210D6
		internal static string ErrArgumentNullOrEmpty
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrArgumentNullOrEmpty", Resources.resourceCulture);
			}
		}

		// Token: 0x17000461 RID: 1121
		// (get) Token: 0x06000CCC RID: 3276 RVA: 0x00022EEC File Offset: 0x000210EC
		internal static string ErrAutoGeneratedKeyNotSupported
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrAutoGeneratedKeyNotSupported", Resources.resourceCulture);
			}
		}

		// Token: 0x17000462 RID: 1122
		// (get) Token: 0x06000CCD RID: 3277 RVA: 0x00022F02 File Offset: 0x00021102
		internal static string ErrCantDecodeHashedPw
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrCantDecodeHashedPw", Resources.resourceCulture);
			}
		}

		// Token: 0x17000463 RID: 1123
		// (get) Token: 0x06000CCE RID: 3278 RVA: 0x00022F18 File Offset: 0x00021118
		internal static string ErrCantDeletePopulatedRole
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrCantDeletePopulatedRole", Resources.resourceCulture);
			}
		}

		// Token: 0x17000464 RID: 1124
		// (get) Token: 0x06000CCF RID: 3279 RVA: 0x00022F2E File Offset: 0x0002112E
		internal static string ErrCantLogoutUser
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrCantLogoutUser", Resources.resourceCulture);
			}
		}

		// Token: 0x17000465 RID: 1125
		// (get) Token: 0x06000CD0 RID: 3280 RVA: 0x00022F44 File Offset: 0x00021144
		internal static string ErrCantRetrieveHashedPw
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrCantRetrieveHashedPw", Resources.resourceCulture);
			}
		}

		// Token: 0x17000466 RID: 1126
		// (get) Token: 0x06000CD1 RID: 3281 RVA: 0x00022F5A File Offset: 0x0002115A
		internal static string ErrCantUpdateFailtureCount
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrCantUpdateFailtureCount", Resources.resourceCulture);
			}
		}

		// Token: 0x17000467 RID: 1127
		// (get) Token: 0x06000CD2 RID: 3282 RVA: 0x00022F70 File Offset: 0x00021170
		internal static string ErrCantUpdateFailtureCountAndWindowStart
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrCantUpdateFailtureCountAndWindowStart", Resources.resourceCulture);
			}
		}

		// Token: 0x17000468 RID: 1128
		// (get) Token: 0x06000CD3 RID: 3283 RVA: 0x00022F86 File Offset: 0x00021186
		internal static string ErrConnectionStringNullOrEmpty
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrConnectionStringNullOrEmpty", Resources.resourceCulture);
			}
		}

		// Token: 0x17000469 RID: 1129
		// (get) Token: 0x06000CD4 RID: 3284 RVA: 0x00022F9C File Offset: 0x0002119C
		internal static string ErrIncorrectPasswordAnswer
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrIncorrectPasswordAnswer", Resources.resourceCulture);
			}
		}

		// Token: 0x1700046A RID: 1130
		// (get) Token: 0x06000CD5 RID: 3285 RVA: 0x00022FB2 File Offset: 0x000211B2
		internal static string ErrOperationAborted
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrOperationAborted", Resources.resourceCulture);
			}
		}

		// Token: 0x1700046B RID: 1131
		// (get) Token: 0x06000CD6 RID: 3286 RVA: 0x00022FC8 File Offset: 0x000211C8
		internal static string ErrPasswordAnswerRequired
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPasswordAnswerRequired", Resources.resourceCulture);
			}
		}

		// Token: 0x1700046C RID: 1132
		// (get) Token: 0x06000CD7 RID: 3287 RVA: 0x00022FDE File Offset: 0x000211DE
		internal static string ErrPasswordChangeCanceled
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPasswordChangeCanceled", Resources.resourceCulture);
			}
		}

		// Token: 0x1700046D RID: 1133
		// (get) Token: 0x06000CD8 RID: 3288 RVA: 0x00022FF4 File Offset: 0x000211F4
		internal static string ErrPasswordResetAborted
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPasswordResetAborted", Resources.resourceCulture);
			}
		}

		// Token: 0x1700046E RID: 1134
		// (get) Token: 0x06000CD9 RID: 3289 RVA: 0x0002300A File Offset: 0x0002120A
		internal static string ErrPasswordResetCanceled
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPasswordResetCanceled", Resources.resourceCulture);
			}
		}

		// Token: 0x1700046F RID: 1135
		// (get) Token: 0x06000CDA RID: 3290 RVA: 0x00023020 File Offset: 0x00021220
		internal static string ErrPasswordResetNotEnabled
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPasswordResetNotEnabled", Resources.resourceCulture);
			}
		}

		// Token: 0x17000470 RID: 1136
		// (get) Token: 0x06000CDB RID: 3291 RVA: 0x00023036 File Offset: 0x00021236
		internal static string ErrPasswordRetrievalNotEnabled
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPasswordRetrievalNotEnabled", Resources.resourceCulture);
			}
		}

		// Token: 0x17000471 RID: 1137
		// (get) Token: 0x06000CDC RID: 3292 RVA: 0x0002304C File Offset: 0x0002124C
		internal static string ErrProfileAlreadyExist
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrProfileAlreadyExist", Resources.resourceCulture);
			}
		}

		// Token: 0x17000472 RID: 1138
		// (get) Token: 0x06000CDD RID: 3293 RVA: 0x00023062 File Offset: 0x00021262
		internal static string ErrPwFormatNotSupported
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrPwFormatNotSupported", Resources.resourceCulture);
			}
		}

		// Token: 0x17000473 RID: 1139
		// (get) Token: 0x06000CDE RID: 3294 RVA: 0x00023078 File Offset: 0x00021278
		internal static string ErrRoleAlreadyExist
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrRoleAlreadyExist", Resources.resourceCulture);
			}
		}

		// Token: 0x17000474 RID: 1140
		// (get) Token: 0x06000CDF RID: 3295 RVA: 0x0002308E File Offset: 0x0002128E
		internal static string ErrRoleNotExist
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrRoleNotExist", Resources.resourceCulture);
			}
		}

		// Token: 0x17000475 RID: 1141
		// (get) Token: 0x06000CE0 RID: 3296 RVA: 0x000230A4 File Offset: 0x000212A4
		internal static string ErrRollbackFailed
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrRollbackFailed", Resources.resourceCulture);
			}
		}

		// Token: 0x17000476 RID: 1142
		// (get) Token: 0x06000CE1 RID: 3297 RVA: 0x000230BA File Offset: 0x000212BA
		internal static string ErrUserAlreadyInRole
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrUserAlreadyInRole", Resources.resourceCulture);
			}
		}

		// Token: 0x17000477 RID: 1143
		// (get) Token: 0x06000CE2 RID: 3298 RVA: 0x000230D0 File Offset: 0x000212D0
		internal static string ErrUserIsLoggedOut
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrUserIsLoggedOut", Resources.resourceCulture);
			}
		}

		// Token: 0x17000478 RID: 1144
		// (get) Token: 0x06000CE3 RID: 3299 RVA: 0x000230E6 File Offset: 0x000212E6
		internal static string ErrUserIsNotInRole
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrUserIsNotInRole", Resources.resourceCulture);
			}
		}

		// Token: 0x17000479 RID: 1145
		// (get) Token: 0x06000CE4 RID: 3300 RVA: 0x000230FC File Offset: 0x000212FC
		internal static string ErrUserNotFound
		{
			get
			{
				return Resources.ResourceManager.GetString("ErrUserNotFound", Resources.resourceCulture);
			}
		}

		// Token: 0x1700047A RID: 1146
		// (get) Token: 0x06000CE5 RID: 3301 RVA: 0x00023112 File Offset: 0x00021312
		internal static string LogRollbackAttempt
		{
			get
			{
				return Resources.ResourceManager.GetString("LogRollbackAttempt", Resources.resourceCulture);
			}
		}

		// Token: 0x1700047B RID: 1147
		// (get) Token: 0x06000CE6 RID: 3302 RVA: 0x00023128 File Offset: 0x00021328
		internal static string MembershipProviderDefaultDescription
		{
			get
			{
				return Resources.ResourceManager.GetString("MembershipProviderDefaultDescription", Resources.resourceCulture);
			}
		}

		// Token: 0x1700047C RID: 1148
		// (get) Token: 0x06000CE7 RID: 3303 RVA: 0x0002313E File Offset: 0x0002133E
		internal static string MembershipProviderDefaultName
		{
			get
			{
				return Resources.ResourceManager.GetString("MembershipProviderDefaultName", Resources.resourceCulture);
			}
		}

		// Token: 0x1700047D RID: 1149
		// (get) Token: 0x06000CE8 RID: 3304 RVA: 0x00023154 File Offset: 0x00021354
		internal static string ProfileProviderDefaultDescription
		{
			get
			{
				return Resources.ResourceManager.GetString("ProfileProviderDefaultDescription", Resources.resourceCulture);
			}
		}

		// Token: 0x1700047E RID: 1150
		// (get) Token: 0x06000CE9 RID: 3305 RVA: 0x0002316A File Offset: 0x0002136A
		internal static string ProfileProviderDefaultName
		{
			get
			{
				return Resources.ResourceManager.GetString("ProfileProviderDefaultName", Resources.resourceCulture);
			}
		}

		// Token: 0x1700047F RID: 1151
		// (get) Token: 0x06000CEA RID: 3306 RVA: 0x00023180 File Offset: 0x00021380
		internal static string RoleProviderDefaultDescription
		{
			get
			{
				return Resources.ResourceManager.GetString("RoleProviderDefaultDescription", Resources.resourceCulture);
			}
		}

		// Token: 0x17000480 RID: 1152
		// (get) Token: 0x06000CEB RID: 3307 RVA: 0x00023196 File Offset: 0x00021396
		internal static string RoleProviderDefaultName
		{
			get
			{
				return Resources.ResourceManager.GetString("RoleProviderDefaultName", Resources.resourceCulture);
			}
		}

		// Token: 0x17000481 RID: 1153
		// (get) Token: 0x06000CEC RID: 3308 RVA: 0x000231AC File Offset: 0x000213AC
		internal static string SessionStoreProviderDefaultDescription
		{
			get
			{
				return Resources.ResourceManager.GetString("SessionStoreProviderDefaultDescription", Resources.resourceCulture);
			}
		}

		// Token: 0x17000482 RID: 1154
		// (get) Token: 0x06000CED RID: 3309 RVA: 0x000231C2 File Offset: 0x000213C2
		internal static string SessionStoreProviderDefaultName
		{
			get
			{
				return Resources.ResourceManager.GetString("SessionStoreProviderDefaultName", Resources.resourceCulture);
			}
		}

		// Token: 0x04001121 RID: 4385
		private static ResourceManager resourceMan;

		// Token: 0x04001122 RID: 4386
		private static CultureInfo resourceCulture;
	}
}
