using System;

namespace System.Data.Common
{
	/// <summary>Provides data for the RowUpdated event of a .NET Framework data provider.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x0200035D RID: 861
	public class RowUpdatedEventArgs : EventArgs
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Data.Common.RowUpdatedEventArgs" /> class.</summary>
		/// <param name="dataRow">The <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		/// <param name="command">The <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called. </param>
		/// <param name="statementType">The type of SQL statement executed. </param>
		/// <param name="tableMapping">The <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </param>
		// Token: 0x060028BD RID: 10429 RVA: 0x000B3BF4 File Offset: 0x000B1DF4
		public RowUpdatedEventArgs(DataRow dataRow, IDbCommand command, StatementType statementType, DataTableMapping tableMapping)
		{
			if (statementType > StatementType.Batch)
			{
				throw ADP.InvalidStatementType(statementType);
			}
			this._dataRow = dataRow;
			this._command = command;
			this._statementType = statementType;
			this._tableMapping = tableMapping;
		}

		/// <summary>Gets the <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> executed when <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> is called.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700070A RID: 1802
		// (get) Token: 0x060028BE RID: 10430 RVA: 0x000B3C24 File Offset: 0x000B1E24
		public IDbCommand Command
		{
			get
			{
				return this._command;
			}
		}

		/// <summary>Gets any errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> was executed.</summary>
		/// <returns>The errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> was executed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700070B RID: 1803
		// (get) Token: 0x060028BF RID: 10431 RVA: 0x000B3C2C File Offset: 0x000B1E2C
		// (set) Token: 0x060028C0 RID: 10432 RVA: 0x000B3C34 File Offset: 0x000B1E34
		public Exception Errors
		{
			get
			{
				return this._errors;
			}
			set
			{
				this._errors = value;
			}
		}

		/// <summary>Gets the number of rows changed, inserted, or deleted by execution of the SQL statement.</summary>
		/// <returns>The number of rows changed, inserted, or deleted; 0 if no rows were affected or the statement failed; and -1 for SELECT statements.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700070C RID: 1804
		// (get) Token: 0x060028C1 RID: 10433 RVA: 0x000B3C3D File Offset: 0x000B1E3D
		public int RecordsAffected
		{
			get
			{
				return this._recordsAffected;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.DataRow" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700070D RID: 1805
		// (get) Token: 0x060028C2 RID: 10434 RVA: 0x000B3C45 File Offset: 0x000B1E45
		public DataRow Row
		{
			get
			{
				return this._dataRow;
			}
		}

		// Token: 0x1700070E RID: 1806
		// (get) Token: 0x060028C3 RID: 10435 RVA: 0x000B3C4D File Offset: 0x000B1E4D
		internal DataRow[] Rows
		{
			get
			{
				return this._dataRows;
			}
		}

		/// <summary>Gets the number of rows processed in a batch of updated records.</summary>
		/// <returns>int that specifies the number of row processed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700070F RID: 1807
		// (get) Token: 0x060028C4 RID: 10436 RVA: 0x000B3C58 File Offset: 0x000B1E58
		public int RowCount
		{
			get
			{
				DataRow[] dataRows = this._dataRows;
				if (dataRows != null)
				{
					return dataRows.Length;
				}
				if (this._dataRow == null)
				{
					return 0;
				}
				return 1;
			}
		}

		/// <summary>Gets the type of SQL statement executed.</summary>
		/// <returns>The type of SQL statement executed.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000710 RID: 1808
		// (get) Token: 0x060028C5 RID: 10437 RVA: 0x000B3C7E File Offset: 0x000B1E7E
		public StatementType StatementType
		{
			get
			{
				return this._statementType;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.UpdateStatus" /> of the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> property.</summary>
		/// <returns>One of the <see cref="T:System.Data.UpdateStatus" /> values. The default is Continue.</returns>
		/// <filterpriority>1</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x17000711 RID: 1809
		// (get) Token: 0x060028C6 RID: 10438 RVA: 0x000B3C86 File Offset: 0x000B1E86
		// (set) Token: 0x060028C7 RID: 10439 RVA: 0x000B3C8E File Offset: 0x000B1E8E
		public UpdateStatus Status
		{
			get
			{
				return this._status;
			}
			set
			{
				if (value <= UpdateStatus.SkipAllRemainingRows)
				{
					this._status = value;
					return;
				}
				throw ADP.InvalidUpdateStatus(value);
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.Common.DataTableMapping" /> sent through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000712 RID: 1810
		// (get) Token: 0x060028C8 RID: 10440 RVA: 0x000B3CA2 File Offset: 0x000B1EA2
		public DataTableMapping TableMapping
		{
			get
			{
				return this._tableMapping;
			}
		}

		// Token: 0x060028C9 RID: 10441 RVA: 0x000B3CAA File Offset: 0x000B1EAA
		internal void AdapterInit(DataRow[] dataRows)
		{
			this._statementType = StatementType.Batch;
			this._dataRows = dataRows;
			if (dataRows != null && 1 == dataRows.Length)
			{
				this._dataRow = dataRows[0];
			}
		}

		// Token: 0x060028CA RID: 10442 RVA: 0x000B3CCC File Offset: 0x000B1ECC
		internal void AdapterInit(int recordsAffected)
		{
			this._recordsAffected = recordsAffected;
		}

		/// <summary>Copies references to the modified rows into the provided array.</summary>
		/// <param name="array">The array of <see cref="T:System.Data.DataRow" /> to copy into.</param>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x060028CB RID: 10443 RVA: 0x000B3CD5 File Offset: 0x000B1ED5
		public void CopyToRows(DataRow[] array)
		{
			this.CopyToRows(array, 0);
		}

		/// <summary>Copies references to the modified rows into the provided array. </summary>
		/// <param name="array">The array of <see cref="T:System.Data.DataRow" /> to copy into.</param>
		/// <param name="arrayIndex">The index in the array to start copying into.</param>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x060028CC RID: 10444 RVA: 0x000B3CE0 File Offset: 0x000B1EE0
		public void CopyToRows(DataRow[] array, int arrayIndex)
		{
			DataRow[] dataRows = this._dataRows;
			if (dataRows != null)
			{
				dataRows.CopyTo(array, arrayIndex);
				return;
			}
			if (array == null)
			{
				throw ADP.ArgumentNull("array");
			}
			array[arrayIndex] = this.Row;
		}

		// Token: 0x04001921 RID: 6433
		private IDbCommand _command;

		// Token: 0x04001922 RID: 6434
		private StatementType _statementType;

		// Token: 0x04001923 RID: 6435
		private DataTableMapping _tableMapping;

		// Token: 0x04001924 RID: 6436
		private Exception _errors;

		// Token: 0x04001925 RID: 6437
		private DataRow _dataRow;

		// Token: 0x04001926 RID: 6438
		private DataRow[] _dataRows;

		// Token: 0x04001927 RID: 6439
		private UpdateStatus _status;

		// Token: 0x04001928 RID: 6440
		private int _recordsAffected;
	}
}
