using System;
using System.CodeDom;
using System.Collections.Specialized;
using System.Xml.Schema;

namespace System.Xml.Serialization.Advanced
{
	// Token: 0x02000382 RID: 898
	internal class MappedTypeDesc
	{
		// Token: 0x06002466 RID: 9318 RVA: 0x000DD800 File Offset: 0x000DBA00
		internal MappedTypeDesc(string clrType, string name, string ns, XmlSchemaType xsdType, XmlSchemaObject context, SchemaImporterExtension extension, CodeNamespace code, StringCollection references)
		{
			this.clrType = clrType.Replace('+', '.');
			this.name = name;
			this.ns = ns;
			this.xsdType = xsdType;
			this.context = context;
			this.code = code;
			this.references = references;
			this.extension = extension;
		}

		// Token: 0x17000732 RID: 1842
		// (get) Token: 0x06002467 RID: 9319 RVA: 0x000DD859 File Offset: 0x000DBA59
		internal SchemaImporterExtension Extension
		{
			get
			{
				return this.extension;
			}
		}

		// Token: 0x17000733 RID: 1843
		// (get) Token: 0x06002468 RID: 9320 RVA: 0x000DD861 File Offset: 0x000DBA61
		internal string Name
		{
			get
			{
				return this.clrType;
			}
		}

		// Token: 0x17000734 RID: 1844
		// (get) Token: 0x06002469 RID: 9321 RVA: 0x000DD869 File Offset: 0x000DBA69
		internal StringCollection ReferencedAssemblies
		{
			get
			{
				if (this.references == null)
				{
					this.references = new StringCollection();
				}
				return this.references;
			}
		}

		// Token: 0x0600246A RID: 9322 RVA: 0x000DD884 File Offset: 0x000DBA84
		internal CodeTypeDeclaration ExportTypeDefinition(CodeNamespace codeNamespace, CodeCompileUnit codeCompileUnit)
		{
			if (this.exported)
			{
				return null;
			}
			this.exported = true;
			foreach (object obj in this.code.Imports)
			{
				CodeNamespaceImport codeNamespaceImport = (CodeNamespaceImport)obj;
				codeNamespace.Imports.Add(codeNamespaceImport);
			}
			CodeTypeDeclaration codeTypeDeclaration = null;
			string @string = Res.GetString("This type definition was generated by {0} schema importer extension.", new object[] { this.extension.GetType().FullName });
			foreach (object obj2 in this.code.Types)
			{
				CodeTypeDeclaration codeTypeDeclaration2 = (CodeTypeDeclaration)obj2;
				if (this.clrType == codeTypeDeclaration2.Name)
				{
					if (codeTypeDeclaration != null)
					{
						throw new InvalidOperationException(Res.GetString("Schema importer extension {0} generated duplicate type definitions: {1}.", new object[]
						{
							this.extension.GetType().FullName,
							this.clrType
						}));
					}
					codeTypeDeclaration = codeTypeDeclaration2;
				}
				codeTypeDeclaration2.Comments.Add(new CodeCommentStatement(@string, false));
				codeNamespace.Types.Add(codeTypeDeclaration2);
			}
			if (codeCompileUnit != null)
			{
				foreach (string text in this.ReferencedAssemblies)
				{
					if (!codeCompileUnit.ReferencedAssemblies.Contains(text))
					{
						codeCompileUnit.ReferencedAssemblies.Add(text);
					}
				}
			}
			return codeTypeDeclaration;
		}

		// Token: 0x040018BE RID: 6334
		private string name;

		// Token: 0x040018BF RID: 6335
		private string ns;

		// Token: 0x040018C0 RID: 6336
		private XmlSchemaType xsdType;

		// Token: 0x040018C1 RID: 6337
		private XmlSchemaObject context;

		// Token: 0x040018C2 RID: 6338
		private string clrType;

		// Token: 0x040018C3 RID: 6339
		private SchemaImporterExtension extension;

		// Token: 0x040018C4 RID: 6340
		private CodeNamespace code;

		// Token: 0x040018C5 RID: 6341
		private bool exported;

		// Token: 0x040018C6 RID: 6342
		private StringCollection references;
	}
}
