using System;

namespace System.CodeDom.Compiler
{
	/// <summary>Identifies code generated by a tool. This class cannot be inherited.</summary>
	// Token: 0x020007B7 RID: 1975
	[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
	public sealed class GeneratedCodeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.CodeDom.Compiler.GeneratedCodeAttribute" /> class specifying the name and version of the tool that generated the code.</summary>
		/// <param name="tool">The name of the tool that generated the code.</param>
		/// <param name="version">The version of the tool that generated the code.</param>
		// Token: 0x06003FB8 RID: 16312 RVA: 0x000E0108 File Offset: 0x000DE308
		public GeneratedCodeAttribute(string tool, string version)
		{
			this.tool = tool;
			this.version = version;
		}

		/// <summary>Gets the name of the tool that generated the code.</summary>
		/// <returns>The name of the tool that generated to code.</returns>
		// Token: 0x17000F54 RID: 3924
		// (get) Token: 0x06003FB9 RID: 16313 RVA: 0x000E011E File Offset: 0x000DE31E
		public string Tool
		{
			get
			{
				return this.tool;
			}
		}

		/// <summary>Gets the version of the tool that generated the code.</summary>
		/// <returns>The version of the tool that generated the code.</returns>
		// Token: 0x17000F55 RID: 3925
		// (get) Token: 0x06003FBA RID: 16314 RVA: 0x000E0126 File Offset: 0x000DE326
		public string Version
		{
			get
			{
				return this.version;
			}
		}

		// Token: 0x04002E7C RID: 11900
		private readonly string tool;

		// Token: 0x04002E7D RID: 11901
		private readonly string version;
	}
}
