using System;
using System.Collections;
using System.Globalization;

namespace System.Xml.Serialization
{
	/// <summary>Maintains a group of names for related code entities or type mappings that are generated by the .NET Framework's XML serialization infrastructure.</summary>
	// Token: 0x020002D3 RID: 723
	public class CodeIdentifiers
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> class. </summary>
		// Token: 0x06001B2F RID: 6959 RVA: 0x00096F97 File Offset: 0x00095197
		public CodeIdentifiers()
			: this(true)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> class and determines whether code identifiers are case sensitive.</summary>
		/// <param name="caseSensitive">true if identifiers are case sensitive; otherwise, false. </param>
		// Token: 0x06001B30 RID: 6960 RVA: 0x00096FA0 File Offset: 0x000951A0
		public CodeIdentifiers(bool caseSensitive)
		{
			if (caseSensitive)
			{
				this.identifiers = new Hashtable();
				this.reservedIdentifiers = new Hashtable();
			}
			else
			{
				IEqualityComparer equalityComparer = new CaseInsensitiveKeyComparer();
				this.identifiers = new Hashtable(equalityComparer);
				this.reservedIdentifiers = new Hashtable(equalityComparer);
			}
			this.list = new ArrayList();
		}

		/// <summary>Removes all code entities or type mappings, including their names, from the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		// Token: 0x06001B31 RID: 6961 RVA: 0x00096FF7 File Offset: 0x000951F7
		public void Clear()
		{
			this.identifiers.Clear();
			this.list.Clear();
		}

		/// <summary>Gets or sets a value that indicates whether the instance uses camel case. </summary>
		/// <returns>true to indicate that the instance uses camel case; false to indicate that the instance uses Pascal case.</returns>
		// Token: 0x1700052B RID: 1323
		// (get) Token: 0x06001B32 RID: 6962 RVA: 0x0009700F File Offset: 0x0009520F
		// (set) Token: 0x06001B33 RID: 6963 RVA: 0x00097017 File Offset: 0x00095217
		public bool UseCamelCasing
		{
			get
			{
				return this.camelCase;
			}
			set
			{
				this.camelCase = value;
			}
		}

		/// <summary>Ensures that the input is of the correct case by modifying the name according to the value of the <see cref="P:System.Xml.Serialization.CodeIdentifiers.UseCamelCasing" /> property. </summary>
		/// <returns>A string that is the same as the input identifier or has the first letter's case modified.</returns>
		/// <param name="identifier">The name to possibly modify.</param>
		// Token: 0x06001B34 RID: 6964 RVA: 0x00097020 File Offset: 0x00095220
		public string MakeRightCase(string identifier)
		{
			if (this.camelCase)
			{
				return CodeIdentifier.MakeCamel(identifier);
			}
			return CodeIdentifier.MakePascal(identifier);
		}

		/// <summary>Determines whether the input name conflicts with another name within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope and, if it does, generates a modified string. </summary>
		/// <returns>The identifier parameter value or a modified string if there is a name collision.</returns>
		/// <param name="identifier">The name to modify if it is not already unique.</param>
		// Token: 0x06001B35 RID: 6965 RVA: 0x00097038 File Offset: 0x00095238
		public string MakeUnique(string identifier)
		{
			if (this.IsInUse(identifier))
			{
				int num = 1;
				string text;
				for (;;)
				{
					text = identifier + num.ToString(CultureInfo.InvariantCulture);
					if (!this.IsInUse(text))
					{
						break;
					}
					num++;
				}
				identifier = text;
			}
			if (identifier.Length > 511)
			{
				return this.MakeUnique("Item");
			}
			return identifier;
		}

		/// <summary>Prevents a specified name from being used within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <param name="identifier">A name that will not be available within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" />instance's scope.</param>
		// Token: 0x06001B36 RID: 6966 RVA: 0x00097091 File Offset: 0x00095291
		public void AddReserved(string identifier)
		{
			this.reservedIdentifiers.Add(identifier, identifier);
		}

		/// <summary>Removes the input name from the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's reserved names. </summary>
		/// <param name="identifier">A name that will be made available within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope.</param>
		// Token: 0x06001B37 RID: 6967 RVA: 0x000970A0 File Offset: 0x000952A0
		public void RemoveReserved(string identifier)
		{
			this.reservedIdentifiers.Remove(identifier);
		}

		/// <summary>Adds a named code entity or type mapping to the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope, ensuring that the name is unique within the scope. </summary>
		/// <returns>The identifier parameter value or a modified string if there is a name collision.</returns>
		/// <param name="identifier">A candidate name that is used to index the code entity.</param>
		/// <param name="value">The code entity or type mapping information.</param>
		// Token: 0x06001B38 RID: 6968 RVA: 0x000970AE File Offset: 0x000952AE
		public string AddUnique(string identifier, object value)
		{
			identifier = this.MakeUnique(identifier);
			this.Add(identifier, value);
			return identifier;
		}

		/// <summary>Determines whether a specified name is already being used within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <returns>true if the name is already in use; otherwise, false.</returns>
		/// <param name="identifier">The name to check for use within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope.</param>
		// Token: 0x06001B39 RID: 6969 RVA: 0x000970C2 File Offset: 0x000952C2
		public bool IsInUse(string identifier)
		{
			return this.identifiers.Contains(identifier) || this.reservedIdentifiers.Contains(identifier);
		}

		/// <summary>Adds a named code entity or type mapping to the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <param name="identifier">A name that is used to index the code entity.</param>
		/// <param name="value">The code entity or type mapping information.</param>
		// Token: 0x06001B3A RID: 6970 RVA: 0x000970E0 File Offset: 0x000952E0
		public void Add(string identifier, object value)
		{
			this.identifiers.Add(identifier, value);
			this.list.Add(value);
		}

		/// <summary>Removes from the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope the code entity or type mapping identified by the input name. </summary>
		/// <param name="identifier">The name of the code entity or type mapping information to remove.</param>
		// Token: 0x06001B3B RID: 6971 RVA: 0x000970FC File Offset: 0x000952FC
		public void Remove(string identifier)
		{
			this.list.Remove(this.identifiers[identifier]);
			this.identifiers.Remove(identifier);
		}

		/// <summary>Returns an array of the code entities or type mappings within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <returns>An array of the code entities or type mappings that is stored by the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> object.</returns>
		/// <param name="type">The type of all the code entities or type mappings for the instance.</param>
		// Token: 0x06001B3C RID: 6972 RVA: 0x00097124 File Offset: 0x00095324
		public object ToArray(Type type)
		{
			Array array = Array.CreateInstance(type, this.list.Count);
			this.list.CopyTo(array, 0);
			return array;
		}

		// Token: 0x06001B3D RID: 6973 RVA: 0x00097154 File Offset: 0x00095354
		internal CodeIdentifiers Clone()
		{
			return new CodeIdentifiers
			{
				identifiers = (Hashtable)this.identifiers.Clone(),
				reservedIdentifiers = (Hashtable)this.reservedIdentifiers.Clone(),
				list = (ArrayList)this.list.Clone(),
				camelCase = this.camelCase
			};
		}

		// Token: 0x040015CD RID: 5581
		private Hashtable identifiers;

		// Token: 0x040015CE RID: 5582
		private Hashtable reservedIdentifiers;

		// Token: 0x040015CF RID: 5583
		private ArrayList list;

		// Token: 0x040015D0 RID: 5584
		private bool camelCase;
	}
}
