using System;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize the class member as an encoded SOAP attribute.</summary>
	// Token: 0x0200030A RID: 778
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class SoapAttributeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapAttributeAttribute" /> class.</summary>
		// Token: 0x06001D1B RID: 7451 RVA: 0x0009F79F File Offset: 0x0009D99F
		public SoapAttributeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapAttributeAttribute" /> class using the specified value as the name of the XML attribute.</summary>
		/// <param name="attributeName">The name of the XML attribute. </param>
		// Token: 0x06001D1C RID: 7452 RVA: 0x0009F7A7 File Offset: 0x0009D9A7
		public SoapAttributeAttribute(string attributeName)
		{
			this.attributeName = attributeName;
		}

		/// <summary>Gets or sets the name of the XML attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>The name of the XML attribute. The default is the member identifier.</returns>
		// Token: 0x170005C5 RID: 1477
		// (get) Token: 0x06001D1D RID: 7453 RVA: 0x0009F7B6 File Offset: 0x0009D9B6
		// (set) Token: 0x06001D1E RID: 7454 RVA: 0x0009F7CC File Offset: 0x0009D9CC
		public string AttributeName
		{
			get
			{
				if (this.attributeName != null)
				{
					return this.attributeName;
				}
				return string.Empty;
			}
			set
			{
				this.attributeName = value;
			}
		}

		/// <summary>Gets or sets the XML namespace of the XML attribute.</summary>
		/// <returns>The XML namespace of the XML attribute.</returns>
		// Token: 0x170005C6 RID: 1478
		// (get) Token: 0x06001D1F RID: 7455 RVA: 0x0009F7D5 File Offset: 0x0009D9D5
		// (set) Token: 0x06001D20 RID: 7456 RVA: 0x0009F7DD File Offset: 0x0009D9DD
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition language (XSD) data type of the SOAP attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the .NET data type. </exception>
		// Token: 0x170005C7 RID: 1479
		// (get) Token: 0x06001D21 RID: 7457 RVA: 0x0009F7E6 File Offset: 0x0009D9E6
		// (set) Token: 0x06001D22 RID: 7458 RVA: 0x0009F7FC File Offset: 0x0009D9FC
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		// Token: 0x04001686 RID: 5766
		private string attributeName;

		// Token: 0x04001687 RID: 5767
		private string ns;

		// Token: 0x04001688 RID: 5768
		private string dataType;
	}
}
