using System;

namespace System.Xml.Serialization
{
	/// <summary>Controls how the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes an enumeration member.</summary>
	// Token: 0x02000310 RID: 784
	[AttributeUsage(AttributeTargets.Field)]
	public class SoapEnumAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapEnumAttribute" /> class.</summary>
		// Token: 0x06001D51 RID: 7505 RVA: 0x0009F79F File Offset: 0x0009D99F
		public SoapEnumAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapEnumAttribute" /> class using the specified element name.</summary>
		/// <param name="name">The XML element name generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />. </param>
		// Token: 0x06001D52 RID: 7506 RVA: 0x000A029B File Offset: 0x0009E49B
		public SoapEnumAttribute(string name)
		{
			this.name = name;
		}

		/// <summary>Gets or sets the value generated in an XML document when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes an enumeration, or the value recognized when it deserializes the enumeration member.</summary>
		/// <returns>The value generated in an XML document when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes the enumeration, or the value recognized when it deserializes the enumeration member.</returns>
		// Token: 0x170005D4 RID: 1492
		// (get) Token: 0x06001D53 RID: 7507 RVA: 0x000A02AA File Offset: 0x0009E4AA
		// (set) Token: 0x06001D54 RID: 7508 RVA: 0x000A02C0 File Offset: 0x0009E4C0
		public string Name
		{
			get
			{
				if (this.name != null)
				{
					return this.name;
				}
				return string.Empty;
			}
			set
			{
				this.name = value;
			}
		}

		// Token: 0x04001698 RID: 5784
		private string name;
	}
}
