using System;

namespace System.Xml.Serialization
{
	/// <summary>Controls the schema generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> when a class instance is serialized as SOAP encoded XML.</summary>
	// Token: 0x02000317 RID: 791
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Interface)]
	public class SoapTypeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class.</summary>
		// Token: 0x06001DBA RID: 7610 RVA: 0x000A3D78 File Offset: 0x000A1F78
		public SoapTypeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class and specifies the name of the XML type.</summary>
		/// <param name="typeName">The name of the XML type that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates when it serializes the class instance (and recognizes when it deserializes the class instance). </param>
		// Token: 0x06001DBB RID: 7611 RVA: 0x000A3D87 File Offset: 0x000A1F87
		public SoapTypeAttribute(string typeName)
		{
			this.typeName = typeName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class and specifies the name and XML namespace of the type.</summary>
		/// <param name="typeName">The name of the XML type that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates when it serializes the class instance (and recognizes when it deserializes the class instance). </param>
		/// <param name="ns">The XML namespace of the type. </param>
		// Token: 0x06001DBC RID: 7612 RVA: 0x000A3D9D File Offset: 0x000A1F9D
		public SoapTypeAttribute(string typeName, string ns)
		{
			this.typeName = typeName;
			this.ns = ns;
		}

		/// <summary>Gets or sets a value that indicates whether to include the type in SOAP-encoded XML Schema documents.</summary>
		/// <returns>true to include the type in SOAP-encoded XML Schema documents; otherwise, false. The default is true.</returns>
		// Token: 0x170005D9 RID: 1497
		// (get) Token: 0x06001DBD RID: 7613 RVA: 0x000A3DBA File Offset: 0x000A1FBA
		// (set) Token: 0x06001DBE RID: 7614 RVA: 0x000A3DC2 File Offset: 0x000A1FC2
		public bool IncludeInSchema
		{
			get
			{
				return this.includeInSchema;
			}
			set
			{
				this.includeInSchema = value;
			}
		}

		/// <summary>Gets or sets the name of the XML type.</summary>
		/// <returns>The name of the XML type. The default is the class name.</returns>
		// Token: 0x170005DA RID: 1498
		// (get) Token: 0x06001DBF RID: 7615 RVA: 0x000A3DCB File Offset: 0x000A1FCB
		// (set) Token: 0x06001DC0 RID: 7616 RVA: 0x000A3DE1 File Offset: 0x000A1FE1
		public string TypeName
		{
			get
			{
				if (this.typeName != null)
				{
					return this.typeName;
				}
				return string.Empty;
			}
			set
			{
				this.typeName = value;
			}
		}

		/// <summary>Gets or sets the namespace of the XML type.</summary>
		/// <returns>The namespace of the XML type. The default is an empty string ("").</returns>
		// Token: 0x170005DB RID: 1499
		// (get) Token: 0x06001DC1 RID: 7617 RVA: 0x000A3DEA File Offset: 0x000A1FEA
		// (set) Token: 0x06001DC2 RID: 7618 RVA: 0x000A3DF2 File Offset: 0x000A1FF2
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		// Token: 0x040016AB RID: 5803
		private string ns;

		// Token: 0x040016AC RID: 5804
		private string typeName;

		// Token: 0x040016AD RID: 5805
		private bool includeInSchema = true;
	}
}
