using System;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize the class member as an XML attribute.</summary>
	// Token: 0x02000329 RID: 809
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlAttributeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class.</summary>
		// Token: 0x06001E7D RID: 7805 RVA: 0x0009F79F File Offset: 0x0009D99F
		public XmlAttributeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class and specifies the name of the generated XML attribute.</summary>
		/// <param name="attributeName">The name of the XML attribute that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates. </param>
		// Token: 0x06001E7E RID: 7806 RVA: 0x000A6C72 File Offset: 0x000A4E72
		public XmlAttributeAttribute(string attributeName)
		{
			this.attributeName = attributeName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> used to store the attribute. </param>
		// Token: 0x06001E7F RID: 7807 RVA: 0x000A6C81 File Offset: 0x000A4E81
		public XmlAttributeAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class.</summary>
		/// <param name="attributeName">The name of the XML attribute that is generated. </param>
		/// <param name="type">The <see cref="T:System.Type" /> used to store the attribute. </param>
		// Token: 0x06001E80 RID: 7808 RVA: 0x000A6C90 File Offset: 0x000A4E90
		public XmlAttributeAttribute(string attributeName, Type type)
		{
			this.attributeName = attributeName;
			this.type = type;
		}

		/// <summary>Gets or sets the complex type of the XML attribute.</summary>
		/// <returns>The type of the XML attribute.</returns>
		// Token: 0x17000622 RID: 1570
		// (get) Token: 0x06001E81 RID: 7809 RVA: 0x000A6CA6 File Offset: 0x000A4EA6
		// (set) Token: 0x06001E82 RID: 7810 RVA: 0x000A6CAE File Offset: 0x000A4EAE
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the name of the XML attribute.</summary>
		/// <returns>The name of the XML attribute. The default is the member name.</returns>
		// Token: 0x17000623 RID: 1571
		// (get) Token: 0x06001E83 RID: 7811 RVA: 0x000A6CB7 File Offset: 0x000A4EB7
		// (set) Token: 0x06001E84 RID: 7812 RVA: 0x000A6CCD File Offset: 0x000A4ECD
		public string AttributeName
		{
			get
			{
				if (this.attributeName != null)
				{
					return this.attributeName;
				}
				return string.Empty;
			}
			set
			{
				this.attributeName = value;
			}
		}

		/// <summary>Gets or sets the XML namespace of the XML attribute.</summary>
		/// <returns>The XML namespace of the XML attribute.</returns>
		// Token: 0x17000624 RID: 1572
		// (get) Token: 0x06001E85 RID: 7813 RVA: 0x000A6CD6 File Offset: 0x000A4ED6
		// (set) Token: 0x06001E86 RID: 7814 RVA: 0x000A6CDE File Offset: 0x000A4EDE
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the XSD data type of the XML attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XSD (XML Schema Document) data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema: DataTypes".</returns>
		// Token: 0x17000625 RID: 1573
		// (get) Token: 0x06001E87 RID: 7815 RVA: 0x000A6CE7 File Offset: 0x000A4EE7
		// (set) Token: 0x06001E88 RID: 7816 RVA: 0x000A6CFD File Offset: 0x000A4EFD
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the XML attribute name generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> is qualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is XmlForm.None.</returns>
		// Token: 0x17000626 RID: 1574
		// (get) Token: 0x06001E89 RID: 7817 RVA: 0x000A6D06 File Offset: 0x000A4F06
		// (set) Token: 0x06001E8A RID: 7818 RVA: 0x000A6D0E File Offset: 0x000A4F0E
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
			set
			{
				this.form = value;
			}
		}

		// Token: 0x0400170D RID: 5901
		private string attributeName;

		// Token: 0x0400170E RID: 5902
		private Type type;

		// Token: 0x0400170F RID: 5903
		private string ns;

		// Token: 0x04001710 RID: 5904
		private string dataType;

		// Token: 0x04001711 RID: 5905
		private XmlSchemaForm form;
	}
}
