using System;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a particular class member as an array of XML elements.</summary>
	// Token: 0x02000326 RID: 806
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = false)]
	public class XmlArrayAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlArrayAttribute" /> class.</summary>
		// Token: 0x06001E55 RID: 7765 RVA: 0x000A6AE8 File Offset: 0x000A4CE8
		public XmlArrayAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlArrayAttribute" /> class and specifies the XML element name generated in the XML document instance.</summary>
		/// <param name="elementName">The name of the XML element that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates. </param>
		// Token: 0x06001E56 RID: 7766 RVA: 0x000A6AF7 File Offset: 0x000A4CF7
		public XmlArrayAttribute(string elementName)
		{
			this.elementName = elementName;
		}

		/// <summary>Gets or sets the XML element name given to the serialized array.</summary>
		/// <returns>The XML element name of the serialized array. The default is the name of the member to which the <see cref="T:System.Xml.Serialization.XmlArrayAttribute" /> is assigned.</returns>
		// Token: 0x17000614 RID: 1556
		// (get) Token: 0x06001E57 RID: 7767 RVA: 0x000A6B0D File Offset: 0x000A4D0D
		// (set) Token: 0x06001E58 RID: 7768 RVA: 0x000A6B23 File Offset: 0x000A4D23
		public string ElementName
		{
			get
			{
				if (this.elementName != null)
				{
					return this.elementName;
				}
				return string.Empty;
			}
			set
			{
				this.elementName = value;
			}
		}

		/// <summary>Gets or sets the namespace of the XML element.</summary>
		/// <returns>The namespace of the XML element.</returns>
		// Token: 0x17000615 RID: 1557
		// (get) Token: 0x06001E59 RID: 7769 RVA: 0x000A6B2C File Offset: 0x000A4D2C
		// (set) Token: 0x06001E5A RID: 7770 RVA: 0x000A6B34 File Offset: 0x000A4D34
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a member as an empty XML tag with the xsi:nil attribute set to true.</summary>
		/// <returns>true if the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates the xsi:nil attribute; otherwise, false.</returns>
		// Token: 0x17000616 RID: 1558
		// (get) Token: 0x06001E5B RID: 7771 RVA: 0x000A6B3D File Offset: 0x000A4D3D
		// (set) Token: 0x06001E5C RID: 7772 RVA: 0x000A6B45 File Offset: 0x000A4D45
		public bool IsNullable
		{
			get
			{
				return this.nullable;
			}
			set
			{
				this.nullable = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the XML element name generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> is qualified or unqualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is XmlSchemaForm.None.</returns>
		// Token: 0x17000617 RID: 1559
		// (get) Token: 0x06001E5D RID: 7773 RVA: 0x000A6B4E File Offset: 0x000A4D4E
		// (set) Token: 0x06001E5E RID: 7774 RVA: 0x000A6B56 File Offset: 0x000A4D56
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
			set
			{
				this.form = value;
			}
		}

		/// <summary>Gets or sets the explicit order in which the elements are serialized or deserialized.</summary>
		/// <returns>The order of the code generation.</returns>
		// Token: 0x17000618 RID: 1560
		// (get) Token: 0x06001E5F RID: 7775 RVA: 0x000A6B5F File Offset: 0x000A4D5F
		// (set) Token: 0x06001E60 RID: 7776 RVA: 0x000A6B67 File Offset: 0x000A4D67
		public int Order
		{
			get
			{
				return this.order;
			}
			set
			{
				if (value < 0)
				{
					throw new ArgumentException(Res.GetString("Negative values are prohibited."), "Order");
				}
				this.order = value;
			}
		}

		// Token: 0x04001700 RID: 5888
		private string elementName;

		// Token: 0x04001701 RID: 5889
		private string ns;

		// Token: 0x04001702 RID: 5890
		private bool nullable;

		// Token: 0x04001703 RID: 5891
		private XmlSchemaForm form;

		// Token: 0x04001704 RID: 5892
		private int order = -1;
	}
}
