using System;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Indicates that a public field or property represents an XML element when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes or deserializes the object that contains it.</summary>
	// Token: 0x02000330 RID: 816
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = true)]
	public class XmlElementAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class.</summary>
		// Token: 0x06001F3F RID: 7999 RVA: 0x000A9B3C File Offset: 0x000A7D3C
		public XmlElementAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class and specifies the name of the XML element.</summary>
		/// <param name="elementName">The XML element name of the serialized member. </param>
		// Token: 0x06001F40 RID: 8000 RVA: 0x000A9B4B File Offset: 0x000A7D4B
		public XmlElementAttribute(string elementName)
		{
			this.elementName = elementName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class and specifies a type for the member to which the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> is applied. This type is used by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> when serializing or deserializing object that contains it.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> of an object derived from the member's type. </param>
		// Token: 0x06001F41 RID: 8001 RVA: 0x000A9B61 File Offset: 0x000A7D61
		public XmlElementAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> and specifies the name of the XML element and a derived type for the member to which the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> is applied. This member type is used when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes the object that contains it.</summary>
		/// <param name="elementName">The XML element name of the serialized member. </param>
		/// <param name="type">The <see cref="T:System.Type" /> of an object derived from the member's type. </param>
		// Token: 0x06001F42 RID: 8002 RVA: 0x000A9B77 File Offset: 0x000A7D77
		public XmlElementAttribute(string elementName, Type type)
		{
			this.elementName = elementName;
			this.type = type;
		}

		/// <summary>Gets or sets the object type used to represent the XML element.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x1700065C RID: 1628
		// (get) Token: 0x06001F43 RID: 8003 RVA: 0x000A9B94 File Offset: 0x000A7D94
		// (set) Token: 0x06001F44 RID: 8004 RVA: 0x000A9B9C File Offset: 0x000A7D9C
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the name of the generated XML element.</summary>
		/// <returns>The name of the generated XML element. The default is the member identifier.</returns>
		// Token: 0x1700065D RID: 1629
		// (get) Token: 0x06001F45 RID: 8005 RVA: 0x000A9BA5 File Offset: 0x000A7DA5
		// (set) Token: 0x06001F46 RID: 8006 RVA: 0x000A9BBB File Offset: 0x000A7DBB
		public string ElementName
		{
			get
			{
				if (this.elementName != null)
				{
					return this.elementName;
				}
				return string.Empty;
			}
			set
			{
				this.elementName = value;
			}
		}

		/// <summary>Gets or sets the namespace assigned to the XML element that results when the class is serialized.</summary>
		/// <returns>The namespace of the XML element.</returns>
		// Token: 0x1700065E RID: 1630
		// (get) Token: 0x06001F47 RID: 8007 RVA: 0x000A9BC4 File Offset: 0x000A7DC4
		// (set) Token: 0x06001F48 RID: 8008 RVA: 0x000A9BCC File Offset: 0x000A7DCC
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition (XSD) data type of the XML element generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the.NET data type. </exception>
		// Token: 0x1700065F RID: 1631
		// (get) Token: 0x06001F49 RID: 8009 RVA: 0x000A9BD5 File Offset: 0x000A7DD5
		// (set) Token: 0x06001F4A RID: 8010 RVA: 0x000A9BEB File Offset: 0x000A7DEB
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a member that is set to null as an empty tag with the xsi:nil attribute set to true.</summary>
		/// <returns>true if the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates the xsi:nil attribute; otherwise, false.</returns>
		// Token: 0x17000660 RID: 1632
		// (get) Token: 0x06001F4B RID: 8011 RVA: 0x000A9BF4 File Offset: 0x000A7DF4
		// (set) Token: 0x06001F4C RID: 8012 RVA: 0x000A9BFC File Offset: 0x000A7DFC
		public bool IsNullable
		{
			get
			{
				return this.nullable;
			}
			set
			{
				this.nullable = value;
				this.nullableSpecified = true;
			}
		}

		// Token: 0x17000661 RID: 1633
		// (get) Token: 0x06001F4D RID: 8013 RVA: 0x000A9C0C File Offset: 0x000A7E0C
		internal bool IsNullableSpecified
		{
			get
			{
				return this.nullableSpecified;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the element is qualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is <see cref="F:System.Xml.Schema.XmlSchemaForm.None" />.</returns>
		// Token: 0x17000662 RID: 1634
		// (get) Token: 0x06001F4E RID: 8014 RVA: 0x000A9C14 File Offset: 0x000A7E14
		// (set) Token: 0x06001F4F RID: 8015 RVA: 0x000A9C1C File Offset: 0x000A7E1C
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
			set
			{
				this.form = value;
			}
		}

		/// <summary>Gets or sets the explicit order in which the elements are serialized or deserialized.</summary>
		/// <returns>The order of the code generation.</returns>
		// Token: 0x17000663 RID: 1635
		// (get) Token: 0x06001F50 RID: 8016 RVA: 0x000A9C25 File Offset: 0x000A7E25
		// (set) Token: 0x06001F51 RID: 8017 RVA: 0x000A9C2D File Offset: 0x000A7E2D
		public int Order
		{
			get
			{
				return this.order;
			}
			set
			{
				if (value < 0)
				{
					throw new ArgumentException(Res.GetString("Negative values are prohibited."), "Order");
				}
				this.order = value;
			}
		}

		// Token: 0x04001733 RID: 5939
		private string elementName;

		// Token: 0x04001734 RID: 5940
		private Type type;

		// Token: 0x04001735 RID: 5941
		private string ns;

		// Token: 0x04001736 RID: 5942
		private string dataType;

		// Token: 0x04001737 RID: 5943
		private bool nullable;

		// Token: 0x04001738 RID: 5944
		private bool nullableSpecified;

		// Token: 0x04001739 RID: 5945
		private XmlSchemaForm form;

		// Token: 0x0400173A RID: 5946
		private int order = -1;
	}
}
