using System;

namespace System.Xml.Serialization
{
	/// <summary>Signifies that the code was generated by the serialization infrastructure and can be reused for increased performance, when this attribute is applied to an assembly.</summary>
	// Token: 0x02000367 RID: 871
	[AttributeUsage(AttributeTargets.Assembly)]
	public sealed class XmlSerializerVersionAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class. </summary>
		// Token: 0x060023A6 RID: 9126 RVA: 0x0009F79F File Offset: 0x0009D99F
		public XmlSerializerVersionAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class for the specified type.</summary>
		/// <param name="type">The type that is being serialized.</param>
		// Token: 0x060023A7 RID: 9127 RVA: 0x000DC0AC File Offset: 0x000DA2AC
		public XmlSerializerVersionAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Gets or sets the identity of the parent assembly.</summary>
		/// <returns>The version of the parent assembly.</returns>
		// Token: 0x170006F6 RID: 1782
		// (get) Token: 0x060023A8 RID: 9128 RVA: 0x000DC0BB File Offset: 0x000DA2BB
		// (set) Token: 0x060023A9 RID: 9129 RVA: 0x000DC0C3 File Offset: 0x000DA2C3
		public string ParentAssemblyId
		{
			get
			{
				return this.mvid;
			}
			set
			{
				this.mvid = value;
			}
		}

		/// <summary>Gets or sets the assembly's version number.</summary>
		/// <returns>The version of the assembly.</returns>
		// Token: 0x170006F7 RID: 1783
		// (get) Token: 0x060023AA RID: 9130 RVA: 0x000DC0CC File Offset: 0x000DA2CC
		// (set) Token: 0x060023AB RID: 9131 RVA: 0x000DC0D4 File Offset: 0x000DA2D4
		public string Version
		{
			get
			{
				return this.serializerVersion;
			}
			set
			{
				this.serializerVersion = value;
			}
		}

		/// <summary>Gets or sets the common language runtime (CLR) namespace of the assembly.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the common language runtime (CLR) namespace of the assembly.</returns>
		// Token: 0x170006F8 RID: 1784
		// (get) Token: 0x060023AC RID: 9132 RVA: 0x000DC0DD File Offset: 0x000DA2DD
		// (set) Token: 0x060023AD RID: 9133 RVA: 0x000DC0E5 File Offset: 0x000DA2E5
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the type that the serializer operates on.</summary>
		/// <returns>The <see cref="T:System.Type" /> to be serialized.</returns>
		// Token: 0x170006F9 RID: 1785
		// (get) Token: 0x060023AE RID: 9134 RVA: 0x000DC0EE File Offset: 0x000DA2EE
		// (set) Token: 0x060023AF RID: 9135 RVA: 0x000DC0F6 File Offset: 0x000DA2F6
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		// Token: 0x04001869 RID: 6249
		private string mvid;

		// Token: 0x0400186A RID: 6250
		private string serializerVersion;

		// Token: 0x0400186B RID: 6251
		private string ns;

		// Token: 0x0400186C RID: 6252
		private Type type;
	}
}
