using System;

namespace System.Xml.Serialization
{
	/// <summary>Indicates to the <see cref="T:System.Xml.Serialization.XmlSerializer" /> that the member must be treated as XML text when the class that contains it is serialized or deserialized.</summary>
	// Token: 0x02000368 RID: 872
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlTextAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlTextAttribute" /> class.</summary>
		// Token: 0x060023B0 RID: 9136 RVA: 0x0009F79F File Offset: 0x0009D99F
		public XmlTextAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlTextAttribute" /> class.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> of the member to be serialized. </param>
		// Token: 0x060023B1 RID: 9137 RVA: 0x000DC0FF File Offset: 0x000DA2FF
		public XmlTextAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Gets or sets the type of the member.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x170006FA RID: 1786
		// (get) Token: 0x060023B2 RID: 9138 RVA: 0x000DC10E File Offset: 0x000DA30E
		// (set) Token: 0x060023B3 RID: 9139 RVA: 0x000DC116 File Offset: 0x000DA316
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition language (XSD) data type of the text generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema (XSD) data type, as defined by the World Wide Web Consortium (www.w3.org) document "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the .NET data type. </exception>
		/// <exception cref="T:System.InvalidOperationException">The XML Schema data type you have specified is invalid for the property and cannot be converted to the member type. </exception>
		// Token: 0x170006FB RID: 1787
		// (get) Token: 0x060023B4 RID: 9140 RVA: 0x000DC11F File Offset: 0x000DA31F
		// (set) Token: 0x060023B5 RID: 9141 RVA: 0x000DC135 File Offset: 0x000DA335
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		// Token: 0x0400186D RID: 6253
		private Type type;

		// Token: 0x0400186E RID: 6254
		private string dataType;
	}
}
