using System;
using System.Collections;
using System.Collections.Generic;

namespace System.Data.SqlClient
{
	/// <summary>Collects all errors generated by the .NET Framework Data Provider for SQL Server. This class cannot be inherited. </summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020001C0 RID: 448
	[Serializable]
	public sealed class SqlErrorCollection : ICollection, IEnumerable
	{
		// Token: 0x060014D0 RID: 5328 RVA: 0x00069A77 File Offset: 0x00067C77
		internal SqlErrorCollection()
		{
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection into an <see cref="T:System.Array" />, starting at the specified index.</summary>
		/// <param name="array">The <see cref="T:System.Array" /> to copy elements into. </param>
		/// <param name="index">The index from which to start copying into the <paramref name="array" /> parameter. </param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection is greater than the <see cref="P:System.Array.Length" /> of the <see cref="T:System.Array" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014D1 RID: 5329 RVA: 0x00069A8A File Offset: 0x00067C8A
		public void CopyTo(Array array, int index)
		{
			((ICollection)this._errors).CopyTo(array, index);
		}

		/// <summary>Copies the elements of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection into a <see cref="T:System.Data.SqlClient.SqlErrorCollection" />, starting at the specified index.</summary>
		/// <param name="array">The <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> to copy the elements into.</param>
		/// <param name="index">The index from which to start copying into the <paramref name="array" /> parameter.</param>
		/// <exception cref="T:System.ArgumentException">The sum of <paramref name="index" /> and the number of elements in the <see cref="T:System.Data.SqlClient.SqlErrorCollection" /> collection is greater than the length of the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />. </exception>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="array" /> is null. </exception>
		/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="index" /> is not valid for <paramref name="array" />. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014D2 RID: 5330 RVA: 0x00069A99 File Offset: 0x00067C99
		public void CopyTo(SqlError[] array, int index)
		{
			this._errors.CopyTo(array, index);
		}

		/// <summary>Gets the number of errors in the collection.</summary>
		/// <returns>The total number of errors in the collection.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DC RID: 988
		// (get) Token: 0x060014D3 RID: 5331 RVA: 0x00069AA8 File Offset: 0x00067CA8
		public int Count
		{
			get
			{
				return this._errors.Count;
			}
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.SyncRoot" />.</summary>
		/// <returns>An object that can be used to synchronize access to the <see cref="T:System.Collections.ICollection" />.</returns>
		// Token: 0x170003DD RID: 989
		// (get) Token: 0x060014D4 RID: 5332 RVA: 0x00005D82 File Offset: 0x00003F82
		object ICollection.SyncRoot
		{
			get
			{
				return this;
			}
		}

		/// <summary>For a description of this member, see <see cref="P:System.Collections.ICollection.IsSynchronized" />.</summary>
		/// <returns>true if access to the <see cref="T:System.Collections.ICollection" /> is synchronized (thread safe); otherwise, false.</returns>
		// Token: 0x170003DE RID: 990
		// (get) Token: 0x060014D5 RID: 5333 RVA: 0x000061D5 File Offset: 0x000043D5
		bool ICollection.IsSynchronized
		{
			get
			{
				return false;
			}
		}

		/// <summary>Gets the error at the specified index.</summary>
		/// <returns>A <see cref="T:System.Data.SqlClient.SqlError" /> that contains the error at the specified index.</returns>
		/// <param name="index">The zero-based index of the error to retrieve. </param>
		/// <exception cref="T:System.IndexOutOfRangeException">Index parameter is outside array bounds. </exception>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003DF RID: 991
		public SqlError this[int index]
		{
			get
			{
				return (SqlError)this._errors[index];
			}
		}

		/// <summary>Returns an enumerator that iterates through the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />.</summary>
		/// <returns>An <see cref="T:System.Collections.IEnumerator" /> for the <see cref="T:System.Data.SqlClient.SqlErrorCollection" />.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014D7 RID: 5335 RVA: 0x00069AC8 File Offset: 0x00067CC8
		public IEnumerator GetEnumerator()
		{
			return this._errors.GetEnumerator();
		}

		// Token: 0x060014D8 RID: 5336 RVA: 0x00069ADA File Offset: 0x00067CDA
		internal void Add(SqlError error)
		{
			this._errors.Add(error);
		}

		// Token: 0x04000E23 RID: 3619
		private readonly List<object> _errors = new List<object>();
	}
}
