using System;
using System.Collections;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;
using System.Runtime.Serialization;
using System.Security.Permissions;
using System.Text;
using Unity;

namespace System.Data.SqlClient
{
	/// <summary>The exception that is thrown when SQL Server returns a warning or error. This class cannot be inherited.</summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020001C1 RID: 449
	[Serializable]
	public sealed class SqlException : DbException
	{
		// Token: 0x060014D9 RID: 5337 RVA: 0x00069AE8 File Offset: 0x00067CE8
		private SqlException(string message, SqlErrorCollection errorCollection, Exception innerException, Guid conId)
		{
			this._clientConnectionId = Guid.Empty;
			base..ctor(message, innerException);
			base.HResult = -2146232060;
			this._errors = errorCollection;
			this._clientConnectionId = conId;
		}

		/// <summary>Sets the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> with information about the exception.</summary>
		/// <param name="si">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown. </param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="si" /> parameter is a null reference (Nothing in Visual Basic).</exception>
		/// <filterpriority>2</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
		///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="ControlEvidence, SerializationFormatter" />
		/// </PermissionSet>
		// Token: 0x060014DA RID: 5338 RVA: 0x000107C2 File Offset: 0x0000E9C2
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.SerializationFormatter)]
		public override void GetObjectData(SerializationInfo si, StreamingContext context)
		{
			base.GetObjectData(si, context);
		}

		/// <summary>Gets a collection of one or more <see cref="T:System.Data.SqlClient.SqlError" /> objects that give detailed information about exceptions generated by the .NET Framework Data Provider for SQL Server.</summary>
		/// <returns>The collected instances of the <see cref="T:System.Data.SqlClient.SqlError" /> class.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E0 RID: 992
		// (get) Token: 0x060014DB RID: 5339 RVA: 0x00069B17 File Offset: 0x00067D17
		public SqlErrorCollection Errors
		{
			get
			{
				if (this._errors == null)
				{
					this._errors = new SqlErrorCollection();
				}
				return this._errors;
			}
		}

		/// <summary>Represents the client connection ID. For more information, see Data Tracing in ADO.NET.</summary>
		/// <returns>Returns the client connection ID.</returns>
		// Token: 0x170003E1 RID: 993
		// (get) Token: 0x060014DC RID: 5340 RVA: 0x00069B32 File Offset: 0x00067D32
		public Guid ClientConnectionId
		{
			get
			{
				return this._clientConnectionId;
			}
		}

		/// <summary>Gets the severity level of the error returned from the .NET Framework Data Provider for SQL Server.</summary>
		/// <returns>A value from 1 to 25 that indicates the severity level of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E2 RID: 994
		// (get) Token: 0x060014DD RID: 5341 RVA: 0x00069B3A File Offset: 0x00067D3A
		public byte Class
		{
			get
			{
				return this.Errors[0].Class;
			}
		}

		/// <summary>Gets the line number within the Transact-SQL command batch or stored procedure that generated the error.</summary>
		/// <returns>The line number within the Transact-SQL command batch or stored procedure that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E3 RID: 995
		// (get) Token: 0x060014DE RID: 5342 RVA: 0x00069B4D File Offset: 0x00067D4D
		public int LineNumber
		{
			get
			{
				return this.Errors[0].LineNumber;
			}
		}

		/// <summary>Gets a number that identifies the type of error.</summary>
		/// <returns>The number that identifies the type of error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E4 RID: 996
		// (get) Token: 0x060014DF RID: 5343 RVA: 0x00069B60 File Offset: 0x00067D60
		public int Number
		{
			get
			{
				return this.Errors[0].Number;
			}
		}

		/// <summary>Gets the name of the stored procedure or remote procedure call (RPC) that generated the error.</summary>
		/// <returns>The name of the stored procedure or RPC.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E5 RID: 997
		// (get) Token: 0x060014E0 RID: 5344 RVA: 0x00069B73 File Offset: 0x00067D73
		public string Procedure
		{
			get
			{
				return this.Errors[0].Procedure;
			}
		}

		/// <summary>Gets the name of the computer that is running an instance of SQL Server that generated the error.</summary>
		/// <returns>The name of the computer running an instance of SQL Server.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E6 RID: 998
		// (get) Token: 0x060014E1 RID: 5345 RVA: 0x00069B86 File Offset: 0x00067D86
		public string Server
		{
			get
			{
				return this.Errors[0].Server;
			}
		}

		/// <summary>Gets a numeric error code from SQL Server that represents an error, warning or "no data found" message. For more information about how to decode these values, see SQL Server Books Online.</summary>
		/// <returns>The number representing the error code.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E7 RID: 999
		// (get) Token: 0x060014E2 RID: 5346 RVA: 0x00069B99 File Offset: 0x00067D99
		public byte State
		{
			get
			{
				return this.Errors[0].State;
			}
		}

		/// <summary>Gets the name of the provider that generated the error.</summary>
		/// <returns>The name of the provider that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003E8 RID: 1000
		// (get) Token: 0x060014E3 RID: 5347 RVA: 0x00069BAC File Offset: 0x00067DAC
		public override string Source
		{
			get
			{
				return this.Errors[0].Source;
			}
		}

		/// <summary>Returns a string that represents the current <see cref="T:System.Data.SqlClient.SqlException" /> object, and includes the client connection ID (for more information, see <see cref="P:System.Data.SqlClient.SqlException.ClientConnectionId" />).</summary>
		/// <returns>A string that represents the current <see cref="T:System.Data.SqlClient.SqlException" /> object.<see cref="T:System.String" />.</returns>
		// Token: 0x060014E4 RID: 5348 RVA: 0x00069BC0 File Offset: 0x00067DC0
		public override string ToString()
		{
			StringBuilder stringBuilder = new StringBuilder(base.ToString());
			stringBuilder.AppendLine();
			stringBuilder.AppendFormat(SQLMessage.ExClientConnectionId(), this._clientConnectionId);
			if (this.Number != 0)
			{
				stringBuilder.AppendLine();
				stringBuilder.AppendFormat(SQLMessage.ExErrorNumberStateClass(), this.Number, this.State, this.Class);
			}
			if (this.Data.Contains("OriginalClientConnectionId"))
			{
				stringBuilder.AppendLine();
				stringBuilder.AppendFormat(SQLMessage.ExOriginalClientConnectionId(), this.Data["OriginalClientConnectionId"]);
			}
			if (this.Data.Contains("RoutingDestination"))
			{
				stringBuilder.AppendLine();
				stringBuilder.AppendFormat(SQLMessage.ExRoutingDestination(), this.Data["RoutingDestination"]);
			}
			return stringBuilder.ToString();
		}

		// Token: 0x060014E5 RID: 5349 RVA: 0x00069CA3 File Offset: 0x00067EA3
		internal static SqlException CreateException(SqlErrorCollection errorCollection, string serverVersion)
		{
			return SqlException.CreateException(errorCollection, serverVersion, Guid.Empty, null);
		}

		// Token: 0x060014E6 RID: 5350 RVA: 0x00069CB4 File Offset: 0x00067EB4
		internal static SqlException CreateException(SqlErrorCollection errorCollection, string serverVersion, SqlInternalConnectionTds internalConnection, Exception innerException = null)
		{
			Guid guid = ((internalConnection == null) ? Guid.Empty : internalConnection._clientConnectionId);
			SqlException ex = SqlException.CreateException(errorCollection, serverVersion, guid, innerException);
			if (internalConnection != null)
			{
				if (internalConnection.OriginalClientConnectionId != Guid.Empty && internalConnection.OriginalClientConnectionId != internalConnection.ClientConnectionId)
				{
					ex.Data.Add("OriginalClientConnectionId", internalConnection.OriginalClientConnectionId);
				}
				if (!string.IsNullOrEmpty(internalConnection.RoutingDestination))
				{
					ex.Data.Add("RoutingDestination", internalConnection.RoutingDestination);
				}
			}
			return ex;
		}

		// Token: 0x060014E7 RID: 5351 RVA: 0x00069D44 File Offset: 0x00067F44
		internal static SqlException CreateException(SqlErrorCollection errorCollection, string serverVersion, Guid conId, Exception innerException = null)
		{
			StringBuilder stringBuilder = new StringBuilder();
			for (int i = 0; i < errorCollection.Count; i++)
			{
				if (i > 0)
				{
					stringBuilder.Append(Environment.NewLine);
				}
				stringBuilder.Append(errorCollection[i].Message);
			}
			if (innerException == null && errorCollection[0].Win32ErrorCode != 0 && errorCollection[0].Win32ErrorCode != -1)
			{
				innerException = new Win32Exception(errorCollection[0].Win32ErrorCode);
			}
			SqlException ex = new SqlException(stringBuilder.ToString(), errorCollection, innerException, conId);
			ex.Data.Add("HelpLink.ProdName", "Microsoft SQL Server");
			if (!string.IsNullOrEmpty(serverVersion))
			{
				ex.Data.Add("HelpLink.ProdVer", serverVersion);
			}
			ex.Data.Add("HelpLink.EvtSrc", "MSSQLServer");
			ex.Data.Add("HelpLink.EvtID", errorCollection[0].Number.ToString(CultureInfo.InvariantCulture));
			ex.Data.Add("HelpLink.BaseHelpUrl", "http://go.microsoft.com/fwlink");
			ex.Data.Add("HelpLink.LinkId", "20476");
			return ex;
		}

		// Token: 0x060014E8 RID: 5352 RVA: 0x00069E64 File Offset: 0x00068064
		internal SqlException InternalClone()
		{
			SqlException ex = new SqlException(this.Message, this._errors, base.InnerException, this._clientConnectionId);
			if (this.Data != null)
			{
				foreach (object obj in this.Data)
				{
					DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
					ex.Data.Add(dictionaryEntry.Key, dictionaryEntry.Value);
				}
			}
			ex._doNotReconnect = this._doNotReconnect;
			return ex;
		}

		// Token: 0x170003E9 RID: 1001
		// (get) Token: 0x060014E9 RID: 5353 RVA: 0x00069F04 File Offset: 0x00068104
		public override string Message
		{
			get
			{
				if (this.Errors.Count == 0)
				{
					return base.Message;
				}
				StringBuilder stringBuilder = new StringBuilder();
				if (base.Message != "SQL Exception has occured.")
				{
					stringBuilder.Append(base.Message);
					stringBuilder.Append("\n");
				}
				for (int i = 0; i < this.Errors.Count - 1; i++)
				{
					stringBuilder.Append(this.Errors[i].Message);
					stringBuilder.Append("\n");
				}
				stringBuilder.Append(this.Errors[this.Errors.Count - 1].Message);
				return stringBuilder.ToString();
			}
		}

		// Token: 0x060014EA RID: 5354 RVA: 0x00010468 File Offset: 0x0000E668
		internal SqlException()
		{
			ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x04000E24 RID: 3620
		private const string OriginalClientConnectionIdKey = "OriginalClientConnectionId";

		// Token: 0x04000E25 RID: 3621
		private const string RoutingDestinationKey = "RoutingDestination";

		// Token: 0x04000E26 RID: 3622
		private const int SqlExceptionHResult = -2146232060;

		// Token: 0x04000E27 RID: 3623
		private SqlErrorCollection _errors;

		// Token: 0x04000E28 RID: 3624
		private Guid _clientConnectionId;

		// Token: 0x04000E29 RID: 3625
		internal bool _doNotReconnect;

		// Token: 0x04000E2A RID: 3626
		private const string DEF_MESSAGE = "SQL Exception has occured.";
	}
}
