using System;
using Unity;

namespace System.Data.SqlClient
{
	/// <summary>Collects information relevant to a warning or error returned by SQL Server.</summary>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020001BF RID: 447
	[Serializable]
	public sealed class SqlError
	{
		// Token: 0x060014C2 RID: 5314 RVA: 0x0006997C File Offset: 0x00067B7C
		internal SqlError(int infoNumber, byte errorState, byte errorClass, string server, string errorMessage, string procedure, int lineNumber, uint win32ErrorCode, Exception exception = null)
			: this(infoNumber, errorState, errorClass, server, errorMessage, procedure, lineNumber, exception)
		{
			this._win32ErrorCode = (int)win32ErrorCode;
		}

		// Token: 0x060014C3 RID: 5315 RVA: 0x000699A4 File Offset: 0x00067BA4
		internal SqlError(int infoNumber, byte errorState, byte errorClass, string server, string errorMessage, string procedure, int lineNumber, Exception exception = null)
		{
			this._source = "Core .Net SqlClient Data Provider";
			base..ctor();
			this._number = infoNumber;
			this._state = errorState;
			this._errorClass = errorClass;
			this._server = server;
			this._message = errorMessage;
			this._procedure = procedure;
			this._lineNumber = lineNumber;
			this._win32ErrorCode = 0;
			this._exception = exception;
		}

		/// <summary>Gets the complete text of the error message.</summary>
		/// <returns>The complete text of the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x060014C4 RID: 5316 RVA: 0x00069A06 File Offset: 0x00067C06
		public override string ToString()
		{
			return typeof(SqlError).ToString() + ": " + this._message;
		}

		/// <summary>Gets the name of the provider that generated the error.</summary>
		/// <returns>The name of the provider that generated the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D2 RID: 978
		// (get) Token: 0x060014C5 RID: 5317 RVA: 0x00069A27 File Offset: 0x00067C27
		public string Source
		{
			get
			{
				return this._source;
			}
		}

		/// <summary>Gets a number that identifies the type of error.</summary>
		/// <returns>The number that identifies the type of error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D3 RID: 979
		// (get) Token: 0x060014C6 RID: 5318 RVA: 0x00069A2F File Offset: 0x00067C2F
		public int Number
		{
			get
			{
				return this._number;
			}
		}

		/// <summary>Some error messages can be raised at multiple points in the code for the Database Engine. For example, an 1105 error can be raised for several different conditions. Each specific condition that raises an error assigns a unique state code.</summary>
		/// <returns>The state code.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D4 RID: 980
		// (get) Token: 0x060014C7 RID: 5319 RVA: 0x00069A37 File Offset: 0x00067C37
		public byte State
		{
			get
			{
				return this._state;
			}
		}

		/// <summary>Gets the severity level of the error returned from SQL Server.</summary>
		/// <returns>A value from 1 to 25 that indicates the severity level of the error. The default is 0.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D5 RID: 981
		// (get) Token: 0x060014C8 RID: 5320 RVA: 0x00069A3F File Offset: 0x00067C3F
		public byte Class
		{
			get
			{
				return this._errorClass;
			}
		}

		/// <summary>Gets the name of the instance of SQL Server that generated the error.</summary>
		/// <returns>The name of the instance of SQL Server.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D6 RID: 982
		// (get) Token: 0x060014C9 RID: 5321 RVA: 0x00069A47 File Offset: 0x00067C47
		public string Server
		{
			get
			{
				return this._server;
			}
		}

		/// <summary>Gets the text describing the error.</summary>
		/// <returns>The text describing the error.For more information on errors generated by SQL Server, see SQL Server Books Online.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D7 RID: 983
		// (get) Token: 0x060014CA RID: 5322 RVA: 0x00069A4F File Offset: 0x00067C4F
		public string Message
		{
			get
			{
				return this._message;
			}
		}

		/// <summary>Gets the name of the stored procedure or remote procedure call (RPC) that generated the error.</summary>
		/// <returns>The name of the stored procedure or RPC.For more information on errors generated by SQL Server, see SQL Server Books Online.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D8 RID: 984
		// (get) Token: 0x060014CB RID: 5323 RVA: 0x00069A57 File Offset: 0x00067C57
		public string Procedure
		{
			get
			{
				return this._procedure;
			}
		}

		/// <summary>Gets the line number within the Transact-SQL command batch or stored procedure that contains the error.</summary>
		/// <returns>The line number within the Transact-SQL command batch or stored procedure that contains the error.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x170003D9 RID: 985
		// (get) Token: 0x060014CC RID: 5324 RVA: 0x00069A5F File Offset: 0x00067C5F
		public int LineNumber
		{
			get
			{
				return this._lineNumber;
			}
		}

		// Token: 0x170003DA RID: 986
		// (get) Token: 0x060014CD RID: 5325 RVA: 0x00069A67 File Offset: 0x00067C67
		internal int Win32ErrorCode
		{
			get
			{
				return this._win32ErrorCode;
			}
		}

		// Token: 0x170003DB RID: 987
		// (get) Token: 0x060014CE RID: 5326 RVA: 0x00069A6F File Offset: 0x00067C6F
		internal Exception Exception
		{
			get
			{
				return this._exception;
			}
		}

		// Token: 0x060014CF RID: 5327 RVA: 0x00010468 File Offset: 0x0000E668
		internal SqlError()
		{
			ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x04000E19 RID: 3609
		private string _source;

		// Token: 0x04000E1A RID: 3610
		private int _number;

		// Token: 0x04000E1B RID: 3611
		private byte _state;

		// Token: 0x04000E1C RID: 3612
		private byte _errorClass;

		// Token: 0x04000E1D RID: 3613
		private string _server;

		// Token: 0x04000E1E RID: 3614
		private string _message;

		// Token: 0x04000E1F RID: 3615
		private string _procedure;

		// Token: 0x04000E20 RID: 3616
		private int _lineNumber;

		// Token: 0x04000E21 RID: 3617
		private int _win32ErrorCode;

		// Token: 0x04000E22 RID: 3618
		private Exception _exception;
	}
}
