using System;

namespace System.Data.SqlClient
{
	/// <summary>Represents the set of arguments passed to the notification event handler.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x020001CD RID: 461
	public class SqlNotificationEventArgs : EventArgs
	{
		/// <summary>Creates a new instance of the <see cref="T:System.Data.SqlClient.SqlNotificationEventArgs" /> object. </summary>
		/// <param name="type">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationType" /> value that indicates whether this notification is generated because of an actual change, or by the subscription. </param>
		/// <param name="info">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationInfo" /> value that indicates the reason for the notification event. This may occur because the data in the store actually changed, or the notification became invalid (for example, it timed out). </param>
		/// <param name="source">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationSource" /> value that indicates the source that generated the notification. </param>
		// Token: 0x0600157F RID: 5503 RVA: 0x0006C04D File Offset: 0x0006A24D
		public SqlNotificationEventArgs(SqlNotificationType type, SqlNotificationInfo info, SqlNotificationSource source)
		{
			this._info = info;
			this._source = source;
			this._type = type;
		}

		/// <summary>Gets a value that indicates whether this notification is generated because of an actual change, or by the subscription.</summary>
		/// <returns>A value indicating whether the notification was generated by a change or a subscription.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700041B RID: 1051
		// (get) Token: 0x06001580 RID: 5504 RVA: 0x0006C06A File Offset: 0x0006A26A
		public SqlNotificationType Type
		{
			get
			{
				return this._type;
			}
		}

		/// <summary>Gets a value that indicates the reason for the notification event, such as a row in the database being modified or a table being truncated.</summary>
		/// <returns>The notification event reason.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700041C RID: 1052
		// (get) Token: 0x06001581 RID: 5505 RVA: 0x0006C072 File Offset: 0x0006A272
		public SqlNotificationInfo Info
		{
			get
			{
				return this._info;
			}
		}

		/// <summary>Gets a value that indicates the source that generated the notification, such as a change to the query data or the database’s state.</summary>
		/// <returns>The source of the notification.</returns>
		/// <filterpriority>2</filterpriority>
		// Token: 0x1700041D RID: 1053
		// (get) Token: 0x06001582 RID: 5506 RVA: 0x0006C07A File Offset: 0x0006A27A
		public SqlNotificationSource Source
		{
			get
			{
				return this._source;
			}
		}

		// Token: 0x04000E73 RID: 3699
		private SqlNotificationType _type;

		// Token: 0x04000E74 RID: 3700
		private SqlNotificationInfo _info;

		// Token: 0x04000E75 RID: 3701
		private SqlNotificationSource _source;

		// Token: 0x04000E76 RID: 3702
		internal static SqlNotificationEventArgs s_notifyError = new SqlNotificationEventArgs(SqlNotificationType.Subscribe, SqlNotificationInfo.Error, SqlNotificationSource.Object);
	}
}
