using System;

namespace System.Runtime.CompilerServices
{
	/// <summary>Allows you to determine whether a method is a state machine method.</summary>
	// Token: 0x02000852 RID: 2130
	[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
	[Serializable]
	public class StateMachineAttribute : Attribute
	{
		/// <summary>Returns the type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</summary>
		/// <returns>Gets the type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</returns>
		// Token: 0x17000EAF RID: 3759
		// (get) Token: 0x06005407 RID: 21511 RVA: 0x00126EB8 File Offset: 0x001250B8
		// (set) Token: 0x06005408 RID: 21512 RVA: 0x00126EC0 File Offset: 0x001250C0
		public Type StateMachineType { get; private set; }

		/// <summary>Initializes a new instance of the <see cref="T:System.Runtime.CompilerServices.StateMachineAttribute" /> class.</summary>
		/// <param name="stateMachineType">The type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</param>
		// Token: 0x06005409 RID: 21513 RVA: 0x00126EC9 File Offset: 0x001250C9
		public StateMachineAttribute(Type stateMachineType)
		{
			this.StateMachineType = stateMachineType;
		}
	}
}
