using System;

namespace System.Web.Security
{
	// Token: 0x0200000C RID: 12
	internal interface IMembershipAdapter
	{
		// Token: 0x1700000F RID: 15
		// (get) Token: 0x06000027 RID: 39
		MembershipProviderCollection Providers { get; }

		// Token: 0x17000010 RID: 16
		// (get) Token: 0x06000028 RID: 40
		int UserIsOnlineTimeWindow { get; }

		// Token: 0x17000011 RID: 17
		// (get) Token: 0x06000029 RID: 41
		bool IsDecryptionKeyAutogenerated { get; }

		// Token: 0x17000012 RID: 18
		// (get) Token: 0x0600002A RID: 42
		bool UsingCustomEncryption { get; }

		// Token: 0x0600002B RID: 43
		byte[] EncryptOrDecryptData(bool encrypt, byte[] buffer, bool useLegacyMode);
	}
}
