using System;
using System.Collections;
using System.IO;
using System.Web.UI;
using System.Web.Util;

namespace System.Web.Configuration
{
	/// <summary>Provides access to detailed information about the capabilities of the client's browser.</summary>
	// Token: 0x020005A6 RID: 1446
	public class HttpCapabilitiesBase : IFilterResolutionService
	{
		/// <summary>Gets the value of the specified browser capability. In C#, this property is the indexer for the class.</summary>
		/// <returns>The browser capability with the specified key name.</returns>
		/// <param name="key">The name of the browser capability to retrieve.</param>
		// Token: 0x170012FB RID: 4859
		public virtual string this[string key]
		{
			get
			{
				return this.capabilities[key] as string;
			}
		}

		// Token: 0x06003D70 RID: 15728 RVA: 0x000A3010 File Offset: 0x000A1210
		internal static string GetUserAgentForDetection(HttpRequest request)
		{
			string text = null;
			if (request.Context.CurrentHandler is Page)
			{
				text = ((Page)request.Context.CurrentHandler).ClientTarget;
			}
			if (string.IsNullOrEmpty(text))
			{
				text = request.ClientTarget;
				if (string.IsNullOrEmpty(text))
				{
					text = request.UserAgent;
				}
			}
			return text;
		}

		// Token: 0x06003D71 RID: 15729 RVA: 0x000A3066 File Offset: 0x000A1266
		private static HttpBrowserCapabilities GetHttpBrowserCapabilitiesFromBrowscapini(string ua)
		{
			return new HttpBrowserCapabilities
			{
				capabilities = CapabilitiesLoader.GetCapabilities(ua)
			};
		}

		/// <summary>Used internally to return an instance of <see cref="T:System.Web.Configuration.HttpCapabilitiesBase" /> representing the browser that generated the specified <see cref="T:System.Web.HttpRequest" />.</summary>
		/// <returns>An instance of <see cref="T:System.Web.Configuration.HttpCapabilitiesBase" /> representing the browser that generated the specified <see cref="T:System.Web.HttpRequest" />.</returns>
		/// <param name="configKey">The name of the configuration section that configures browser capabilities.</param>
		/// <param name="request">The <see cref="T:System.Web.HttpRequest" /> generated by the browser for which to return capabilities and which is usually the current <see cref="T:System.Web.HttpRequest" />.</param>
		// Token: 0x06003D72 RID: 15730 RVA: 0x000A307C File Offset: 0x000A127C
		public static HttpCapabilitiesBase GetConfigCapabilities(string configKey, HttpRequest request)
		{
			string userAgentForDetection = HttpCapabilitiesBase.GetUserAgentForDetection(request);
			HttpBrowserCapabilities httpBrowserCapabilities = HttpCapabilitiesBase.GetHttpBrowserCapabilitiesFromBrowscapini(userAgentForDetection);
			HttpCapabilitiesBase.GetConfigCapabilities_called = true;
			if (HttpApplicationFactory.AppBrowsersFiles.Length != 0)
			{
				httpBrowserCapabilities = HttpApplicationFactory.CapabilitiesProcessor.Process(request, httpBrowserCapabilities.Capabilities);
			}
			httpBrowserCapabilities.useragent = userAgentForDetection;
			httpBrowserCapabilities.Init();
			return httpBrowserCapabilities;
		}

		/// <summary>Used internally to initialize an internal set of values.</summary>
		// Token: 0x06003D73 RID: 15731 RVA: 0x0000393A File Offset: 0x00001B3A
		protected virtual void Init()
		{
		}

		/// <summary>Used internally to compare filters.</summary>
		/// <returns>1 if <paramref name="filter1" /> is a parent of <paramref name="filter2" />; -1 if <paramref name="filter2" /> is a parent of <paramref name="filter1" />; 0 if there is no parent-child relationship between <paramref name="filter1" /> and <paramref name="filter2" />.</returns>
		/// <param name="filter1">The first filter to compare.</param>
		/// <param name="filter2">The second filter to compare.</param>
		// Token: 0x06003D74 RID: 15732 RVA: 0x00003A1F File Offset: 0x00001C1F
		int IFilterResolutionService.CompareFilters(string filter1, string filter2)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used internally to evaluate a filter.</summary>
		/// <returns>true if the filter was successfully evaluated; otherwise, false.</returns>
		/// <param name="filterName">The filter to evaluate.</param>
		// Token: 0x06003D75 RID: 15733 RVA: 0x00003A1F File Offset: 0x00001C1F
		bool IFilterResolutionService.EvaluateFilter(string filterName)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used internally to add an entry to the internal collection of browsers for which capabilities are recognized.</summary>
		/// <param name="browserName">The name of the browser to add.</param>
		// Token: 0x06003D76 RID: 15734 RVA: 0x0000393A File Offset: 0x00001B3A
		public void AddBrowser(string browserName)
		{
		}

		/// <summary>Creates a new instance of the <see cref="T:System.Web.UI.HtmlTextWriter" /> to be used.</summary>
		/// <returns>A new instance of the <see cref="T:System.Web.UI.HtmlTextWriter" /> to be used.</returns>
		/// <param name="w">
		///   <see cref="T:System.IO.TextWriter" /> to be created.</param>
		/// <exception cref="T:System.Exception">The method failed to create an instance of <see cref="T:System.Web.UI.HtmlTextWriter" />.</exception>
		// Token: 0x06003D77 RID: 15735 RVA: 0x000A30C5 File Offset: 0x000A12C5
		public HtmlTextWriter CreateHtmlTextWriter(TextWriter w)
		{
			return (HtmlTextWriter)Activator.CreateInstance(this.TagWriter, new object[] { w });
		}

		/// <summary>Used internally to disable use of an optimized cache key.</summary>
		// Token: 0x06003D78 RID: 15736 RVA: 0x00003A1F File Offset: 0x00001C1F
		public void DisableOptimizedCacheKey()
		{
			throw new NotImplementedException();
		}

		/// <summary>Returns the collection of available control adapters.</summary>
		/// <returns>The collection of registered control adapters.</returns>
		// Token: 0x170012FC RID: 4860
		// (get) Token: 0x06003D79 RID: 15737 RVA: 0x000A30E1 File Offset: 0x000A12E1
		public IDictionary Adapters
		{
			get
			{
				if (!this.Get(2))
				{
					this.adapters = this.GetAdapters();
					this.Set(2);
				}
				return this.adapters;
			}
		}

		// Token: 0x06003D7A RID: 15738 RVA: 0x000A3105 File Offset: 0x000A1305
		internal virtual IDictionary GetAdapters()
		{
			return new Hashtable();
		}

		/// <summary>Gets a value indicating whether the browser supports decks that contain multiple forms, such as separate cards.</summary>
		/// <returns>true if the browser supports decks that contain multiple forms; otherwise, false. The default is true.</returns>
		// Token: 0x170012FD RID: 4861
		// (get) Token: 0x06003D7B RID: 15739 RVA: 0x000A310C File Offset: 0x000A130C
		public virtual bool CanCombineFormsInDeck
		{
			get
			{
				if (!this.Get(8))
				{
					this.canCombineFormsInDeck = this.ReadBoolean("cancombineformsindeck");
					this.Set(8);
				}
				return this.canCombineFormsInDeck;
			}
		}

		/// <summary>Gets a value indicating whether the browser device is capable of initiating a voice call.</summary>
		/// <returns>true if the browser device is capable of initiating a voice call; otherwise, false. The default is false.</returns>
		// Token: 0x170012FE RID: 4862
		// (get) Token: 0x06003D7C RID: 15740 RVA: 0x000A3135 File Offset: 0x000A1335
		public virtual bool CanInitiateVoiceCall
		{
			get
			{
				if (!this.Get(9))
				{
					this.canInitiateVoiceCall = this.ReadBoolean("caninitiatevoicecall");
					this.Set(9);
				}
				return this.canInitiateVoiceCall;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports page content following WML &lt;select&gt; or &lt;input&gt; elements.</summary>
		/// <returns>true if the browser supports page content following HTML &lt;select&gt; or &lt;input&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x170012FF RID: 4863
		// (get) Token: 0x06003D7D RID: 15741 RVA: 0x000A3160 File Offset: 0x000A1360
		public virtual bool CanRenderAfterInputOrSelectElement
		{
			get
			{
				if (!this.Get(10))
				{
					this.canRenderAfterInputOrSelectElement = this.ReadBoolean("canrenderafterinputorselectelement");
					this.Set(10);
				}
				return this.canRenderAfterInputOrSelectElement;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports empty HTML &lt;select&gt; elements.</summary>
		/// <returns>true if the browser supports empty HTML &lt;select&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x17001300 RID: 4864
		// (get) Token: 0x06003D7E RID: 15742 RVA: 0x000A318B File Offset: 0x000A138B
		public virtual bool CanRenderEmptySelects
		{
			get
			{
				if (!this.Get(11))
				{
					this.canRenderEmptySelects = this.ReadBoolean("canrenderemptyselects");
					this.Set(11);
				}
				return this.canRenderEmptySelects;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports WML INPUT and SELECT elements together on the same card.</summary>
		/// <returns>true if the browser supports WML &lt;input&gt; and &lt;select&gt; elements together; otherwise, false. The default is false.</returns>
		// Token: 0x17001301 RID: 4865
		// (get) Token: 0x06003D7F RID: 15743 RVA: 0x000A31B6 File Offset: 0x000A13B6
		public virtual bool CanRenderInputAndSelectElementsTogether
		{
			get
			{
				if (!this.Get(12))
				{
					this.canRenderInputAndSelectElementsTogether = this.ReadBoolean("canrenderinputandselectelementstogether");
					this.Set(12);
				}
				return this.canRenderInputAndSelectElementsTogether;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports WML &lt;option&gt; elements that specify both onpick and value attributes.</summary>
		/// <returns>true if the browser supports WML &lt;option&gt; elements that specify both onpick and value attributes; otherwise, false. The default is true.</returns>
		// Token: 0x17001302 RID: 4866
		// (get) Token: 0x06003D80 RID: 15744 RVA: 0x000A31E1 File Offset: 0x000A13E1
		public virtual bool CanRenderMixedSelects
		{
			get
			{
				if (!this.Get(13))
				{
					this.canRenderMixedSelects = this.ReadBoolean("canrendermixedselects");
					this.Set(13);
				}
				return this.canRenderMixedSelects;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports WML &lt;onevent&gt; and &lt;prev&gt; elements that coexist within the same WML card.</summary>
		/// <returns>true if the browser supports WML &lt;onevent&gt; and &lt;prev&gt; elements that coexist within the same WML card; otherwise, false. The default is true.</returns>
		// Token: 0x17001303 RID: 4867
		// (get) Token: 0x06003D81 RID: 15745 RVA: 0x000A320C File Offset: 0x000A140C
		public virtual bool CanRenderOneventAndPrevElementsTogether
		{
			get
			{
				if (!this.Get(14))
				{
					this.canRenderOneventAndPrevElementsTogether = this.ReadBoolean("canrenderoneventandprevelementstogether");
					this.Set(14);
				}
				return this.canRenderOneventAndPrevElementsTogether;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports WML cards for postback.</summary>
		/// <returns>true if the browser supports WML cards for postback; otherwise, false. The default is true.</returns>
		// Token: 0x17001304 RID: 4868
		// (get) Token: 0x06003D82 RID: 15746 RVA: 0x000A3237 File Offset: 0x000A1437
		public virtual bool CanRenderPostBackCards
		{
			get
			{
				if (!this.Get(15))
				{
					this.canRenderPostBackCards = this.ReadBoolean("canrenderpostbackcards");
					this.Set(15);
				}
				return this.canRenderPostBackCards;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports WML &lt;setvar&gt; elements with a value attribute of 0.</summary>
		/// <returns>true if the browser supports WML &lt;setvar&gt; elements with a value attribute of 0; otherwise, false. The default is true.</returns>
		// Token: 0x17001305 RID: 4869
		// (get) Token: 0x06003D83 RID: 15747 RVA: 0x000A3262 File Offset: 0x000A1462
		public virtual bool CanRenderSetvarZeroWithMultiSelectionList
		{
			get
			{
				if (!this.Get(16))
				{
					this.canRenderSetvarZeroWithMultiSelectionList = this.ReadBoolean("canrendersetvarzerowithmultiselectionlist");
					this.Set(16);
				}
				return this.canRenderSetvarZeroWithMultiSelectionList;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports sending e-mail by using the HTML &lt;mailto&gt; element for displaying electronic addresses.</summary>
		/// <returns>true if the browser supports sending e-mail by using the HTML &lt;mailto&gt; element for displaying electronic addresses; otherwise, false. The default is true.</returns>
		// Token: 0x17001306 RID: 4870
		// (get) Token: 0x06003D84 RID: 15748 RVA: 0x000A328D File Offset: 0x000A148D
		public virtual bool CanSendMail
		{
			get
			{
				if (!this.Get(17))
				{
					this.canSendMail = this.ReadBoolean("cansendmail");
					this.Set(17);
				}
				return this.canSendMail;
			}
		}

		/// <summary>Used internally to get the defined capabilities of the browser.</summary>
		/// <returns>The defined capabilities of the browser.</returns>
		// Token: 0x17001307 RID: 4871
		// (get) Token: 0x06003D85 RID: 15749 RVA: 0x000A32B8 File Offset: 0x000A14B8
		// (set) Token: 0x06003D86 RID: 15750 RVA: 0x000A32C0 File Offset: 0x000A14C0
		public IDictionary Capabilities
		{
			get
			{
				return this.capabilities;
			}
			set
			{
				this.capabilities = new Hashtable(value.Keys.Count, StringComparer.OrdinalIgnoreCase);
				foreach (object obj in value.Keys)
				{
					if (!this.capabilities.Contains(obj))
					{
						this.capabilities.Add(obj, value[obj]);
					}
				}
			}
		}

		/// <summary>Returns the maximum number of Submit buttons that are allowed for a form.</summary>
		/// <returns>The maximum number of Submit buttons that are allowed for a form.</returns>
		// Token: 0x17001308 RID: 4872
		// (get) Token: 0x06003D87 RID: 15751 RVA: 0x000A334C File Offset: 0x000A154C
		public virtual int DefaultSubmitButtonLimit
		{
			get
			{
				if (!this.Get(22))
				{
					this.defaultSubmitButtonLimit = this.ReadInt32("defaultsubmitbuttonlimit");
					this.Set(22);
				}
				return this.defaultSubmitButtonLimit;
			}
		}

		/// <summary>Gets the major version number of the wireless gateway used to access the server, if known. </summary>
		/// <returns>The major version number of the wireless gateway used to access the server, if known. The default is 0.</returns>
		/// <exception cref="T:System.Web.HttpUnhandledException">The major version number of the wireless gateway cannot be parsed.</exception>
		// Token: 0x17001309 RID: 4873
		// (get) Token: 0x06003D88 RID: 15752 RVA: 0x000A3377 File Offset: 0x000A1577
		public virtual int GatewayMajorVersion
		{
			get
			{
				if (!this.Get(25))
				{
					this.gatewayMajorVersion = this.ReadInt32("gatewaymajorversion");
					this.Set(25);
				}
				return this.gatewayMajorVersion;
			}
		}

		/// <summary>Gets the minor version number of the wireless gateway used to access the server, if known. </summary>
		/// <returns>The minor version number of the wireless gateway used to access the server, if known. The default is 0.</returns>
		/// <exception cref="T:System.Web.HttpUnhandledException">The minor version number of the wireless gateway cannot be parsed.</exception>
		// Token: 0x1700130A RID: 4874
		// (get) Token: 0x06003D89 RID: 15753 RVA: 0x000A33A2 File Offset: 0x000A15A2
		public virtual double GatewayMinorVersion
		{
			get
			{
				if (!this.Get(26))
				{
					this.gatewayMinorVersion = this.ReadDouble("gatewayminorversion");
					this.Set(26);
				}
				return this.gatewayMinorVersion;
			}
		}

		/// <summary>Gets the version of the wireless gateway used to access the server, if known.</summary>
		/// <returns>The version number of the wireless gateway used to access the server, if known. The default is None.</returns>
		// Token: 0x1700130B RID: 4875
		// (get) Token: 0x06003D8A RID: 15754 RVA: 0x000A33CD File Offset: 0x000A15CD
		public virtual string GatewayVersion
		{
			get
			{
				if (!this.Get(27))
				{
					this.gatewayVersion = this.ReadString("gatewayversion");
					this.Set(27);
				}
				return this.gatewayVersion;
			}
		}

		/// <summary>Gets a value indicating whether the browser has a dedicated Back button.</summary>
		/// <returns>true if the browser has a dedicated Back button; otherwise, false. The default is true.</returns>
		// Token: 0x1700130C RID: 4876
		// (get) Token: 0x06003D8B RID: 15755 RVA: 0x000A33F8 File Offset: 0x000A15F8
		public virtual bool HasBackButton
		{
			get
			{
				if (!this.Get(28))
				{
					this.hasBackButton = this.ReadBoolean("hasbackbutton");
					this.Set(28);
				}
				return this.hasBackButton;
			}
		}

		/// <summary>Gets a value indicating whether the scrollbar of an HTML &lt;select multiple&gt; element with an align attribute value of right is obscured upon rendering.</summary>
		/// <returns>true if the scrollbar of an HTML &lt;select multiple&gt; element with an align attribute value of right is obscured upon rendering; otherwise, false. The default is false.</returns>
		// Token: 0x1700130D RID: 4877
		// (get) Token: 0x06003D8C RID: 15756 RVA: 0x000A3423 File Offset: 0x000A1623
		public virtual bool HidesRightAlignedMultiselectScrollbars
		{
			get
			{
				if (!this.Get(29))
				{
					this.hidesRightAlignedMultiselectScrollbars = this.ReadBoolean("hidesrightalignedmultiselectscrollbars");
					this.Set(29);
				}
				return this.hidesRightAlignedMultiselectScrollbars;
			}
		}

		/// <summary>Gets or sets the fully qualified class name of the <see cref="T:System.Web.UI.HtmlTextWriter" /> to use.</summary>
		/// <returns>The fully qualified class name of the <see cref="T:System.Web.UI.HtmlTextWriter" /> to use.</returns>
		// Token: 0x1700130E RID: 4878
		// (get) Token: 0x06003D8D RID: 15757 RVA: 0x000A344E File Offset: 0x000A164E
		// (set) Token: 0x06003D8E RID: 15758 RVA: 0x000A3479 File Offset: 0x000A1679
		public string HtmlTextWriter
		{
			get
			{
				if (!this.Get(30))
				{
					this.htmlTextWriter = this.ReadString("htmlTextWriter");
					this.Set(30);
				}
				return this.htmlTextWriter;
			}
			set
			{
				this.Set(30);
				this.htmlTextWriter = value;
			}
		}

		/// <summary>Gets the internal identifier of the browser as specified in the browser definition file.</summary>
		/// <returns>Internal identifier of the browser as specified in the browser definition file.</returns>
		// Token: 0x1700130F RID: 4879
		// (get) Token: 0x06003D8F RID: 15759 RVA: 0x000A348A File Offset: 0x000A168A
		public string Id
		{
			get
			{
				return this.Browser;
			}
		}

		/// <summary>Returns the type of input supported by browser.</summary>
		/// <returns>The type of input supported by browser. The default is telephoneKeypad.</returns>
		// Token: 0x17001310 RID: 4880
		// (get) Token: 0x06003D90 RID: 15760 RVA: 0x000A3492 File Offset: 0x000A1692
		public virtual string InputType
		{
			get
			{
				if (!this.Get(32))
				{
					this.inputType = this.ReadString("inputtype");
					this.Set(32);
				}
				return this.inputType;
			}
		}

		/// <summary>Gets a value indicating whether the browser has a color display.</summary>
		/// <returns>true if the browser has a color display; otherwise, false. The default is false.</returns>
		// Token: 0x17001311 RID: 4881
		// (get) Token: 0x06003D91 RID: 15761 RVA: 0x000A34BD File Offset: 0x000A16BD
		public virtual bool IsColor
		{
			get
			{
				if (!this.Get(33))
				{
					this.isColor = this.ReadBoolean("iscolor");
					this.Set(33);
				}
				return this.isColor;
			}
		}

		/// <summary>Gets a value indicating whether the browser is a recognized mobile device.</summary>
		/// <returns>true if the browser is a recognized mobile device; otherwise, false. The default is true.</returns>
		// Token: 0x17001312 RID: 4882
		// (get) Token: 0x06003D92 RID: 15762 RVA: 0x000A34E8 File Offset: 0x000A16E8
		public virtual bool IsMobileDevice
		{
			get
			{
				if (!this.Get(34))
				{
					this.isMobileDevice = this.ReadBoolean("ismobiledevice");
					this.Set(34);
				}
				return this.isMobileDevice;
			}
		}

		/// <summary>Gets the JScript version that the browser supports.</summary>
		/// <returns>The <see cref="T:System.Version" /> of JScript that the browser supports.</returns>
		// Token: 0x17001313 RID: 4883
		// (get) Token: 0x06003D93 RID: 15763 RVA: 0x000A3513 File Offset: 0x000A1713
		public Version JScriptVersion
		{
			get
			{
				if (!this.Get(37))
				{
					this.jscriptVersion = this.ReadVersion("jscriptversion");
					this.Set(37);
				}
				return this.jscriptVersion;
			}
		}

		/// <summary>Gets the maximum length in characters for the href attribute of an HTML &lt;a&gt; (anchor) element.</summary>
		/// <returns>The maximum length in characters for the href attribute of an HTML &lt;a&gt; (anchor) element.</returns>
		// Token: 0x17001314 RID: 4884
		// (get) Token: 0x06003D94 RID: 15764 RVA: 0x000A353E File Offset: 0x000A173E
		public virtual int MaximumHrefLength
		{
			get
			{
				if (!this.Get(39))
				{
					this.maximumHrefLength = this.ReadInt32("maximumhreflength");
					this.Set(39);
				}
				return this.maximumHrefLength;
			}
		}

		/// <summary>Gets the maximum length of the page, in bytes, which the browser can display. </summary>
		/// <returns>The maximum length of the page, in bytes, which the browser can display. The default is 2000.</returns>
		// Token: 0x17001315 RID: 4885
		// (get) Token: 0x06003D95 RID: 15765 RVA: 0x000A3569 File Offset: 0x000A1769
		public virtual int MaximumRenderedPageSize
		{
			get
			{
				if (!this.Get(40))
				{
					this.maximumRenderedPageSize = this.ReadInt32("maximumrenderedpagesize");
					this.Set(40);
				}
				return this.maximumRenderedPageSize;
			}
		}

		/// <summary>Returns the maximum length of the text that a soft-key label can display.</summary>
		/// <returns>The maximum length of the text that a soft-key label can display. The default is 5.</returns>
		// Token: 0x17001316 RID: 4886
		// (get) Token: 0x06003D96 RID: 15766 RVA: 0x000A3594 File Offset: 0x000A1794
		public virtual int MaximumSoftkeyLabelLength
		{
			get
			{
				if (!this.Get(41))
				{
					this.maximumSoftkeyLabelLength = this.ReadInt32("maximumsoftkeylabellength");
					this.Set(41);
				}
				return this.maximumSoftkeyLabelLength;
			}
		}

		/// <summary>Gets the minor (decimal) version number of the browser as a string.</summary>
		/// <returns>The minor version number of the browser.</returns>
		// Token: 0x17001317 RID: 4887
		// (get) Token: 0x06003D97 RID: 15767 RVA: 0x000A35BF File Offset: 0x000A17BF
		public string MinorVersionString
		{
			get
			{
				if (!this.Get(43))
				{
					this.minorVersionString = this.ReadString("minorversionstring");
					this.Set(43);
				}
				return this.minorVersionString;
			}
		}

		/// <summary>Returns the name of the manufacturer of a mobile device, if known.</summary>
		/// <returns>The name of the manufacturer of a mobile device, if known. The default is Unknown.</returns>
		// Token: 0x17001318 RID: 4888
		// (get) Token: 0x06003D98 RID: 15768 RVA: 0x000A35EA File Offset: 0x000A17EA
		public virtual string MobileDeviceManufacturer
		{
			get
			{
				if (!this.Get(44))
				{
					this.mobileDeviceManufacturer = this.ReadString("mobiledevicemanufacturer");
					this.Set(44);
				}
				return this.mobileDeviceManufacturer;
			}
		}

		/// <summary>Gets the model name of a mobile device, if known.</summary>
		/// <returns>The model name of a mobile device, if known. The default is Unknown.</returns>
		// Token: 0x17001319 RID: 4889
		// (get) Token: 0x06003D99 RID: 15769 RVA: 0x000A3615 File Offset: 0x000A1815
		public virtual string MobileDeviceModel
		{
			get
			{
				if (!this.Get(45))
				{
					this.mobileDeviceModel = this.ReadString("mobiledevicemodel");
					this.Set(45);
				}
				return this.mobileDeviceModel;
			}
		}

		/// <summary>Returns the number of soft keys on a mobile device.</summary>
		/// <returns>The number of soft keys supported on a mobile device. The default is 0.</returns>
		// Token: 0x1700131A RID: 4890
		// (get) Token: 0x06003D9A RID: 15770 RVA: 0x000A3640 File Offset: 0x000A1840
		public virtual int NumberOfSoftkeys
		{
			get
			{
				if (!this.Get(47))
				{
					this.numberOfSoftkeys = this.ReadInt32("numberofsoftkeys");
					this.Set(47);
				}
				return this.numberOfSoftkeys;
			}
		}

		/// <summary>Returns the MIME type of the type of image content typically preferred by the browser.</summary>
		/// <returns>The MIME type of the type of image content typically preferred by the browser. The default is image/gif.</returns>
		// Token: 0x1700131B RID: 4891
		// (get) Token: 0x06003D9B RID: 15771 RVA: 0x000A366B File Offset: 0x000A186B
		public virtual string PreferredImageMime
		{
			get
			{
				if (!this.Get(49))
				{
					this.preferredImageMime = this.ReadString("preferredimagemime");
					this.Set(49);
				}
				return this.preferredImageMime;
			}
		}

		/// <summary>Returns the MIME type of the type of content typically preferred by the browser.</summary>
		/// <returns>The MIME type of the type of content typically preferred by the browser. The default is text/html.</returns>
		// Token: 0x1700131C RID: 4892
		// (get) Token: 0x06003D9C RID: 15772 RVA: 0x000A3696 File Offset: 0x000A1896
		public virtual string PreferredRenderingMime
		{
			get
			{
				if (!this.Get(50))
				{
					this.preferredRenderingMime = this.ReadString("preferredrenderingmime");
					this.Set(50);
				}
				return this.preferredRenderingMime;
			}
		}

		/// <summary>Gets the general name for the type of content that the browser prefers.</summary>
		/// <returns>html32 or chtml10. The default is html32.</returns>
		// Token: 0x1700131D RID: 4893
		// (get) Token: 0x06003D9D RID: 15773 RVA: 0x000A36C1 File Offset: 0x000A18C1
		public virtual string PreferredRenderingType
		{
			get
			{
				if (!this.Get(51))
				{
					this.preferredRenderingType = this.ReadString("preferredrenderingtype");
					this.Set(51);
				}
				return this.preferredRenderingType;
			}
		}

		/// <summary>Gets the request encoding preferred by the browser.</summary>
		/// <returns>The request encoding preferred by the browser.</returns>
		// Token: 0x1700131E RID: 4894
		// (get) Token: 0x06003D9E RID: 15774 RVA: 0x000A36EC File Offset: 0x000A18EC
		public virtual string PreferredRequestEncoding
		{
			get
			{
				if (!this.Get(52))
				{
					this.preferredRequestEncoding = this.ReadString("preferredrequestencoding");
					this.Set(52);
				}
				return this.preferredRequestEncoding;
			}
		}

		/// <summary>Gets the response encoding preferred by the browser.</summary>
		/// <returns>The response encoding preferred by the browser.</returns>
		// Token: 0x1700131F RID: 4895
		// (get) Token: 0x06003D9F RID: 15775 RVA: 0x000A3717 File Offset: 0x000A1917
		public virtual string PreferredResponseEncoding
		{
			get
			{
				if (!this.Get(53))
				{
					this.preferredResponseEncoding = this.ReadString("preferredresponseencoding");
					this.Set(53);
				}
				return this.preferredResponseEncoding;
			}
		}

		/// <summary>Gets a value indicating whether the browser renders a line break before &lt;select&gt; or &lt;input&gt; elements.</summary>
		/// <returns>true if the browser renders a line break before &lt;select&gt; or &lt;input&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001320 RID: 4896
		// (get) Token: 0x06003DA0 RID: 15776 RVA: 0x000A3742 File Offset: 0x000A1942
		public virtual bool RendersBreakBeforeWmlSelectAndInput
		{
			get
			{
				if (!this.Get(54))
				{
					this.rendersBreakBeforeWmlSelectAndInput = this.ReadBoolean("rendersbreakbeforewmlselectandinput");
					this.Set(54);
				}
				return this.rendersBreakBeforeWmlSelectAndInput;
			}
		}

		/// <summary>Gets a value indicating whether the browser renders a line break after list-item elements.</summary>
		/// <returns>true if the browser renders a line break after list-item elements; otherwise, false. The default is true.</returns>
		// Token: 0x17001321 RID: 4897
		// (get) Token: 0x06003DA1 RID: 15777 RVA: 0x000A376D File Offset: 0x000A196D
		public virtual bool RendersBreaksAfterHtmlLists
		{
			get
			{
				if (!this.Get(55))
				{
					this.rendersBreaksAfterHtmlLists = this.ReadBoolean("rendersbreaksafterhtmllists");
					this.Set(55);
				}
				return this.rendersBreaksAfterHtmlLists;
			}
		}

		/// <summary>Gets a value indicating whether the browser renders a line break after a stand-alone HTML &lt;a&gt; (anchor) element.</summary>
		/// <returns>true if the browser renders a line break after a stand-alone HTML &lt;a&gt; (anchor) element; otherwise, false. The default is false.</returns>
		// Token: 0x17001322 RID: 4898
		// (get) Token: 0x06003DA2 RID: 15778 RVA: 0x000A3798 File Offset: 0x000A1998
		public virtual bool RendersBreaksAfterWmlAnchor
		{
			get
			{
				if (!this.Get(56))
				{
					this.rendersBreaksAfterWmlAnchor = this.ReadBoolean("rendersbreaksafterwmlanchor");
					this.Set(56);
				}
				return this.rendersBreaksAfterWmlAnchor;
			}
		}

		/// <summary>Gets a value indicating whether the browser renders a line break after an HTML &lt;input&gt; element.</summary>
		/// <returns>true if the browser renders a line break after an HTML &lt;input&gt; element; otherwise, false. The default is false.</returns>
		// Token: 0x17001323 RID: 4899
		// (get) Token: 0x06003DA3 RID: 15779 RVA: 0x000A37C3 File Offset: 0x000A19C3
		public virtual bool RendersBreaksAfterWmlInput
		{
			get
			{
				if (!this.Get(57))
				{
					this.rendersBreaksAfterWmlInput = this.ReadBoolean("rendersbreaksafterwmlinput");
					this.Set(57);
				}
				return this.rendersBreaksAfterWmlInput;
			}
		}

		/// <summary>Gets a value indicating whether the mobile-device browser renders a WML do-based form accept construct as an inline button rather than as a soft key.</summary>
		/// <returns>true if the mobile-device browser renders a WML do-based form-accept construct as an inline button; otherwise, false. The default is true.</returns>
		// Token: 0x17001324 RID: 4900
		// (get) Token: 0x06003DA4 RID: 15780 RVA: 0x000A37EE File Offset: 0x000A19EE
		public virtual bool RendersWmlDoAcceptsInline
		{
			get
			{
				if (!this.Get(58))
				{
					this.rendersWmlDoAcceptsInline = this.ReadBoolean("renderswmldoacceptsinline");
					this.Set(58);
				}
				return this.rendersWmlDoAcceptsInline;
			}
		}

		/// <summary>Gets a value indicating whether the browser renders WML &lt;select&gt; elements as menu cards, rather than as a combo box.</summary>
		/// <returns>true if the browser renders WML &lt;select&gt; elements as menu cards; otherwise, false. The default is false.</returns>
		// Token: 0x17001325 RID: 4901
		// (get) Token: 0x06003DA5 RID: 15781 RVA: 0x000A3819 File Offset: 0x000A1A19
		public virtual bool RendersWmlSelectsAsMenuCards
		{
			get
			{
				if (!this.Get(59))
				{
					this.rendersWmlSelectsAsMenuCards = this.ReadBoolean("renderswmlselectsasmenucards");
					this.Set(59);
				}
				return this.rendersWmlSelectsAsMenuCards;
			}
		}

		/// <summary>Used internally to produce a meta-tag required by some browsers.</summary>
		/// <returns>A meta-tag required by some browsers.</returns>
		// Token: 0x17001326 RID: 4902
		// (get) Token: 0x06003DA6 RID: 15782 RVA: 0x000A3844 File Offset: 0x000A1A44
		public virtual string RequiredMetaTagNameValue
		{
			get
			{
				if (!this.Get(60))
				{
					this.requiredMetaTagNameValue = this.ReadString("requiredmetatagnamevalue");
					this.Set(60);
				}
				return this.requiredMetaTagNameValue;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires colons in element attribute values to be substituted with a different character.</summary>
		/// <returns>true if the browser requires colons in element attribute values to be substituted with a different character; otherwise, false. The default is false.</returns>
		// Token: 0x17001327 RID: 4903
		// (get) Token: 0x06003DA7 RID: 15783 RVA: 0x000A386F File Offset: 0x000A1A6F
		public virtual bool RequiresAttributeColonSubstitution
		{
			get
			{
				if (!this.Get(61))
				{
					this.requiresAttributeColonSubstitution = this.ReadBoolean("requiresattributecolonsubstitution");
					this.Set(61);
				}
				return this.requiresAttributeColonSubstitution;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires an HTML &lt;meta&gt; element for which the content-type attribute is specified.</summary>
		/// <returns>true if the browser requires an HTML &lt;meta&gt; element for which the content-type attribute is specified; otherwise, false. The default is false.</returns>
		// Token: 0x17001328 RID: 4904
		// (get) Token: 0x06003DA8 RID: 15784 RVA: 0x000A389A File Offset: 0x000A1A9A
		public virtual bool RequiresContentTypeMetaTag
		{
			get
			{
				if (!this.Get(62))
				{
					this.requiresContentTypeMetaTag = this.ReadBoolean("requiresContentTypeMetaTag");
					this.Set(62);
				}
				return this.requiresContentTypeMetaTag;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires control state to be maintained in sessions.</summary>
		/// <returns>true if the browser requires control state to be maintained in sessions; otherwise, false. The default is false.</returns>
		// Token: 0x17001329 RID: 4905
		// (get) Token: 0x06003DA9 RID: 15785 RVA: 0x000A38C5 File Offset: 0x000A1AC5
		public bool RequiresControlStateInSession
		{
			get
			{
				if (!this.Get(63))
				{
					this.requiresControlStateInSession = this.ReadBoolean("requiresControlStateInSession");
					this.Set(63);
				}
				return this.requiresControlStateInSession;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires a double-byte character set.</summary>
		/// <returns>true if the browser requires a double-byte character set; otherwise, false. The default is false.</returns>
		// Token: 0x1700132A RID: 4906
		// (get) Token: 0x06003DAA RID: 15786 RVA: 0x000A38F0 File Offset: 0x000A1AF0
		public virtual bool RequiresDBCSCharacter
		{
			get
			{
				if (!this.Get(64))
				{
					this.requiresDBCSCharacter = this.ReadBoolean("requiresdbcscharacter");
					this.Set(64);
				}
				return this.requiresDBCSCharacter;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires nonstandard error messages.</summary>
		/// <returns>true if the browser requires nonstandard error messages; otherwise, false. The default is false.</returns>
		// Token: 0x1700132B RID: 4907
		// (get) Token: 0x06003DAB RID: 15787 RVA: 0x000A391B File Offset: 0x000A1B1B
		public virtual bool RequiresHtmlAdaptiveErrorReporting
		{
			get
			{
				if (!this.Get(65))
				{
					this.requiresHtmlAdaptiveErrorReporting = this.ReadBoolean("requireshtmladaptiveerrorreporting");
					this.Set(65);
				}
				return this.requiresHtmlAdaptiveErrorReporting;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires the first element in the body of a Web page to be an HTML &lt;br&gt; element.</summary>
		/// <returns>true if the browser requires the first element in the body of a Web page to be an HTML BR element; otherwise, false. The default is false.</returns>
		// Token: 0x1700132C RID: 4908
		// (get) Token: 0x06003DAC RID: 15788 RVA: 0x000A3946 File Offset: 0x000A1B46
		public virtual bool RequiresLeadingPageBreak
		{
			get
			{
				if (!this.Get(66))
				{
					this.requiresLeadingPageBreak = this.ReadBoolean("requiresleadingpagebreak");
					this.Set(66);
				}
				return this.requiresLeadingPageBreak;
			}
		}

		/// <summary>Gets a value indicating whether the browser does not support HTML &lt;br&gt; elements to format line breaks.</summary>
		/// <returns>true if the browser does not support HTML &lt;br&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x1700132D RID: 4909
		// (get) Token: 0x06003DAD RID: 15789 RVA: 0x000A3971 File Offset: 0x000A1B71
		public virtual bool RequiresNoBreakInFormatting
		{
			get
			{
				if (!this.Get(67))
				{
					this.requiresNoBreakInFormatting = this.ReadBoolean("requiresnobreakinformatting");
					this.Set(67);
				}
				return this.requiresNoBreakInFormatting;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires pages to contain a size-optimized form of markup language tags.</summary>
		/// <returns>true if the browser requires pages to contain a size-optimized form of markup language tags; otherwise, false. The default is false.</returns>
		// Token: 0x1700132E RID: 4910
		// (get) Token: 0x06003DAE RID: 15790 RVA: 0x000A399C File Offset: 0x000A1B9C
		public virtual bool RequiresOutputOptimization
		{
			get
			{
				if (!this.Get(68))
				{
					this.requiresOutputOptimization = this.ReadBoolean("requiresoutputoptimization");
					this.Set(68);
				}
				return this.requiresOutputOptimization;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports phone dialing based on plain text, or whether it requires special markup.</summary>
		/// <returns>true if the browser supports phone dialing based on plain text only; otherwise, false. The default is false.</returns>
		// Token: 0x1700132F RID: 4911
		// (get) Token: 0x06003DAF RID: 15791 RVA: 0x000A39C7 File Offset: 0x000A1BC7
		public virtual bool RequiresPhoneNumbersAsPlainText
		{
			get
			{
				if (!this.Get(69))
				{
					this.requiresPhoneNumbersAsPlainText = this.ReadBoolean("requiresphonenumbersasplaintext");
					this.Set(69);
				}
				return this.requiresPhoneNumbersAsPlainText;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires VIEWSTATE values to be specially encoded.</summary>
		/// <returns>true if the browser requires VIEWSTATE values to be specially encoded; otherwise, false. The default is false.</returns>
		// Token: 0x17001330 RID: 4912
		// (get) Token: 0x06003DB0 RID: 15792 RVA: 0x000A39F2 File Offset: 0x000A1BF2
		public virtual bool RequiresSpecialViewStateEncoding
		{
			get
			{
				if (!this.Get(70))
				{
					this.requiresSpecialViewStateEncoding = this.ReadBoolean("requiresspecialviewstateencoding");
					this.Set(70);
				}
				return this.requiresSpecialViewStateEncoding;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires unique form-action URLs.</summary>
		/// <returns>true if the browser requires unique form-action URLs; otherwise, false. The default is false.</returns>
		// Token: 0x17001331 RID: 4913
		// (get) Token: 0x06003DB1 RID: 15793 RVA: 0x000A3A1D File Offset: 0x000A1C1D
		public virtual bool RequiresUniqueFilePathSuffix
		{
			get
			{
				if (!this.Get(71))
				{
					this.requiresUniqueFilePathSuffix = this.ReadBoolean("requiresuniquefilepathsuffix");
					this.Set(71);
				}
				return this.requiresUniqueFilePathSuffix;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires unique name attribute values of multiple HTML &lt;input type="checkbox"&gt; elements.</summary>
		/// <returns>true if the browser requires unique name attribute values of multiple HTML &lt;input type="checkbox"&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001332 RID: 4914
		// (get) Token: 0x06003DB2 RID: 15794 RVA: 0x000A3A48 File Offset: 0x000A1C48
		public virtual bool RequiresUniqueHtmlCheckboxNames
		{
			get
			{
				if (!this.Get(72))
				{
					this.requiresUniqueHtmlCheckboxNames = this.ReadBoolean("requiresuniquehtmlcheckboxnames");
					this.Set(72);
				}
				return this.requiresUniqueHtmlCheckboxNames;
			}
		}

		/// <summary>Gets a value indicating whether the browser requires unique name attribute values of multiple HTML &lt;input&gt; elements.</summary>
		/// <returns>true if the browser requires unique name attribute values of multiple HTML &lt;input&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001333 RID: 4915
		// (get) Token: 0x06003DB3 RID: 15795 RVA: 0x000A3A73 File Offset: 0x000A1C73
		public virtual bool RequiresUniqueHtmlInputNames
		{
			get
			{
				if (!this.Get(73))
				{
					this.requiresUniqueHtmlInputNames = this.ReadBoolean("requiresuniquehtmlinputnames");
					this.Set(73);
				}
				return this.requiresUniqueHtmlInputNames;
			}
		}

		/// <summary>Gets a value indicating whether postback data sent by the browser will be UrlEncoded.</summary>
		/// <returns>true if postback data sent by the browser will be UrlEncoded; otherwise, false. The default is false.</returns>
		// Token: 0x17001334 RID: 4916
		// (get) Token: 0x06003DB4 RID: 15796 RVA: 0x000A3A9E File Offset: 0x000A1C9E
		public virtual bool RequiresUrlEncodedPostfieldValues
		{
			get
			{
				if (!this.Get(74))
				{
					this.requiresUrlEncodedPostfieldValues = this.ReadBoolean("requiresurlencodedpostfieldvalues");
					this.Set(74);
				}
				return this.requiresUrlEncodedPostfieldValues;
			}
		}

		/// <summary>Returns the depth of the display, in bits per pixel.</summary>
		/// <returns>The depth of the display, in bits per pixel. The default is 1.</returns>
		// Token: 0x17001335 RID: 4917
		// (get) Token: 0x06003DB5 RID: 15797 RVA: 0x000A3AC9 File Offset: 0x000A1CC9
		public virtual int ScreenBitDepth
		{
			get
			{
				if (!this.Get(75))
				{
					this.screenBitDepth = this.ReadInt32("screenbitdepth");
					this.Set(75);
				}
				return this.screenBitDepth;
			}
		}

		/// <summary>Returns the approximate height of the display, in character lines.</summary>
		/// <returns>The approximate height of the display, in character lines. The default is 6.</returns>
		// Token: 0x17001336 RID: 4918
		// (get) Token: 0x06003DB6 RID: 15798 RVA: 0x000A3AF4 File Offset: 0x000A1CF4
		public virtual int ScreenCharactersHeight
		{
			get
			{
				if (!this.Get(76))
				{
					this.screenCharactersHeight = this.ReadInt32("screencharactersheight");
					this.Set(76);
				}
				return this.screenCharactersHeight;
			}
		}

		/// <summary>Returns the approximate width of the display, in characters.</summary>
		/// <returns>The approximate width of the display, in characters. The default is 12.</returns>
		// Token: 0x17001337 RID: 4919
		// (get) Token: 0x06003DB7 RID: 15799 RVA: 0x000A3B1F File Offset: 0x000A1D1F
		public virtual int ScreenCharactersWidth
		{
			get
			{
				if (!this.Get(77))
				{
					this.screenCharactersWidth = this.ReadInt32("screencharacterswidth");
					this.Set(77);
				}
				return this.screenCharactersWidth;
			}
		}

		/// <summary>Returns the approximate height of the display, in pixels.</summary>
		/// <returns>The approximate height of the display, in pixels. The default is 72.</returns>
		// Token: 0x17001338 RID: 4920
		// (get) Token: 0x06003DB8 RID: 15800 RVA: 0x000A3B4A File Offset: 0x000A1D4A
		public virtual int ScreenPixelsHeight
		{
			get
			{
				if (!this.Get(78))
				{
					this.screenPixelsHeight = this.ReadInt32("screenpixelsheight");
					this.Set(78);
				}
				return this.screenPixelsHeight;
			}
		}

		/// <summary>Returns the approximate width of the display, in pixels.</summary>
		/// <returns>The approximate width of the display, in pixels. The default is 96.</returns>
		// Token: 0x17001339 RID: 4921
		// (get) Token: 0x06003DB9 RID: 15801 RVA: 0x000A3B75 File Offset: 0x000A1D75
		public virtual int ScreenPixelsWidth
		{
			get
			{
				if (!this.Get(79))
				{
					this.screenPixelsWidth = this.ReadInt32("screenpixelswidth");
					this.Set(79);
				}
				return this.screenPixelsWidth;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the ACCESSKEY attribute of HTML &lt;a&gt; (anchor) and &lt;input&gt; elements.</summary>
		/// <returns>true if the browser supports the accesskey attribute of HTML &lt;a&gt;  (anchor) and &lt;input&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x1700133A RID: 4922
		// (get) Token: 0x06003DBA RID: 15802 RVA: 0x000A3BA0 File Offset: 0x000A1DA0
		public virtual bool SupportsAccesskeyAttribute
		{
			get
			{
				if (!this.Get(80))
				{
					this.supportsAccesskeyAttribute = this.ReadBoolean("supportsaccesskeyattribute");
					this.Set(80);
				}
				return this.supportsAccesskeyAttribute;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the bgcolor attribute of the HTML &lt;body&gt; element.</summary>
		/// <returns>true if the browser supports the bgcolor attribute of the HTML &lt;body&gt; element; otherwise, false. The default is true.</returns>
		// Token: 0x1700133B RID: 4923
		// (get) Token: 0x06003DBB RID: 15803 RVA: 0x000A3BCB File Offset: 0x000A1DCB
		public virtual bool SupportsBodyColor
		{
			get
			{
				if (!this.Get(81))
				{
					this.supportsBodyColor = this.ReadBoolean("supportsbodycolor");
					this.Set(81);
				}
				return this.supportsBodyColor;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports HTML &lt;b&gt; elements to format bold text.</summary>
		/// <returns>true if the browser supports HTML &lt;b&gt;  elements to format bold text; otherwise, false. The default is false.</returns>
		// Token: 0x1700133C RID: 4924
		// (get) Token: 0x06003DBC RID: 15804 RVA: 0x000A3BF6 File Offset: 0x000A1DF6
		public virtual bool SupportsBold
		{
			get
			{
				if (!this.Get(82))
				{
					this.supportsBold = this.ReadBoolean("supportsbold");
					this.Set(82);
				}
				return this.supportsBold;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the cache-control value for the http-equiv attribute of HTML &lt;meta&gt; elements.</summary>
		/// <returns>true if the browser supports the cache-control value for the http-equiv attribute of HTML &lt;meta&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x1700133D RID: 4925
		// (get) Token: 0x06003DBD RID: 15805 RVA: 0x000A3C21 File Offset: 0x000A1E21
		public virtual bool SupportsCacheControlMetaTag
		{
			get
			{
				if (!this.Get(83))
				{
					this.supportsCacheControlMetaTag = this.ReadBoolean("supportscachecontrolmetatag");
					this.Set(83);
				}
				return this.supportsCacheControlMetaTag;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports callback scripts.</summary>
		/// <returns>true if the browser supports callback scripts; otherwise, false. The default is false.</returns>
		// Token: 0x1700133E RID: 4926
		// (get) Token: 0x06003DBE RID: 15806 RVA: 0x000A3C4C File Offset: 0x000A1E4C
		public virtual bool SupportsCallback
		{
			get
			{
				if (!this.Get(84))
				{
					this.supportsCallback = this.ReadBoolean("supportscallback");
					this.Set(84);
				}
				return this.supportsCallback;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports Cascading Style Sheets (CSS).</summary>
		/// <returns>true if the browser supports CSS; otherwise, false. The default is false.</returns>
		// Token: 0x1700133F RID: 4927
		// (get) Token: 0x06003DBF RID: 15807 RVA: 0x000A3C77 File Offset: 0x000A1E77
		public virtual bool SupportsCss
		{
			get
			{
				if (!this.Get(85))
				{
					this.supportsCss = this.ReadBoolean("supportscss");
					this.Set(85);
				}
				return this.supportsCss;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the align attribute of HTML &lt;div&gt; elements.</summary>
		/// <returns>true if the browser supports the align attribute of HTML &lt;div&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x17001340 RID: 4928
		// (get) Token: 0x06003DC0 RID: 15808 RVA: 0x000A3CA2 File Offset: 0x000A1EA2
		public virtual bool SupportsDivAlign
		{
			get
			{
				if (!this.Get(86))
				{
					this.supportsDivAlign = this.ReadBoolean("supportsdivalign");
					this.Set(86);
				}
				return this.supportsDivAlign;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the nowrap attribute of HTML &lt;div&gt; elements.</summary>
		/// <returns>true if the browser supports the nowrap attribute of HTML &lt;div&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001341 RID: 4929
		// (get) Token: 0x06003DC1 RID: 15809 RVA: 0x000A3CCD File Offset: 0x000A1ECD
		public virtual bool SupportsDivNoWrap
		{
			get
			{
				if (!this.Get(87))
				{
					this.supportsDivNoWrap = this.ReadBoolean("supportsdivnowrap");
					this.Set(64);
				}
				return this.supportsDivNoWrap;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports empty (null) strings in cookie values.</summary>
		/// <returns>true if the browser supports empty (null) strings in cookie values; otherwise, false. The default is false.</returns>
		// Token: 0x17001342 RID: 4930
		// (get) Token: 0x06003DC2 RID: 15810 RVA: 0x000A3CF8 File Offset: 0x000A1EF8
		public virtual bool SupportsEmptyStringInCookieValue
		{
			get
			{
				if (!this.Get(88))
				{
					this.supportsEmptyStringInCookieValue = this.ReadBoolean("supportsemptystringincookievalue");
					this.Set(88);
				}
				return this.supportsEmptyStringInCookieValue;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the color attribute of HTML &lt;font&gt; elements.</summary>
		/// <returns>true if the browser supports the color attribute of HTML &lt;font&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x17001343 RID: 4931
		// (get) Token: 0x06003DC3 RID: 15811 RVA: 0x000A3D23 File Offset: 0x000A1F23
		public virtual bool SupportsFontColor
		{
			get
			{
				if (!this.Get(89))
				{
					this.supportsFontColor = this.ReadBoolean("supportsfontcolor");
					this.Set(89);
				}
				return this.supportsFontColor;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the name attribute of HTML &lt;font&gt; elements.</summary>
		/// <returns>true if the browser supports the name attribute of HTML &lt;font&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001344 RID: 4932
		// (get) Token: 0x06003DC4 RID: 15812 RVA: 0x000A3D4E File Offset: 0x000A1F4E
		public virtual bool SupportsFontName
		{
			get
			{
				if (!this.Get(90))
				{
					this.supportsFontName = this.ReadBoolean("supportsfontname");
					this.Set(90);
				}
				return this.supportsFontName;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the size attribute of HTML &lt;font&gt; elements.</summary>
		/// <returns>true if the browser supports the size attribute of HTML &lt;font&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001345 RID: 4933
		// (get) Token: 0x06003DC5 RID: 15813 RVA: 0x000A3D79 File Offset: 0x000A1F79
		public virtual bool SupportsFontSize
		{
			get
			{
				if (!this.Get(91))
				{
					this.supportsFontSize = this.ReadBoolean("supportsfontsize");
					this.Set(91);
				}
				return this.supportsFontSize;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports using a custom image in place of a standard form Submit button.</summary>
		/// <returns>true if the browser supports using a custom image in place of a standard form Submit button; otherwise, false. The default is false.</returns>
		// Token: 0x17001346 RID: 4934
		// (get) Token: 0x06003DC6 RID: 15814 RVA: 0x000A3DA4 File Offset: 0x000A1FA4
		public virtual bool SupportsImageSubmit
		{
			get
			{
				if (!this.Get(92))
				{
					this.supportsImageSubmit = this.ReadBoolean("supportsimagesubmit");
					this.Set(92);
				}
				return this.supportsImageSubmit;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports i-mode symbols.</summary>
		/// <returns>true if the browser supports i-mode symbols; otherwise, false. The default is false.</returns>
		// Token: 0x17001347 RID: 4935
		// (get) Token: 0x06003DC7 RID: 15815 RVA: 0x000A3DCF File Offset: 0x000A1FCF
		public virtual bool SupportsIModeSymbols
		{
			get
			{
				if (!this.Get(93))
				{
					this.supportsIModeSymbols = this.ReadBoolean("supportsimodesymbols");
					this.Set(93);
				}
				return this.supportsIModeSymbols;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the istyle attribute of HTML &lt;input&gt; elements.</summary>
		/// <returns>true if the browser supports the istyle attribute of HTML &lt;input&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001348 RID: 4936
		// (get) Token: 0x06003DC8 RID: 15816 RVA: 0x000A3DFA File Offset: 0x000A1FFA
		public virtual bool SupportsInputIStyle
		{
			get
			{
				if (!this.Get(94))
				{
					this.supportsInputIStyle = this.ReadBoolean("supportsinputistyle");
					this.Set(94);
				}
				return this.supportsInputIStyle;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the mode attribute of HTML &lt;input&gt; elements.</summary>
		/// <returns>true if the browser supports the mode attribute of HTML &lt;input&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001349 RID: 4937
		// (get) Token: 0x06003DC9 RID: 15817 RVA: 0x000A3E25 File Offset: 0x000A2025
		public virtual bool SupportsInputMode
		{
			get
			{
				if (!this.Get(95))
				{
					this.supportsInputMode = this.ReadBoolean("supportsinputmode");
					this.Set(95);
				}
				return this.supportsInputMode;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports HTML &lt;i&gt; elements to format italic text.</summary>
		/// <returns>true if the browser supports HTML &lt;i&gt; elements to format italic text; otherwise, false. The default is false.</returns>
		// Token: 0x1700134A RID: 4938
		// (get) Token: 0x06003DCA RID: 15818 RVA: 0x000A3E50 File Offset: 0x000A2050
		public virtual bool SupportsItalic
		{
			get
			{
				if (!this.Get(96))
				{
					this.supportsItalic = this.ReadBoolean("supportsitalic");
					this.Set(96);
				}
				return this.supportsItalic;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports J-Phone multimedia attributes.</summary>
		/// <returns>true if the browser supports J-Phone multimedia attributes; otherwise, false. The default is false.</returns>
		// Token: 0x1700134B RID: 4939
		// (get) Token: 0x06003DCB RID: 15819 RVA: 0x000A3E7B File Offset: 0x000A207B
		public virtual bool SupportsJPhoneMultiMediaAttributes
		{
			get
			{
				if (!this.Get(97))
				{
					this.supportsJPhoneMultiMediaAttributes = this.ReadBoolean("supportsjphonemultimediaattributes");
					this.Set(97);
				}
				return this.supportsJPhoneMultiMediaAttributes;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports J-Phone–specific picture symbols.</summary>
		/// <returns>true if the browser supports J-Phone–specific picture symbols; otherwise, false. The default is false.</returns>
		// Token: 0x1700134C RID: 4940
		// (get) Token: 0x06003DCC RID: 15820 RVA: 0x000A3EA6 File Offset: 0x000A20A6
		public virtual bool SupportsJPhoneSymbols
		{
			get
			{
				if (!this.Get(98))
				{
					this.supportsJPhoneSymbols = this.ReadBoolean("supportsjphonesymbols");
					this.Set(98);
				}
				return this.supportsJPhoneSymbols;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports a query string in the action attribute value of HTML &lt;form&gt; elements.</summary>
		/// <returns>true if the browser supports a query string in the action attribute value of HTML &lt;form&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x1700134D RID: 4941
		// (get) Token: 0x06003DCD RID: 15821 RVA: 0x000A3ED1 File Offset: 0x000A20D1
		public virtual bool SupportsQueryStringInFormAction
		{
			get
			{
				if (!this.Get(99))
				{
					this.supportsQueryStringInFormAction = this.ReadBoolean("supportsquerystringinformaction");
					this.Set(99);
				}
				return this.supportsQueryStringInFormAction;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports cookies on redirection.</summary>
		/// <returns>true if the browser supports cookies on redirection; otherwise, false. The default is true.</returns>
		// Token: 0x1700134E RID: 4942
		// (get) Token: 0x06003DCE RID: 15822 RVA: 0x000A3EFC File Offset: 0x000A20FC
		public virtual bool SupportsRedirectWithCookie
		{
			get
			{
				if (!this.Get(100))
				{
					this.supportsRedirectWithCookie = this.ReadBoolean("supportsredirectwithcookie");
					this.Set(100);
				}
				return this.supportsRedirectWithCookie;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports the multiple attribute of HTML &lt;select&gt; elements.</summary>
		/// <returns>true if the browser supports the multiple attribute of HTML &lt;select&gt; elements; otherwise, false. The default is true.</returns>
		// Token: 0x1700134F RID: 4943
		// (get) Token: 0x06003DCF RID: 15823 RVA: 0x000A3F27 File Offset: 0x000A2127
		public virtual bool SupportsSelectMultiple
		{
			get
			{
				if (!this.Get(101))
				{
					this.supportsSelectMultiple = this.ReadBoolean("supportsselectmultiple");
					this.Set(101);
				}
				return this.supportsSelectMultiple;
			}
		}

		/// <summary>Gets a value indicating whether the clearing of a checked HTML &lt;input type=checkbox&gt; element is reflected in postback data.</summary>
		/// <returns>true if the clearing of a checked HTML &lt;input type=checkbox&gt; element is reflected in postback data; otherwise, false. The default is true.</returns>
		// Token: 0x17001350 RID: 4944
		// (get) Token: 0x06003DD0 RID: 15824 RVA: 0x000A3F52 File Offset: 0x000A2152
		public virtual bool SupportsUncheck
		{
			get
			{
				if (!this.Get(102))
				{
					this.supportsUncheck = this.ReadBoolean("supportsuncheck");
					this.Set(102);
				}
				return this.supportsUncheck;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports receiving XML over HTTP.</summary>
		/// <returns>true if the browser supports receiving XML over HTTP; otherwise, false. The default is false.</returns>
		// Token: 0x17001351 RID: 4945
		// (get) Token: 0x06003DD1 RID: 15825 RVA: 0x000A3F7D File Offset: 0x000A217D
		public virtual bool SupportsXmlHttp
		{
			get
			{
				if (!this.Get(103))
				{
					this.supportsXmlHttp = this.ReadBoolean("supportsxmlhttp");
					this.Set(103);
				}
				return this.supportsXmlHttp;
			}
		}

		/// <summary>Used internally to get a value indicating whether to use an optimized cache key.</summary>
		/// <returns>true to use an optimized cache key; otherwise, false. The default is false.</returns>
		// Token: 0x17001352 RID: 4946
		// (get) Token: 0x06003DD2 RID: 15826 RVA: 0x000A3FA8 File Offset: 0x000A21A8
		public bool UseOptimizedCacheKey
		{
			get
			{
				if (!this.Get(107))
				{
					this.useOptimizedCacheKey = this.ReadBoolean("useoptimizedcachekey");
					this.Set(107);
				}
				return this.useOptimizedCacheKey;
			}
		}

		/// <summary>Gets or sets the <see cref="T:System.Web.Configuration.HttpCapabilitiesProvider" /> object for the current browser.</summary>
		/// <returns>The <see cref="T:System.Web.Configuration.HttpCapabilitiesProvider" /> object for the current browser.</returns>
		// Token: 0x17001353 RID: 4947
		// (get) Token: 0x06003DD3 RID: 15827 RVA: 0x000A3FD3 File Offset: 0x000A21D3
		// (set) Token: 0x06003DD4 RID: 15828 RVA: 0x000A3FDA File Offset: 0x000A21DA
		public static HttpCapabilitiesProvider BrowserCapabilitiesProvider
		{
			get
			{
				return HttpCapabilitiesBase._provider;
			}
			set
			{
				HttpCapabilitiesBase._provider = value;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports ActiveX controls.</summary>
		/// <returns>true if the browser supports ActiveX controls; otherwise, false. The default is false.</returns>
		// Token: 0x17001354 RID: 4948
		// (get) Token: 0x06003DD5 RID: 15829 RVA: 0x000A3FE2 File Offset: 0x000A21E2
		public bool ActiveXControls
		{
			get
			{
				if (!this.Get(1))
				{
					this.activeXControls = this.ReadBoolean("activexcontrols");
					this.Set(1);
				}
				return this.activeXControls;
			}
		}

		/// <summary>Gets a value indicating whether the client is an America Online (AOL) browser.</summary>
		/// <returns>true if the browser is an AOL browser; otherwise, false. The default is false.</returns>
		// Token: 0x17001355 RID: 4949
		// (get) Token: 0x06003DD6 RID: 15830 RVA: 0x000A400B File Offset: 0x000A220B
		public bool AOL
		{
			get
			{
				if (!this.Get(3))
				{
					this.aol = this.ReadBoolean("aol");
					this.Set(3);
				}
				return this.aol;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports playing background sounds using the &lt;bgsounds&gt; HTML element.</summary>
		/// <returns>true if the browser supports playing background sounds; otherwise, false. The default is false.</returns>
		// Token: 0x17001356 RID: 4950
		// (get) Token: 0x06003DD7 RID: 15831 RVA: 0x000A4034 File Offset: 0x000A2234
		public bool BackgroundSounds
		{
			get
			{
				if (!this.Get(4))
				{
					this.backgroundSounds = this.ReadBoolean("backgroundsounds");
					this.Set(4);
				}
				return this.backgroundSounds;
			}
		}

		/// <summary>Gets a value indicating whether the browser is a beta version.</summary>
		/// <returns>true if the browser is a beta version; otherwise, false. The default is false.</returns>
		// Token: 0x17001357 RID: 4951
		// (get) Token: 0x06003DD8 RID: 15832 RVA: 0x000A405D File Offset: 0x000A225D
		public bool Beta
		{
			get
			{
				if (!this.Get(5))
				{
					this.beta = this.ReadBoolean("beta");
					this.Set(5);
				}
				return this.beta;
			}
		}

		/// <summary>Gets the browser string (if any) that was sent by the browser in the User-Agent request header.</summary>
		/// <returns>The contents of the User-Agent request header sent by the browser.</returns>
		// Token: 0x17001358 RID: 4952
		// (get) Token: 0x06003DD9 RID: 15833 RVA: 0x000A4088 File Offset: 0x000A2288
		public string Browser
		{
			get
			{
				if (!this.Get(6))
				{
					this.browser = this["browser"];
					if (this.browser == null || this.browser.Length == 0)
					{
						this.browser = "Unknown";
					}
					this.Set(6);
				}
				return this.browser;
			}
		}

		/// <summary>Gets an <see cref="T:System.Collections.ArrayList" /> of the browsers in the <see cref="P:System.Web.Configuration.HttpCapabilitiesBase.Capabilities" /> dictionary.</summary>
		/// <returns>An <see cref="T:System.Collections.ArrayList" /> of the browsers in the <see cref="P:System.Web.Configuration.HttpCapabilitiesBase.Capabilities" /> dictionary.</returns>
		// Token: 0x17001359 RID: 4953
		// (get) Token: 0x06003DDA RID: 15834 RVA: 0x000A40DC File Offset: 0x000A22DC
		public ArrayList Browsers
		{
			get
			{
				if (!this.Get(7))
				{
					this.browsers = this.ReadArrayList("browsers");
					this.Set(7);
				}
				return this.browsers;
			}
		}

		/// <summary>Gets a value indicating whether the client browser is the same as the specified browser.</summary>
		/// <returns>true if the client browser is the same as the specified browser; otherwise, false. The default is false.</returns>
		/// <param name="browserName">The specified browser.</param>
		// Token: 0x06003DDB RID: 15835 RVA: 0x000A4108 File Offset: 0x000A2308
		public bool IsBrowser(string browserName)
		{
			foreach (object obj in this.Browsers)
			{
				string text = (string)obj;
				if (string.Compare(text, "Unknown", StringComparison.OrdinalIgnoreCase) != 0 && string.Compare(browserName, text, StringComparison.OrdinalIgnoreCase) == 0)
				{
					return true;
				}
			}
			return false;
		}

		/// <summary>Gets a value indicating whether the browser supports Channel Definition Format (CDF) for webcasting.</summary>
		/// <returns>true if the browser supports CDF; otherwise, false. The default is false.</returns>
		// Token: 0x1700135A RID: 4954
		// (get) Token: 0x06003DDC RID: 15836 RVA: 0x000A417C File Offset: 0x000A237C
		public bool CDF
		{
			get
			{
				if (!this.Get(18))
				{
					this.cdf = this.ReadBoolean("cdf");
					this.Set(18);
				}
				return this.cdf;
			}
		}

		/// <summary>Gets the version of the .NET Framework that is installed on the client.</summary>
		/// <returns>The common language runtime <see cref="T:System.Version" />.</returns>
		// Token: 0x1700135B RID: 4955
		// (get) Token: 0x06003DDD RID: 15837 RVA: 0x000A41A7 File Offset: 0x000A23A7
		public Version ClrVersion
		{
			get
			{
				if (this.clrVersion == null)
				{
					this.InternalGetClrVersions();
				}
				return this.clrVersion;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports cookies.</summary>
		/// <returns>true if the browser supports cookies; otherwise, false. The default is false.</returns>
		// Token: 0x1700135C RID: 4956
		// (get) Token: 0x06003DDE RID: 15838 RVA: 0x000A41C3 File Offset: 0x000A23C3
		public bool Cookies
		{
			get
			{
				if (!this.Get(20))
				{
					this.cookies = this.ReadBoolean("cookies");
					this.Set(20);
				}
				return this.cookies;
			}
		}

		/// <summary>Gets a value indicating whether the browser is a search engine Web crawler.</summary>
		/// <returns>true if the browser is a search engine; otherwise, false. The default is false.</returns>
		// Token: 0x1700135D RID: 4957
		// (get) Token: 0x06003DDF RID: 15839 RVA: 0x000A41EE File Offset: 0x000A23EE
		public bool Crawler
		{
			get
			{
				if (!this.Get(21))
				{
					this.crawler = this.ReadBoolean("crawler");
					this.Set(21);
				}
				return this.crawler;
			}
		}

		/// <summary>Gets the version number of ECMAScript that the browser supports.</summary>
		/// <returns>The version number of ECMAScript that the browser supports.</returns>
		// Token: 0x1700135E RID: 4958
		// (get) Token: 0x06003DE0 RID: 15840 RVA: 0x000A4219 File Offset: 0x000A2419
		public Version EcmaScriptVersion
		{
			get
			{
				if (!this.Get(23))
				{
					this.ecmaScriptVersion = this.ReadVersion("ecmascriptversion");
					this.Set(23);
				}
				return this.ecmaScriptVersion;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports HTML frames.</summary>
		/// <returns>true if the browser supports frames; otherwise, false. The default is false.</returns>
		// Token: 0x1700135F RID: 4959
		// (get) Token: 0x06003DE1 RID: 15841 RVA: 0x000A4244 File Offset: 0x000A2444
		public bool Frames
		{
			get
			{
				if (!this.Get(24))
				{
					this.frames = this.ReadBoolean("frames");
					this.Set(24);
				}
				return this.frames;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports Java.</summary>
		/// <returns>true if the browser supports Java; otherwise, false. The default is false.</returns>
		// Token: 0x17001360 RID: 4960
		// (get) Token: 0x06003DE2 RID: 15842 RVA: 0x000A426F File Offset: 0x000A246F
		public bool JavaApplets
		{
			get
			{
				if (!this.Get(35))
				{
					this.javaApplets = this.ReadBoolean("javaapplets");
					this.Set(35);
				}
				return this.javaApplets;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports JavaScript.</summary>
		/// <returns>true if the browser supports JavaScript; otherwise, false. The default is false.</returns>
		// Token: 0x17001361 RID: 4961
		// (get) Token: 0x06003DE3 RID: 15843 RVA: 0x000A429A File Offset: 0x000A249A
		[Obsolete("The recommended alternative is the EcmaScriptVersion property. A Major version value greater than or equal to 1 implies JavaScript support. http://go.microsoft.com/fwlink/?linkid=14202")]
		public bool JavaScript
		{
			get
			{
				if (!this.Get(36))
				{
					this.javaScript = this.ReadBoolean("javascript");
					this.Set(36);
				}
				return this.javaScript;
			}
		}

		/// <summary>Gets the major (integer) version number of the browser.</summary>
		/// <returns>The major version number of the browser.</returns>
		/// <exception cref="T:System.Exception">The major version value is not an integer.</exception>
		// Token: 0x17001362 RID: 4962
		// (get) Token: 0x06003DE4 RID: 15844 RVA: 0x000A42C8 File Offset: 0x000A24C8
		public int MajorVersion
		{
			get
			{
				if (!this.Get(38))
				{
					if (this["majorversion"] != null)
					{
						this.majorVersion = this.ReadInt32("majorversion");
					}
					else
					{
						this.majorVersion = this.ReadInt32("majorver");
					}
					this.Set(38);
				}
				return this.majorVersion;
			}
		}

		/// <summary>Gets the minor (that is, decimal) version number of the browser.</summary>
		/// <returns>The minor version number of the browser.</returns>
		/// <exception cref="T:System.Web.HttpUnhandledException">The minor version number in the header is not valid.</exception>
		// Token: 0x17001363 RID: 4963
		// (get) Token: 0x06003DE5 RID: 15845 RVA: 0x000A4320 File Offset: 0x000A2520
		public double MinorVersion
		{
			get
			{
				if (!this.Get(42))
				{
					if (this["minorversion"] != null)
					{
						this.minorVersion = this.ReadDouble("minorversion");
					}
					else
					{
						this.minorVersion = this.ReadDouble("minorver");
					}
					this.Set(42);
				}
				return this.minorVersion;
			}
		}

		/// <summary>Gets the version of Microsoft HTML (MSHTML) Document Object Model (DOM) that the browser supports.</summary>
		/// <returns>The number of the MSHTML DOM version that the browser supports.</returns>
		// Token: 0x17001364 RID: 4964
		// (get) Token: 0x06003DE6 RID: 15846 RVA: 0x000A4376 File Offset: 0x000A2576
		public Version MSDomVersion
		{
			get
			{
				if (!this.Get(46))
				{
					this.msDomVersion = this.ReadVersion("msdomversion");
					this.Set(46);
				}
				return this.msDomVersion;
			}
		}

		/// <summary>Gets the name of the platform that the client uses, if it is known.</summary>
		/// <returns>The operating system that the client uses, if it is known, otherwise the value is set to Unknown.</returns>
		// Token: 0x17001365 RID: 4965
		// (get) Token: 0x06003DE7 RID: 15847 RVA: 0x000A43A1 File Offset: 0x000A25A1
		public string Platform
		{
			get
			{
				if (!this.Get(48))
				{
					this.platform = this.ReadString("platform");
					this.Set(48);
				}
				return this.platform;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports HTML &lt;table&gt; elements.</summary>
		/// <returns>true if the browser supports HTML &lt;table&gt; elements; otherwise, false. The default is false.</returns>
		// Token: 0x17001366 RID: 4966
		// (get) Token: 0x06003DE8 RID: 15848 RVA: 0x000A43CC File Offset: 0x000A25CC
		public bool Tables
		{
			get
			{
				if (!this.Get(104))
				{
					this.tables = this.ReadBoolean("tables");
					this.Set(104);
				}
				return this.tables;
			}
		}

		/// <summary>Used internally to get the type of the object that is used to write tags for the browser.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the object that is used to write tags for the browser.</returns>
		/// <exception cref="T:System.Web.HttpUnhandledException">There is a parse error.</exception>
		// Token: 0x17001367 RID: 4967
		// (get) Token: 0x06003DE9 RID: 15849 RVA: 0x000A43F7 File Offset: 0x000A25F7
		public Type TagWriter
		{
			get
			{
				if (!this.Get(105))
				{
					this.tagWriter = this.GetTagWriter();
					this.Set(105);
				}
				return this.tagWriter;
			}
		}

		// Token: 0x06003DEA RID: 15850 RVA: 0x000A441D File Offset: 0x000A261D
		internal virtual Type GetTagWriter()
		{
			return typeof(HtmlTextWriter);
		}

		/// <summary>Gets the name and major (integer) version number of the browser.</summary>
		/// <returns>The name and major version number of the browser.</returns>
		// Token: 0x17001368 RID: 4968
		// (get) Token: 0x06003DEB RID: 15851 RVA: 0x000A4429 File Offset: 0x000A2629
		public string Type
		{
			get
			{
				return this.Browser + this.MajorVersion;
			}
		}

		/// <summary>Gets a value indicating whether the browser supports Visual Basic Scripting edition (VBScript).</summary>
		/// <returns>true if the browser supports VBScript; otherwise, false. The default is false.</returns>
		// Token: 0x17001369 RID: 4969
		// (get) Token: 0x06003DEC RID: 15852 RVA: 0x000A4441 File Offset: 0x000A2641
		public bool VBScript
		{
			get
			{
				if (!this.Get(108))
				{
					this.vbscript = this.ReadBoolean("vbscript");
					this.Set(108);
				}
				return this.vbscript;
			}
		}

		/// <summary>Gets the full version number (integer and decimal) of the browser as a string.</summary>
		/// <returns>The full version number of the browser as a string.</returns>
		// Token: 0x1700136A RID: 4970
		// (get) Token: 0x06003DED RID: 15853 RVA: 0x000A446C File Offset: 0x000A266C
		public string Version
		{
			get
			{
				if (!this.Get(109))
				{
					this.version = this.ReadString("version");
					this.Set(109);
				}
				return this.version;
			}
		}

		/// <summary>Gets the version of the World Wide Web Consortium (W3C) XML Document Object Model (DOM) that the browser supports.</summary>
		/// <returns>The number of the W3C XML DOM version number that the browser supports.</returns>
		// Token: 0x1700136B RID: 4971
		// (get) Token: 0x06003DEE RID: 15854 RVA: 0x000A4497 File Offset: 0x000A2697
		public Version W3CDomVersion
		{
			get
			{
				if (!this.Get(110))
				{
					this.w3CDomVersion = this.ReadVersion("w3cdomversion");
					this.Set(110);
				}
				return this.w3CDomVersion;
			}
		}

		/// <summary>Gets a value indicating whether the client is a Win16-based computer.</summary>
		/// <returns>true if the browser is running on a Win16-based computer; otherwise, false. The default is false.</returns>
		// Token: 0x1700136C RID: 4972
		// (get) Token: 0x06003DEF RID: 15855 RVA: 0x000A44C2 File Offset: 0x000A26C2
		public bool Win16
		{
			get
			{
				if (!this.Get(111))
				{
					this.win16 = this.ReadBoolean("win16");
					this.Set(111);
				}
				return this.win16;
			}
		}

		/// <summary>Gets a value indicating whether the client is a Win32-based computer.</summary>
		/// <returns>true if the client is a Win32-based computer; otherwise, false. The default is false.</returns>
		// Token: 0x1700136D RID: 4973
		// (get) Token: 0x06003DF0 RID: 15856 RVA: 0x000A44F0 File Offset: 0x000A26F0
		public bool Win32
		{
			get
			{
				if (!this.Get(112))
				{
					string text = this.Platform;
					this.win32 = text != "Win16" && text.StartsWith("Win");
					this.Set(112);
				}
				return this.win32;
			}
		}

		/// <summary>Returns all versions of the .NET Framework common language runtime that are installed on the client.</summary>
		/// <returns>An array of <see cref="T:System.Version" /> objects.</returns>
		// Token: 0x06003DF1 RID: 15857 RVA: 0x000A453D File Offset: 0x000A273D
		public Version[] GetClrVersions()
		{
			if (this.clrVersions == null)
			{
				this.InternalGetClrVersions();
			}
			return this.clrVersions;
		}

		// Token: 0x06003DF2 RID: 15858 RVA: 0x000A4554 File Offset: 0x000A2754
		private void InternalGetClrVersions()
		{
			char[] array = new char[] { ';', ')' };
			string text = this.useragent;
			ArrayList arrayList = null;
			int num;
			while (text != null && (num = text.IndexOf(".NET CLR ")) != -1)
			{
				int num2 = text.IndexOfAny(array, num + 9);
				if (num2 == -1)
				{
					break;
				}
				string text2 = text.Substring(num + 9, num2 - num - 9);
				try
				{
					Version version = new Version(text2);
					if (this.clrVersion == null || version > this.clrVersion)
					{
						this.clrVersion = version;
					}
					if (arrayList == null)
					{
						arrayList = new ArrayList(4);
					}
					arrayList.Add(version);
				}
				catch
				{
				}
				text = text.Substring(num + 9);
			}
			if (arrayList == null || arrayList.Count == 0)
			{
				this.clrVersion = new Version();
				this.clrVersions = null;
				return;
			}
			arrayList.Sort();
			this.clrVersions = (Version[])arrayList.ToArray(typeof(Version));
		}

		// Token: 0x06003DF3 RID: 15859 RVA: 0x000A465C File Offset: 0x000A285C
		private bool ReadBoolean(string key)
		{
			string text = this[key];
			if (text == null)
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			return string.Compare(text, "True", true, Helpers.InvariantCulture) == 0;
		}

		// Token: 0x06003DF4 RID: 15860 RVA: 0x000A4684 File Offset: 0x000A2884
		private int ReadInt32(string key)
		{
			string text = this[key];
			if (text == null)
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			int num;
			try
			{
				num = int.Parse(text);
			}
			catch
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			return num;
		}

		// Token: 0x06003DF5 RID: 15861 RVA: 0x000A46C8 File Offset: 0x000A28C8
		private double ReadDouble(string key)
		{
			string text = this[key];
			if (text == null)
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			double num;
			try
			{
				num = double.Parse(text);
			}
			catch
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			return num;
		}

		// Token: 0x06003DF6 RID: 15862 RVA: 0x000A470C File Offset: 0x000A290C
		private string ReadString(string key)
		{
			string text = this[key];
			if (text == null)
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			return text;
		}

		// Token: 0x06003DF7 RID: 15863 RVA: 0x000A4720 File Offset: 0x000A2920
		private Version ReadVersion(string key)
		{
			string text = this[key];
			if (text == null)
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			Version version;
			try
			{
				version = new Version(text);
			}
			catch
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			return version;
		}

		// Token: 0x06003DF8 RID: 15864 RVA: 0x000A4764 File Offset: 0x000A2964
		private ArrayList ReadArrayList(string key)
		{
			ArrayList arrayList = (ArrayList)this.capabilities[key];
			if (arrayList == null)
			{
				throw this.CreateCapabilityNotFoundException(key);
			}
			return arrayList;
		}

		// Token: 0x06003DF9 RID: 15865 RVA: 0x000A4782 File Offset: 0x000A2982
		private Exception CreateCapabilityNotFoundException(string key)
		{
			return new ArgumentNullException(string.Format("browscaps.ini does not contain a definition for capability {0} for userAgent {1}", key, this.Browser));
		}

		// Token: 0x06003DFA RID: 15866 RVA: 0x000A479A File Offset: 0x000A299A
		private bool Get(int idx)
		{
			return this.flags.Get(idx);
		}

		// Token: 0x06003DFB RID: 15867 RVA: 0x000A47A8 File Offset: 0x000A29A8
		private void Set(int idx)
		{
			this.flags.Set(idx, true);
		}

		// Token: 0x0400211D RID: 8477
		internal IDictionary capabilities;

		// Token: 0x0400211E RID: 8478
		internal static bool GetConfigCapabilities_called;

		// Token: 0x0400211F RID: 8479
		private IDictionary adapters;

		// Token: 0x04002120 RID: 8480
		private bool canCombineFormsInDeck;

		// Token: 0x04002121 RID: 8481
		private bool canInitiateVoiceCall;

		// Token: 0x04002122 RID: 8482
		private bool canRenderAfterInputOrSelectElement;

		// Token: 0x04002123 RID: 8483
		private bool canRenderEmptySelects;

		// Token: 0x04002124 RID: 8484
		private bool canRenderInputAndSelectElementsTogether;

		// Token: 0x04002125 RID: 8485
		private bool canRenderMixedSelects;

		// Token: 0x04002126 RID: 8486
		private bool canRenderOneventAndPrevElementsTogether;

		// Token: 0x04002127 RID: 8487
		private bool canRenderPostBackCards;

		// Token: 0x04002128 RID: 8488
		private bool canRenderSetvarZeroWithMultiSelectionList;

		// Token: 0x04002129 RID: 8489
		private bool canSendMail;

		// Token: 0x0400212A RID: 8490
		private int defaultSubmitButtonLimit;

		// Token: 0x0400212B RID: 8491
		private int gatewayMajorVersion;

		// Token: 0x0400212C RID: 8492
		private double gatewayMinorVersion;

		// Token: 0x0400212D RID: 8493
		private string gatewayVersion;

		// Token: 0x0400212E RID: 8494
		private bool hasBackButton;

		// Token: 0x0400212F RID: 8495
		private bool hidesRightAlignedMultiselectScrollbars;

		// Token: 0x04002130 RID: 8496
		private string htmlTextWriter;

		// Token: 0x04002131 RID: 8497
		private string inputType;

		// Token: 0x04002132 RID: 8498
		private bool isColor;

		// Token: 0x04002133 RID: 8499
		private bool isMobileDevice;

		// Token: 0x04002134 RID: 8500
		private Version jscriptVersion;

		// Token: 0x04002135 RID: 8501
		private int maximumHrefLength;

		// Token: 0x04002136 RID: 8502
		private int maximumRenderedPageSize;

		// Token: 0x04002137 RID: 8503
		private int maximumSoftkeyLabelLength;

		// Token: 0x04002138 RID: 8504
		private string minorVersionString;

		// Token: 0x04002139 RID: 8505
		private string mobileDeviceManufacturer;

		// Token: 0x0400213A RID: 8506
		private string mobileDeviceModel;

		// Token: 0x0400213B RID: 8507
		private int numberOfSoftkeys;

		// Token: 0x0400213C RID: 8508
		private string preferredImageMime;

		// Token: 0x0400213D RID: 8509
		private string preferredRenderingMime;

		// Token: 0x0400213E RID: 8510
		private string preferredRenderingType;

		// Token: 0x0400213F RID: 8511
		private string preferredRequestEncoding;

		// Token: 0x04002140 RID: 8512
		private string preferredResponseEncoding;

		// Token: 0x04002141 RID: 8513
		private bool rendersBreakBeforeWmlSelectAndInput;

		// Token: 0x04002142 RID: 8514
		private bool rendersBreaksAfterHtmlLists;

		// Token: 0x04002143 RID: 8515
		private bool rendersBreaksAfterWmlAnchor;

		// Token: 0x04002144 RID: 8516
		private bool rendersBreaksAfterWmlInput;

		// Token: 0x04002145 RID: 8517
		private bool rendersWmlDoAcceptsInline;

		// Token: 0x04002146 RID: 8518
		private bool rendersWmlSelectsAsMenuCards;

		// Token: 0x04002147 RID: 8519
		private string requiredMetaTagNameValue;

		// Token: 0x04002148 RID: 8520
		private bool requiresAttributeColonSubstitution;

		// Token: 0x04002149 RID: 8521
		private bool requiresContentTypeMetaTag;

		// Token: 0x0400214A RID: 8522
		private bool requiresControlStateInSession;

		// Token: 0x0400214B RID: 8523
		private bool requiresDBCSCharacter;

		// Token: 0x0400214C RID: 8524
		private bool requiresHtmlAdaptiveErrorReporting;

		// Token: 0x0400214D RID: 8525
		private bool requiresLeadingPageBreak;

		// Token: 0x0400214E RID: 8526
		private bool requiresNoBreakInFormatting;

		// Token: 0x0400214F RID: 8527
		private bool requiresOutputOptimization;

		// Token: 0x04002150 RID: 8528
		private bool requiresPhoneNumbersAsPlainText;

		// Token: 0x04002151 RID: 8529
		private bool requiresSpecialViewStateEncoding;

		// Token: 0x04002152 RID: 8530
		private bool requiresUniqueFilePathSuffix;

		// Token: 0x04002153 RID: 8531
		private bool requiresUniqueHtmlCheckboxNames;

		// Token: 0x04002154 RID: 8532
		private bool requiresUniqueHtmlInputNames;

		// Token: 0x04002155 RID: 8533
		private bool requiresUrlEncodedPostfieldValues;

		// Token: 0x04002156 RID: 8534
		private int screenBitDepth;

		// Token: 0x04002157 RID: 8535
		private int screenCharactersHeight;

		// Token: 0x04002158 RID: 8536
		private int screenCharactersWidth;

		// Token: 0x04002159 RID: 8537
		private int screenPixelsHeight;

		// Token: 0x0400215A RID: 8538
		private int screenPixelsWidth;

		// Token: 0x0400215B RID: 8539
		private bool supportsAccesskeyAttribute;

		// Token: 0x0400215C RID: 8540
		private bool supportsBodyColor;

		// Token: 0x0400215D RID: 8541
		private bool supportsBold;

		// Token: 0x0400215E RID: 8542
		private bool supportsCacheControlMetaTag;

		// Token: 0x0400215F RID: 8543
		private bool supportsCallback;

		// Token: 0x04002160 RID: 8544
		private bool supportsCss;

		// Token: 0x04002161 RID: 8545
		private bool supportsDivAlign;

		// Token: 0x04002162 RID: 8546
		private bool supportsDivNoWrap;

		// Token: 0x04002163 RID: 8547
		private bool supportsEmptyStringInCookieValue;

		// Token: 0x04002164 RID: 8548
		private bool supportsFontColor;

		// Token: 0x04002165 RID: 8549
		private bool supportsFontName;

		// Token: 0x04002166 RID: 8550
		private bool supportsFontSize;

		// Token: 0x04002167 RID: 8551
		private bool supportsImageSubmit;

		// Token: 0x04002168 RID: 8552
		private bool supportsIModeSymbols;

		// Token: 0x04002169 RID: 8553
		private bool supportsInputIStyle;

		// Token: 0x0400216A RID: 8554
		private bool supportsInputMode;

		// Token: 0x0400216B RID: 8555
		private bool supportsItalic;

		// Token: 0x0400216C RID: 8556
		private bool supportsJPhoneMultiMediaAttributes;

		// Token: 0x0400216D RID: 8557
		private bool supportsJPhoneSymbols;

		// Token: 0x0400216E RID: 8558
		private bool supportsQueryStringInFormAction;

		// Token: 0x0400216F RID: 8559
		private bool supportsRedirectWithCookie;

		// Token: 0x04002170 RID: 8560
		private bool supportsSelectMultiple;

		// Token: 0x04002171 RID: 8561
		private bool supportsUncheck;

		// Token: 0x04002172 RID: 8562
		private bool supportsXmlHttp;

		// Token: 0x04002173 RID: 8563
		private bool useOptimizedCacheKey;

		// Token: 0x04002174 RID: 8564
		private static HttpCapabilitiesProvider _provider = new HttpCapabilitiesDefaultProvider();

		// Token: 0x04002175 RID: 8565
		private const int HaveActiveXControls = 1;

		// Token: 0x04002176 RID: 8566
		private const int HaveAdapters = 2;

		// Token: 0x04002177 RID: 8567
		private const int HaveAOL = 3;

		// Token: 0x04002178 RID: 8568
		private const int HaveBackGroundSounds = 4;

		// Token: 0x04002179 RID: 8569
		private const int HaveBeta = 5;

		// Token: 0x0400217A RID: 8570
		private const int HaveBrowser = 6;

		// Token: 0x0400217B RID: 8571
		private const int HaveBrowsers = 7;

		// Token: 0x0400217C RID: 8572
		private const int HaveCanCombineFormsInDeck = 8;

		// Token: 0x0400217D RID: 8573
		private const int HaveCanInitiateVoiceCall = 9;

		// Token: 0x0400217E RID: 8574
		private const int HaveCanRenderAfterInputOrSelectElement = 10;

		// Token: 0x0400217F RID: 8575
		private const int HaveCanRenderEmptySelects = 11;

		// Token: 0x04002180 RID: 8576
		private const int HaveCanRenderInputAndSelectElementsTogether = 12;

		// Token: 0x04002181 RID: 8577
		private const int HaveCanRenderMixedSelects = 13;

		// Token: 0x04002182 RID: 8578
		private const int HaveCanRenderOneventAndPrevElementsTogether = 14;

		// Token: 0x04002183 RID: 8579
		private const int HaveCanRenderPostBackCards = 15;

		// Token: 0x04002184 RID: 8580
		private const int HaveCanRenderSetvarZeroWithMultiSelectionList = 16;

		// Token: 0x04002185 RID: 8581
		private const int HaveCanSendMail = 17;

		// Token: 0x04002186 RID: 8582
		private const int HaveCDF = 18;

		// Token: 0x04002187 RID: 8583
		private const int HaveCookies = 20;

		// Token: 0x04002188 RID: 8584
		private const int HaveCrawler = 21;

		// Token: 0x04002189 RID: 8585
		private const int HaveDefaultSubmitButtonLimit = 22;

		// Token: 0x0400218A RID: 8586
		private const int HaveEcmaScriptVersion = 23;

		// Token: 0x0400218B RID: 8587
		private const int HaveFrames = 24;

		// Token: 0x0400218C RID: 8588
		private const int HaveGatewayMajorVersion = 25;

		// Token: 0x0400218D RID: 8589
		private const int HaveGatewayMinorVersion = 26;

		// Token: 0x0400218E RID: 8590
		private const int HaveGatewayVersion = 27;

		// Token: 0x0400218F RID: 8591
		private const int HaveHasBackButton = 28;

		// Token: 0x04002190 RID: 8592
		private const int HaveHidesRightAlignedMultiselectScrollbars = 29;

		// Token: 0x04002191 RID: 8593
		private const int HaveHtmlTextWriter = 30;

		// Token: 0x04002192 RID: 8594
		private const int HaveId = 31;

		// Token: 0x04002193 RID: 8595
		private const int HaveInputType = 32;

		// Token: 0x04002194 RID: 8596
		private const int HaveIsColor = 33;

		// Token: 0x04002195 RID: 8597
		private const int HaveIsMobileDevice = 34;

		// Token: 0x04002196 RID: 8598
		private const int HaveJavaApplets = 35;

		// Token: 0x04002197 RID: 8599
		private const int HaveJavaScript = 36;

		// Token: 0x04002198 RID: 8600
		private const int HaveJScriptVersion = 37;

		// Token: 0x04002199 RID: 8601
		private const int HaveMajorVersion = 38;

		// Token: 0x0400219A RID: 8602
		private const int HaveMaximumHrefLength = 39;

		// Token: 0x0400219B RID: 8603
		private const int HaveMaximumRenderedPageSize = 40;

		// Token: 0x0400219C RID: 8604
		private const int HaveMaximumSoftkeyLabelLength = 41;

		// Token: 0x0400219D RID: 8605
		private const int HaveMinorVersion = 42;

		// Token: 0x0400219E RID: 8606
		private const int HaveMinorVersionString = 43;

		// Token: 0x0400219F RID: 8607
		private const int HaveMobileDeviceManufacturer = 44;

		// Token: 0x040021A0 RID: 8608
		private const int HaveMobileDeviceModel = 45;

		// Token: 0x040021A1 RID: 8609
		private const int HaveMSDomVersion = 46;

		// Token: 0x040021A2 RID: 8610
		private const int HaveNumberOfSoftkeys = 47;

		// Token: 0x040021A3 RID: 8611
		private const int HavePlatform = 48;

		// Token: 0x040021A4 RID: 8612
		private const int HavePreferredImageMime = 49;

		// Token: 0x040021A5 RID: 8613
		private const int HavePreferredRenderingMime = 50;

		// Token: 0x040021A6 RID: 8614
		private const int HavePreferredRenderingType = 51;

		// Token: 0x040021A7 RID: 8615
		private const int HavePreferredRequestEncoding = 52;

		// Token: 0x040021A8 RID: 8616
		private const int HavePreferredResponseEncoding = 53;

		// Token: 0x040021A9 RID: 8617
		private const int HaveRendersBreakBeforeWmlSelectAndInput = 54;

		// Token: 0x040021AA RID: 8618
		private const int HaveRendersBreaksAfterHtmlLists = 55;

		// Token: 0x040021AB RID: 8619
		private const int HaveRendersBreaksAfterWmlAnchor = 56;

		// Token: 0x040021AC RID: 8620
		private const int HaveRendersBreaksAfterWmlInput = 57;

		// Token: 0x040021AD RID: 8621
		private const int HaveRendersWmlDoAcceptsInline = 58;

		// Token: 0x040021AE RID: 8622
		private const int HaveRendersWmlSelectsAsMenuCards = 59;

		// Token: 0x040021AF RID: 8623
		private const int HaveRequiredMetaTagNameValue = 60;

		// Token: 0x040021B0 RID: 8624
		private const int HaveRequiresAttributeColonSubstitution = 61;

		// Token: 0x040021B1 RID: 8625
		private const int HaveRequiresContentTypeMetaTag = 62;

		// Token: 0x040021B2 RID: 8626
		private const int HaveRequiresControlStateInSession = 63;

		// Token: 0x040021B3 RID: 8627
		private const int HaveRequiresDBCSCharacter = 64;

		// Token: 0x040021B4 RID: 8628
		private const int HaveRequiresHtmlAdaptiveErrorReporting = 65;

		// Token: 0x040021B5 RID: 8629
		private const int HaveRequiresLeadingPageBreak = 66;

		// Token: 0x040021B6 RID: 8630
		private const int HaveRequiresNoBreakInFormatting = 67;

		// Token: 0x040021B7 RID: 8631
		private const int HaveRequiresOutputOptimization = 68;

		// Token: 0x040021B8 RID: 8632
		private const int HaveRequiresPhoneNumbersAsPlainText = 69;

		// Token: 0x040021B9 RID: 8633
		private const int HaveRequiresSpecialViewStateEncoding = 70;

		// Token: 0x040021BA RID: 8634
		private const int HaveRequiresUniqueFilePathSuffix = 71;

		// Token: 0x040021BB RID: 8635
		private const int HaveRequiresUniqueHtmlCheckboxNames = 72;

		// Token: 0x040021BC RID: 8636
		private const int HaveRequiresUniqueHtmlInputNames = 73;

		// Token: 0x040021BD RID: 8637
		private const int HaveRequiresUrlEncodedPostfieldValues = 74;

		// Token: 0x040021BE RID: 8638
		private const int HaveScreenBitDepth = 75;

		// Token: 0x040021BF RID: 8639
		private const int HaveScreenCharactersHeight = 76;

		// Token: 0x040021C0 RID: 8640
		private const int HaveScreenCharactersWidth = 77;

		// Token: 0x040021C1 RID: 8641
		private const int HaveScreenPixelsHeight = 78;

		// Token: 0x040021C2 RID: 8642
		private const int HaveScreenPixelsWidth = 79;

		// Token: 0x040021C3 RID: 8643
		private const int HaveSupportsAccesskeyAttribute = 80;

		// Token: 0x040021C4 RID: 8644
		private const int HaveSupportsBodyColor = 81;

		// Token: 0x040021C5 RID: 8645
		private const int HaveSupportsBold = 82;

		// Token: 0x040021C6 RID: 8646
		private const int HaveSupportsCacheControlMetaTag = 83;

		// Token: 0x040021C7 RID: 8647
		private const int HaveSupportsCallback = 84;

		// Token: 0x040021C8 RID: 8648
		private const int HaveSupportsCss = 85;

		// Token: 0x040021C9 RID: 8649
		private const int HaveSupportsDivAlign = 86;

		// Token: 0x040021CA RID: 8650
		private const int HaveSupportsDivNoWrap = 87;

		// Token: 0x040021CB RID: 8651
		private const int HaveSupportsEmptyStringInCookieValue = 88;

		// Token: 0x040021CC RID: 8652
		private const int HaveSupportsFontColor = 89;

		// Token: 0x040021CD RID: 8653
		private const int HaveSupportsFontName = 90;

		// Token: 0x040021CE RID: 8654
		private const int HaveSupportsFontSize = 91;

		// Token: 0x040021CF RID: 8655
		private const int HaveSupportsImageSubmit = 92;

		// Token: 0x040021D0 RID: 8656
		private const int HaveSupportsIModeSymbols = 93;

		// Token: 0x040021D1 RID: 8657
		private const int HaveSupportsInputIStyle = 94;

		// Token: 0x040021D2 RID: 8658
		private const int HaveSupportsInputMode = 95;

		// Token: 0x040021D3 RID: 8659
		private const int HaveSupportsItalic = 96;

		// Token: 0x040021D4 RID: 8660
		private const int HaveSupportsJPhoneMultiMediaAttributes = 97;

		// Token: 0x040021D5 RID: 8661
		private const int HaveSupportsJPhoneSymbols = 98;

		// Token: 0x040021D6 RID: 8662
		private const int HaveSupportsQueryStringInFormAction = 99;

		// Token: 0x040021D7 RID: 8663
		private const int HaveSupportsRedirectWithCookie = 100;

		// Token: 0x040021D8 RID: 8664
		private const int HaveSupportsSelectMultiple = 101;

		// Token: 0x040021D9 RID: 8665
		private const int HaveSupportsUncheck = 102;

		// Token: 0x040021DA RID: 8666
		private const int HaveSupportsXmlHttp = 103;

		// Token: 0x040021DB RID: 8667
		private const int HaveTables = 104;

		// Token: 0x040021DC RID: 8668
		private const int HaveTagWriter = 105;

		// Token: 0x040021DD RID: 8669
		private const int HaveType = 106;

		// Token: 0x040021DE RID: 8670
		private const int HaveUseOptimizedCacheKey = 107;

		// Token: 0x040021DF RID: 8671
		private const int HaveVBScript = 108;

		// Token: 0x040021E0 RID: 8672
		private const int HaveVersion = 109;

		// Token: 0x040021E1 RID: 8673
		private const int HaveW3CDomVersion = 110;

		// Token: 0x040021E2 RID: 8674
		private const int HaveWin16 = 111;

		// Token: 0x040021E3 RID: 8675
		private const int HaveWin32 = 112;

		// Token: 0x040021E4 RID: 8676
		private const int LastHaveFlag = 113;

		// Token: 0x040021E5 RID: 8677
		private BitArray flags = new BitArray(113);

		// Token: 0x040021E6 RID: 8678
		private bool activeXControls;

		// Token: 0x040021E7 RID: 8679
		private bool aol;

		// Token: 0x040021E8 RID: 8680
		private bool backgroundSounds;

		// Token: 0x040021E9 RID: 8681
		private bool beta;

		// Token: 0x040021EA RID: 8682
		private string browser;

		// Token: 0x040021EB RID: 8683
		private bool cdf;

		// Token: 0x040021EC RID: 8684
		private Version clrVersion;

		// Token: 0x040021ED RID: 8685
		private bool cookies;

		// Token: 0x040021EE RID: 8686
		private bool crawler;

		// Token: 0x040021EF RID: 8687
		private Version ecmaScriptVersion;

		// Token: 0x040021F0 RID: 8688
		private bool frames;

		// Token: 0x040021F1 RID: 8689
		private bool javaApplets;

		// Token: 0x040021F2 RID: 8690
		private bool javaScript;

		// Token: 0x040021F3 RID: 8691
		private int majorVersion;

		// Token: 0x040021F4 RID: 8692
		private double minorVersion;

		// Token: 0x040021F5 RID: 8693
		private Version msDomVersion;

		// Token: 0x040021F6 RID: 8694
		private string platform;

		// Token: 0x040021F7 RID: 8695
		private bool tables;

		// Token: 0x040021F8 RID: 8696
		private Type tagWriter;

		// Token: 0x040021F9 RID: 8697
		private bool vbscript;

		// Token: 0x040021FA RID: 8698
		private string version;

		// Token: 0x040021FB RID: 8699
		private Version w3CDomVersion;

		// Token: 0x040021FC RID: 8700
		private bool win16;

		// Token: 0x040021FD RID: 8701
		private bool win32;

		// Token: 0x040021FE RID: 8702
		private Version[] clrVersions;

		// Token: 0x040021FF RID: 8703
		internal string useragent;

		// Token: 0x04002200 RID: 8704
		private ArrayList browsers;
	}
}
