using System;

namespace System.Web.Configuration
{
	/// <summary>Specifies which encryption methods can be used.</summary>
	// Token: 0x0200056C RID: 1388
	public enum MachineKeyCompatibilityMode
	{
		/// <summary>Use the encryption methods that were implemented in .NET Framework versions earlier than version 2.0 Service Pack 2. Initialization vectors (IVs) are used for all encryption operations except for storing encrypted passwords in the ASP.NET membership database.</summary>
		// Token: 0x04002025 RID: 8229
		Framework20SP1,
		/// <summary>Use the stronger encryption methods that are available in .NET Framework version 2.0 SP2 and later versions. Initialization vectors (IVs) are used for all encryption operations.</summary>
		// Token: 0x04002026 RID: 8230
		Framework20SP2,
		/// <summary>Use encryption methods that are available in .NET Framework version 4.5 and later versions. Compared to the encryption methods that are used for <see cref="F:System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1" /> and <see cref="F:System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2" />, the ciphertext that is generated by the default cryptographic routines is slightly smaller and is more resilient against certain classes of theoretical attacks. They also integrate with Windows 8 directory key management in order to get required cryptographic keys. This option also enables you to specify custom cryptographic routines by writing a class that derives from <see cref="T:System.Security.Cryptography.DataProtector" /> and specifying the class name in the <see cref="P:System.Web.Configuration.MachineKeySection.DataProtectorType" /> property.The following configuration requirements apply to this option:1. If the <see cref="P:System.Web.Configuration.MachineKeySection.DataProtectorType" /> property has a value, the <see cref="P:System.Web.Configuration.MachineKeySection.ApplicationName" /> property must also have a value.2. The <see cref="P:System.Web.Configuration.MachineKeySection.Validation" /> attribute must specify a system-defined validation algorithm (such as MD5, SHA1, HMACSHA256, HMACSHA384, or HMACSHA512) or a custom validation algorithm in a class that derives from the <see cref="T:System.Security.Cryptography.KeyedHashAlgorithm" /> class. The values AES and 3DES are not validation algorithms.When you specify this option, forms authentication tickets are always both encrypted and signed, regardless of the value specified for the <see cref="P:System.Web.Configuration.FormsAuthenticationConfiguration.Protection" /> property. View state is also both encrypted and signed if a page's <see cref="P:System.Web.UI.Page.EnableViewStateMac" /> property is <paramref name="true" /> or the <see cref="P:System.Web.UI.Page.ViewStateEncryptionMode" /> property is <see cref="F:System.Web.UI.ViewStateEncryptionMode.Always" />.</summary>
		// Token: 0x04002027 RID: 8231
		Framework45
	}
}
