using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Web.Configuration;
using System.Web.Hosting;
using System.Web.Util;
using Unity;

namespace System.Web.Compilation
{
	/// <summary>Defines a set of properties and methods for generating source code within the ASP.NET build environment. This class is abstract.</summary>
	// Token: 0x02000643 RID: 1603
	public abstract class BuildProvider
	{
		// Token: 0x17001582 RID: 5506
		// (get) Token: 0x060044DC RID: 17628 RVA: 0x000BCBE8 File Offset: 0x000BADE8
		private CompilationSection CompilationConfig
		{
			get
			{
				if (this.compilationSection == null)
				{
					this.compilationSection = WebConfigurationManager.GetWebApplicationSection("system.web/compilation") as CompilationSection;
				}
				return this.compilationSection;
			}
		}

		// Token: 0x17001583 RID: 5507
		// (get) Token: 0x060044DD RID: 17629 RVA: 0x000BCC0D File Offset: 0x000BAE0D
		internal virtual string LanguageName
		{
			get
			{
				return this.CompilationConfig.DefaultLanguage;
			}
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Web.Compilation.BuildProvider" /> class. </summary>
		// Token: 0x060044DE RID: 17630 RVA: 0x000BCC1A File Offset: 0x000BAE1A
		protected BuildProvider()
		{
			this.ref_assemblies = new ArrayList();
		}

		// Token: 0x060044DF RID: 17631 RVA: 0x000BCC2D File Offset: 0x000BAE2D
		internal void SetVirtualPath(VirtualPath virtualPath)
		{
			this.vpath = virtualPath;
		}

		// Token: 0x060044E0 RID: 17632 RVA: 0x0000393A File Offset: 0x00001B3A
		internal virtual void GenerateCode()
		{
		}

		// Token: 0x060044E1 RID: 17633 RVA: 0x00003BEA File Offset: 0x00001DEA
		internal virtual IDictionary<string, bool> ExtractDependencies()
		{
			return null;
		}

		/// <summary>Generates source code for the virtual path of the build provider, and adds the source code to a specified assembly builder.</summary>
		/// <param name="assemblyBuilder">The assembly builder that references the source code generated by the build provider.</param>
		// Token: 0x060044E2 RID: 17634 RVA: 0x0000393A File Offset: 0x00001B3A
		public virtual void GenerateCode(AssemblyBuilder assemblyBuilder)
		{
		}

		/// <summary>Generates a string to be persisted in the compiled assembly.</summary>
		/// <returns>A string to be persisted in the build environment, or null if the <see cref="T:System.Web.Compilation.BuildProvider" /> instance does not implement <see cref="M:System.Web.Compilation.BuildProvider.GetCustomString(System.CodeDom.Compiler.CompilerResults)" />.</returns>
		/// <param name="results">The compilation results for the build provider's virtual path.</param>
		// Token: 0x060044E3 RID: 17635 RVA: 0x00003BEA File Offset: 0x00001DEA
		public virtual string GetCustomString(CompilerResults results)
		{
			return null;
		}

		/// <summary>Returns the compiler settings for the default language in the application.</summary>
		/// <returns>A <see cref="T:System.Web.Compilation.CompilerType" /> that represents the compiler settings for the default language in the application. The base class returns the default compiler based on the application configuration file.</returns>
		// Token: 0x060044E4 RID: 17636 RVA: 0x000BCC36 File Offset: 0x000BAE36
		protected CompilerType GetDefaultCompilerType()
		{
			return BuildManager.GetDefaultCompilerTypeForLanguage(this.CompilationConfig.DefaultLanguage, this.CompilationConfig);
		}

		/// <summary>Returns the compiler settings for the build provider based on the specified language.</summary>
		/// <returns>A <see cref="T:System.Web.Compilation.CompilerType" /> that represents the compiler settings for the build provider based on the specified language. The base class returns the default compiler settings for the language based on the application configuration file.</returns>
		/// <param name="language">A code language name.</param>
		/// <exception cref="T:System.ArgumentNullException">
		///   <paramref name="language" /> is null.</exception>
		/// <exception cref="T:System.Web.HttpException">
		///   <paramref name="language" /> does not match a configured compiler for the build provider.</exception>
		// Token: 0x060044E5 RID: 17637 RVA: 0x000BCC4E File Offset: 0x000BAE4E
		protected CompilerType GetDefaultCompilerTypeForLanguage(string language)
		{
			return BuildManager.GetDefaultCompilerTypeForLanguage(language, null);
		}

		/// <summary>Returns a type generated by the build provider from the virtual path.</summary>
		/// <returns>The type that is generated by the build provider for the virtual path. The base class returns null.</returns>
		/// <param name="results">The compilation results for the build provider's virtual path.</param>
		// Token: 0x060044E6 RID: 17638 RVA: 0x00003BEA File Offset: 0x00001DEA
		public virtual Type GetGeneratedType(CompilerResults results)
		{
			return null;
		}

		/// <summary>Returns a value indicating actions required when a virtual path is built.</summary>
		/// <returns>A <see cref="T:System.Web.Compilation.BuildProviderResultFlags" /> value indicating actions required after the virtual path is built within the ASP.NET build environment.</returns>
		/// <param name="results">The compilation results for the build provider's virtual path.</param>
		// Token: 0x060044E7 RID: 17639 RVA: 0x00008A69 File Offset: 0x00006C69
		public virtual BuildProviderResultFlags GetResultFlags(CompilerResults results)
		{
			return BuildProviderResultFlags.Default;
		}

		/// <summary>Opens a text reader for reading from the virtual path of the current build provider object.</summary>
		/// <returns>An open <see cref="T:System.IO.TextReader" /> that can be used to read the contents of the <see cref="P:System.Web.Compilation.BuildProvider.VirtualPath" />.</returns>
		// Token: 0x060044E8 RID: 17640 RVA: 0x000BCC57 File Offset: 0x000BAE57
		protected TextReader OpenReader()
		{
			return this.OpenReader(this.VirtualPath);
		}

		/// <summary>Opens a text reader for reading from a specified virtual path.</summary>
		/// <returns>An open <see cref="T:System.IO.TextReader" /> that can be used to read the contents of the specified virtual path.</returns>
		/// <param name="virtualPath">The virtual path to read.</param>
		// Token: 0x060044E9 RID: 17641 RVA: 0x000BCC65 File Offset: 0x000BAE65
		protected TextReader OpenReader(string virtualPath)
		{
			return new StreamReader(this.OpenStream(virtualPath), WebEncoding.FileEncoding);
		}

		/// <summary>Opens a stream for reading the virtual path of the current build provider object.</summary>
		/// <returns>An open <see cref="T:System.IO.Stream" /> that can be used to read the contents of the <see cref="P:System.Web.Compilation.BuildProvider.VirtualPath" />.</returns>
		// Token: 0x060044EA RID: 17642 RVA: 0x000BCC78 File Offset: 0x000BAE78
		protected Stream OpenStream()
		{
			return this.OpenStream(this.VirtualPath);
		}

		/// <summary>Opens a stream for reading from a specified virtual path.</summary>
		/// <returns>An open <see cref="T:System.IO.Stream" /> that can be used to read the contents of the specified virtual path.</returns>
		/// <param name="virtualPath">The virtual path to read.</param>
		// Token: 0x060044EB RID: 17643 RVA: 0x000BCC86 File Offset: 0x000BAE86
		protected Stream OpenStream(string virtualPath)
		{
			return VirtualPathProvider.OpenFile(virtualPath);
		}

		/// <summary>Registers a build provider.</summary>
		/// <param name="extension">The file-name extension that the build provider is for.</param>
		/// <param name="providerType">The build provider class.</param>
		// Token: 0x060044EC RID: 17644 RVA: 0x000BCC90 File Offset: 0x000BAE90
		public static void RegisterBuildProvider(string extension, Type providerType)
		{
			if (string.IsNullOrEmpty(extension))
			{
				throw new ArgumentException("The string parameter 'extension' cannot be null or empty.", "extension");
			}
			if (providerType == null)
			{
				throw new ArgumentNullException("providerType");
			}
			if (!typeof(BuildProvider).IsAssignableFrom(providerType))
			{
				throw new ArgumentException("The parameter 'providerType' is invalid", "providerType");
			}
			BuildManager.AssertPreStartMethodsRunning();
			if (BuildProvider.registeredBuildProviderTypes == null)
			{
				BuildProvider.registeredBuildProviderTypes = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);
			}
			BuildProvider.registeredBuildProviderTypes[extension] = providerType;
		}

		// Token: 0x060044ED RID: 17645 RVA: 0x000BCD14 File Offset: 0x000BAF14
		internal static Type GetProviderTypeForExtension(string extension)
		{
			if (string.IsNullOrEmpty(extension))
			{
				return null;
			}
			Type type = null;
			if (BuildProvider.registeredBuildProviderTypes == null || !BuildProvider.registeredBuildProviderTypes.TryGetValue(extension, out type) || type == null)
			{
				CompilationSection compilationSection = WebConfigurationManager.GetSection("system.web/compilation") as CompilationSection;
				BuildProviderCollection buildProviderCollection = ((compilationSection != null) ? compilationSection.BuildProviders : null);
				BuildProvider buildProvider = ((buildProviderCollection != null) ? buildProviderCollection[extension] : null);
				if (buildProvider != null)
				{
					type = HttpApplication.LoadType(buildProvider.Type);
				}
			}
			return type;
		}

		// Token: 0x060044EE RID: 17646 RVA: 0x000BCD88 File Offset: 0x000BAF88
		internal static BuildProvider GetProviderInstanceForExtension(string extension)
		{
			Type providerTypeForExtension = BuildProvider.GetProviderTypeForExtension(extension);
			if (providerTypeForExtension == null)
			{
				return null;
			}
			return Activator.CreateInstance(providerTypeForExtension, null) as BuildProvider;
		}

		/// <summary>Represents the compiler type used by a build provider to generate source code for a custom file type.</summary>
		/// <returns>A read-only <see cref="T:System.Web.Compilation.CompilerType" /> representing the code generator, code compiler, and compiler settings used to build source code for the virtual path. The base class returns null.</returns>
		// Token: 0x17001584 RID: 5508
		// (get) Token: 0x060044EF RID: 17647 RVA: 0x00003BEA File Offset: 0x00001DEA
		public virtual CompilerType CodeCompilerType
		{
			get
			{
				return null;
			}
		}

		/// <summary>Represents the assemblies to compile with the source generated by the build provider.</summary>
		/// <returns>A read-only collection of assemblies that can be referenced by the source code generated by the build provider.</returns>
		// Token: 0x17001585 RID: 5509
		// (get) Token: 0x060044F0 RID: 17648 RVA: 0x000BCDB3 File Offset: 0x000BAFB3
		protected ICollection ReferencedAssemblies
		{
			get
			{
				return this.ref_assemblies;
			}
		}

		/// <summary>Represents the file to be built by this build provider implementation.</summary>
		/// <returns>A read-only string that specifies the virtual path of a file to be compiled by this build provider.</returns>
		// Token: 0x17001586 RID: 5510
		// (get) Token: 0x060044F1 RID: 17649 RVA: 0x000BCDBB File Offset: 0x000BAFBB
		protected internal string VirtualPath
		{
			get
			{
				if (this.vpath == null)
				{
					return null;
				}
				return this.vpath.Absolute;
			}
		}

		// Token: 0x17001587 RID: 5511
		// (get) Token: 0x060044F2 RID: 17650 RVA: 0x000BCDD2 File Offset: 0x000BAFD2
		internal VirtualPath VirtualPathInternal
		{
			get
			{
				return this.vpath;
			}
		}

		/// <summary>Represents a collection of virtual paths that must be built before the build provider generates code.</summary>
		/// <returns>A read-only collection of strings, representing the virtual paths that this instance of the build provider is dependent on.</returns>
		// Token: 0x17001588 RID: 5512
		// (get) Token: 0x060044F3 RID: 17651 RVA: 0x000BCDDA File Offset: 0x000BAFDA
		public virtual ICollection VirtualPathDependencies
		{
			get
			{
				if (this.vpath_deps == null)
				{
					this.vpath_deps = new OneNullCollection();
				}
				return this.vpath_deps;
			}
		}

		// Token: 0x17001589 RID: 5513
		// (get) Token: 0x060044F4 RID: 17652 RVA: 0x00003BEA File Offset: 0x00001DEA
		internal virtual CodeCompileUnit CodeUnit
		{
			get
			{
				return null;
			}
		}

		/// <summary>Represents the container for the generated CodeDOM graph.</summary>
		/// <returns>The container for the CodeDOM graph that is generated by the <see cref="T:System.Web.Compilation.BuildProvider" /> instance.</returns>
		/// <param name="linePragmasTable">When this method returns, contains a dictionary that contains all associated line numbers and line pragmas of the source code. This parameter is passed uninitialized. </param>
		// Token: 0x060044F5 RID: 17653 RVA: 0x0000E80B File Offset: 0x0000CA0B
		protected internal virtual CodeCompileUnit GetCodeCompileUnit(out IDictionary linePragmasTable)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return null;
		}

		/// <summary>When overridden in a derived class, enables you to review compiler error messages so that you can modify them to provide more information.</summary>
		/// <param name="results">Compiler results.</param>
		// Token: 0x060044F6 RID: 17654 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public virtual void ProcessCompileErrors(CompilerResults results)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x040024BC RID: 9404
		private static Dictionary<string, Type> registeredBuildProviderTypes;

		// Token: 0x040024BD RID: 9405
		private ArrayList ref_assemblies;

		// Token: 0x040024BE RID: 9406
		private ICollection vpath_deps;

		// Token: 0x040024BF RID: 9407
		private CompilationSection compilationSection;

		// Token: 0x040024C0 RID: 9408
		private VirtualPath vpath;
	}
}
