using System;
using System.CodeDom;
using System.Collections;
using System.Web.UI;
using Unity;

namespace System.Web.Compilation
{
	/// <summary>Allows the compilation process to be customized or controlled.</summary>
	// Token: 0x02000782 RID: 1922
	public abstract class ControlBuilderInterceptor
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Web.Compilation.ControlBuilderInterceptor" /> class.</summary>
		// Token: 0x06004E1C RID: 19996 RVA: 0x0000B3E4 File Offset: 0x000095E4
		protected ControlBuilderInterceptor()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Called after the <see cref="P:System.Web.UI.ControlBuilder" /> has completed generating code.</summary>
		/// <param name="controlBuilder">The control builder instance.</param>
		/// <param name="codeCompileUnit">A <see cref="T:System.CodeDom.CodeCompileUnit" /> object that is generated by the compilation.</param>
		/// <param name="baseType">The type declaration of the code behind class or derived type.</param>
		/// <param name="derivedType">The type declaration of top level markup element.</param>
		/// <param name="buildMethod">The method with the necessary code to create the control and set the control's various properties, events, fields.</param>
		/// <param name="dataBindingMethod">The method with code to evaluate data binding expressions within the control.</param>
		/// <param name="additionalState">The additional state which can be used to store and retrieve data within several methods of  the <see cref="T:System.Web.Compilation.ControlBuilderInterceptor" /> class.</param>
		// Token: 0x06004E1D RID: 19997 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public virtual void OnProcessGeneratedCode(ControlBuilder controlBuilder, CodeCompileUnit codeCompileUnit, CodeTypeDeclaration baseType, CodeTypeDeclaration derivedType, CodeMemberMethod buildMethod, CodeMemberMethod dataBindingMethod, IDictionary additionalState)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Called before the <see cref="P:System.Web.UI.ControlBuilder" /> of an element in the markup is initialized.</summary>
		/// <param name="controlBuilder">The control builder which is about to be initialized.</param>
		/// <param name="parser">The <see cref="T:System.Web.UI.TemplateParser" /> which was used to parse the markup.</param>
		/// <param name="parentBuilder">The parent control builder.</param>
		/// <param name="type">The type of the control that this builder will create.</param>
		/// <param name="tagName">The name of the tag to be built.</param>
		/// <param name="id">The ID of the element in the markup.</param>
		/// <param name="attributes">The list of attributes of the element in the markup.</param>
		/// <param name="additionalState">The additional state which can be used to store and retrieve data within several methods of  the <see cref="T:System.Web.Compilation.ControlBuilderInterceptor" /> class.</param>
		// Token: 0x06004E1E RID: 19998 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public virtual void PreControlBuilderInit(ControlBuilder controlBuilder, TemplateParser parser, ControlBuilder parentBuilder, Type type, string tagName, string id, IDictionary attributes, IDictionary additionalState)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}
	}
}
