using System;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Security.Permissions;

namespace System.Web.UI.WebControls
{
	/// <summary>Represents an automatically generated field in a data-bound control. This class cannot be inherited.</summary>
	// Token: 0x02000333 RID: 819
	[EditorBrowsable(EditorBrowsableState.Never)]
	[AspNetHostingPermission(SecurityAction.LinkDemand, Level = AspNetHostingPermissionLevel.Minimal)]
	[AspNetHostingPermission(SecurityAction.InheritanceDemand, Level = AspNetHostingPermissionLevel.Minimal)]
	public sealed class AutoGeneratedField : BoundField
	{
		// Token: 0x06001C64 RID: 7268 RVA: 0x00046FCF File Offset: 0x000451CF
		internal AutoGeneratedField()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> class with the specified data field.</summary>
		/// <param name="dataField">The name of the data field to bind to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" />.</param>
		// Token: 0x06001C65 RID: 7269 RVA: 0x00046FE7 File Offset: 0x000451E7
		public AutoGeneratedField(string dataField)
		{
			this.DataField = dataField;
		}

		// Token: 0x06001C66 RID: 7270 RVA: 0x00047008 File Offset: 0x00045208
		internal AutoGeneratedField(AutoGeneratedFieldProperties fieldProperties)
		{
			this.DataField = fieldProperties.DataField;
			this.DataType = fieldProperties.Type;
			this.SortExpression = fieldProperties.Name;
			this.HeaderText = fieldProperties.Name;
			this.ReadOnly = fieldProperties.IsReadOnly;
		}

		/// <summary>Gets or sets the data type of the values displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object.</summary>
		/// <returns>A <see cref="T:System.Type" /> that represents the data type of the value displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object. The default is <see cref="T:System.String" />.</returns>
		// Token: 0x170008B8 RID: 2232
		// (get) Token: 0x06001C67 RID: 7271 RVA: 0x00047067 File Offset: 0x00045267
		// (set) Token: 0x06001C68 RID: 7272 RVA: 0x0004706F File Offset: 0x0004526F
		public Type DataType
		{
			get
			{
				return this.dataType;
			}
			set
			{
				this.dataType = value;
			}
		}

		/// <summary>Gets or sets a value indicating whether empty string ("") values are converted to null when the field values are retrieved from the data source.</summary>
		/// <returns>Always returns true.</returns>
		/// <exception cref="T:System.NotSupportedException">An attempt is made to set this property.</exception>
		// Token: 0x170008B9 RID: 2233
		// (get) Token: 0x06001C69 RID: 7273 RVA: 0x00008B66 File Offset: 0x00006D66
		// (set) Token: 0x06001C6A RID: 7274 RVA: 0x00003A01 File Offset: 0x00001C01
		public override bool ConvertEmptyStringToNull
		{
			get
			{
				return true;
			}
			set
			{
				throw new NotSupportedException();
			}
		}

		/// <summary>Gets or sets the string that specifies the format in which the alternate text for each image in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object is rendered.</summary>
		/// <returns>Always returns an empty string ("").</returns>
		/// <exception cref="T:System.NotSupportedException">An attempt is made to set this property.</exception>
		// Token: 0x170008BA RID: 2234
		// (get) Token: 0x06001C6B RID: 7275 RVA: 0x0000EE9B File Offset: 0x0000D09B
		// (set) Token: 0x06001C6C RID: 7276 RVA: 0x00003A01 File Offset: 0x00001C01
		public override string DataFormatString
		{
			get
			{
				return string.Empty;
			}
			set
			{
				throw new NotSupportedException();
			}
		}

		/// <summary>Gets or sets a value indicating whether the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object is visible in insert mode.</summary>
		/// <returns>Always returns true.</returns>
		/// <exception cref="T:System.NotSupportedException">An attempt is made to set this property.</exception>
		// Token: 0x170008BB RID: 2235
		// (get) Token: 0x06001C6D RID: 7277 RVA: 0x00008B66 File Offset: 0x00006D66
		// (set) Token: 0x06001C6E RID: 7278 RVA: 0x00003A01 File Offset: 0x00001C01
		public override bool InsertVisible
		{
			get
			{
				return true;
			}
			set
			{
				throw new NotSupportedException();
			}
		}

		/// <summary>Fills the specified <see cref="T:System.Collections.Specialized.IOrderedDictionary" /> object with the values from the specified <see cref="T:System.Web.UI.WebControls.DataControlFieldCell" /> object.</summary>
		/// <param name="dictionary">An <see cref="T:System.Collections.Specialized.IOrderedDictionary" /> used to store the values of the specified cell.</param>
		/// <param name="cell">The <see cref="T:System.Web.UI.WebControls.DataControlFieldCell" /> that contains the values to retrieve.</param>
		/// <param name="rowState">One of the <see cref="T:System.Web.UI.WebControls.DataControlRowState" /> values.</param>
		/// <param name="includeReadOnly">The value true includes only the values of read-only fields; otherwise, false.</param>
		// Token: 0x06001C6F RID: 7279 RVA: 0x00047078 File Offset: 0x00045278
		[global::System.MonoTODO("Support other data types")]
		public override void ExtractValuesFromCell(IOrderedDictionary dictionary, DataControlFieldCell cell, DataControlRowState rowState, bool includeReadOnly)
		{
			if (this.dataType == typeof(bool))
			{
				if (base.IsEditable(rowState) || includeReadOnly)
				{
					CheckBox checkBox = (CheckBox)cell.Controls[0];
					dictionary[this.DataField] = checkBox.Checked;
					return;
				}
			}
			else
			{
				base.ExtractValuesFromCell(dictionary, cell, rowState, includeReadOnly);
			}
		}

		// Token: 0x06001C70 RID: 7280 RVA: 0x000470E0 File Offset: 0x000452E0
		[global::System.MonoTODO("Support other data types")]
		protected override void InitializeDataCell(DataControlFieldCell cell, DataControlRowState rowState)
		{
			if (this.dataType == typeof(bool))
			{
				bool flag = base.IsEditable(rowState);
				CheckBox checkBox = new CheckBox();
				checkBox.Enabled = flag;
				checkBox.ToolTip = this.HeaderText;
				cell.Controls.Add(checkBox);
				return;
			}
			base.InitializeDataCell(cell, rowState);
		}

		// Token: 0x06001C71 RID: 7281 RVA: 0x0004713C File Offset: 0x0004533C
		[global::System.MonoTODO("Support other data types")]
		protected override void OnDataBindField(object sender, EventArgs e)
		{
			DataControlFieldCell dataControlFieldCell = (DataControlFieldCell)sender;
			if (this.dataType == typeof(bool))
			{
				CheckBox checkBox = (CheckBox)dataControlFieldCell.Controls[0];
				object value = this.GetValue(dataControlFieldCell.BindingContainer);
				if (value != null && value != DBNull.Value)
				{
					checkBox.Checked = (bool)value;
				}
				else if (string.IsNullOrEmpty(this.DataField))
				{
					checkBox.Visible = false;
					return;
				}
				if (!checkBox.Visible)
				{
					checkBox.Visible = true;
					return;
				}
			}
			else
			{
				base.OnDataBindField(sender, e);
			}
		}

		/// <summary>Determines whether the controls contained in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object support callbacks.</summary>
		// Token: 0x06001C72 RID: 7282 RVA: 0x0000393A File Offset: 0x00001B3A
		public override void ValidateSupportsCallback()
		{
		}

		// Token: 0x06001C73 RID: 7283 RVA: 0x000471CC File Offset: 0x000453CC
		protected override DataControlField CreateField()
		{
			return new AutoGeneratedField();
		}

		// Token: 0x06001C74 RID: 7284 RVA: 0x000471D3 File Offset: 0x000453D3
		protected override void CopyProperties(DataControlField newField)
		{
			base.CopyProperties(newField);
			((AutoGeneratedField)newField).DataType = this.DataType;
		}

		// Token: 0x06001C75 RID: 7285 RVA: 0x000471ED File Offset: 0x000453ED
		protected override object GetDesignTimeValue()
		{
			return base.GetDesignTimeValue();
		}

		// Token: 0x040017F2 RID: 6130
		private Type dataType = typeof(string);
	}
}
