using System;
using System.Security.Permissions;

namespace System.Web.UI.WebControls
{
	/// <summary>Represents the properties of an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object. This class cannot be inherited.</summary>
	// Token: 0x02000334 RID: 820
	[AspNetHostingPermission(SecurityAction.LinkDemand, Level = AspNetHostingPermissionLevel.Minimal)]
	[AspNetHostingPermission(SecurityAction.InheritanceDemand, Level = AspNetHostingPermissionLevel.Minimal)]
	public sealed class AutoGeneratedFieldProperties : IStateManager
	{
		/// <summary>Gets or sets the name of the field bound to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object.</summary>
		/// <returns>The name of the field bound to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" />. The default is an empty string (""), which indicates that this property is not set.</returns>
		// Token: 0x170008BC RID: 2236
		// (get) Token: 0x06001C76 RID: 7286 RVA: 0x000471F5 File Offset: 0x000453F5
		// (set) Token: 0x06001C77 RID: 7287 RVA: 0x0004720C File Offset: 0x0004540C
		public string DataField
		{
			get
			{
				return this.ViewState.GetString("DataField", string.Empty);
			}
			set
			{
				this.ViewState["DataField"] = value;
			}
		}

		/// <summary>Gets or sets a value indicating whether the values displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object can be modified in edit mode.</summary>
		/// <returns>true to indicate that the values are read-only; otherwise, false. The default is false.</returns>
		// Token: 0x170008BD RID: 2237
		// (get) Token: 0x06001C78 RID: 7288 RVA: 0x0004721F File Offset: 0x0004541F
		// (set) Token: 0x06001C79 RID: 7289 RVA: 0x00047232 File Offset: 0x00045432
		public bool IsReadOnly
		{
			get
			{
				return this.ViewState.GetBool("IsReadOnly", false);
			}
			set
			{
				this.ViewState["IsReadOnly"] = value;
			}
		}

		/// <summary>Gets or sets the name of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object.</summary>
		/// <returns>The name of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object. The default is an empty string (""), which indicates that this property is not set.</returns>
		// Token: 0x170008BE RID: 2238
		// (get) Token: 0x06001C7A RID: 7290 RVA: 0x0004724A File Offset: 0x0004544A
		// (set) Token: 0x06001C7B RID: 7291 RVA: 0x00047261 File Offset: 0x00045461
		public string Name
		{
			get
			{
				return this.ViewState.GetString("Name", string.Empty);
			}
			set
			{
				this.ViewState["Name"] = value;
			}
		}

		/// <summary>Gets or sets the data type of the value displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
		/// <returns>A <see cref="T:System.Type" /> that represents the data type of the value displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object. The default is null, which indicates that this property is not set.</returns>
		// Token: 0x170008BF RID: 2239
		// (get) Token: 0x06001C7C RID: 7292 RVA: 0x00047274 File Offset: 0x00045474
		// (set) Token: 0x06001C7D RID: 7293 RVA: 0x0004729D File Offset: 0x0004549D
		public Type Type
		{
			get
			{
				object obj = this.ViewState["Type"];
				if (obj != null)
				{
					return (Type)obj;
				}
				return null;
			}
			set
			{
				this.ViewState["Type"] = value;
			}
		}

		/// <summary>Loads the previously saved view state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
		/// <param name="state">An <see cref="T:System.Object" /> that represents the state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" />.</param>
		// Token: 0x06001C7E RID: 7294 RVA: 0x000472B0 File Offset: 0x000454B0
		void IStateManager.LoadViewState(object state)
		{
			this.ViewState.LoadViewState(state);
		}

		/// <summary>Saves the current view state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
		/// <returns>An <see cref="T:System.Object" /> that contains the saved state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</returns>
		// Token: 0x06001C7F RID: 7295 RVA: 0x000472BE File Offset: 0x000454BE
		object IStateManager.SaveViewState()
		{
			return this.ViewState.SaveViewState();
		}

		/// <summary>Marks the starting point at which to begin tracking and saving view-state changes to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
		// Token: 0x06001C80 RID: 7296 RVA: 0x000472CB File Offset: 0x000454CB
		void IStateManager.TrackViewState()
		{
			this.ViewState.TrackViewState();
		}

		/// <summary>Gets a value indicating whether the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object is tracking its view-state changes.</summary>
		/// <returns>true to indicate that the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object is tracking its view-state changes; otherwise, false.</returns>
		// Token: 0x170008C0 RID: 2240
		// (get) Token: 0x06001C81 RID: 7297 RVA: 0x000472D8 File Offset: 0x000454D8
		bool IStateManager.IsTrackingViewState
		{
			get
			{
				return this.ViewState.IsTrackingViewState;
			}
		}

		// Token: 0x040017F3 RID: 6131
		private StateBag ViewState = new StateBag();
	}
}
