using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Unity;

namespace System.Web.UI.WebControls
{
	/// <summary>Represents a base class for classes that automatically generate fields for data-bound controls that use ASP.NET Dynamic Data features.</summary>
	// Token: 0x02000797 RID: 1943
	public abstract class AutoFieldsGenerator : IAutoFieldGenerator, IStateManager
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.AutoFieldsGenerator" /> class.</summary>
		// Token: 0x06004E7C RID: 20092 RVA: 0x0000B3E4 File Offset: 0x000095E4
		protected AutoFieldsGenerator()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Returns a list of the properties of an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object.</summary>
		/// <returns>The list of properties.</returns>
		// Token: 0x170017DA RID: 6106
		// (get) Token: 0x06004E7D RID: 20093 RVA: 0x0000FAB7 File Offset: 0x0000DCB7
		protected internal List<AutoGeneratedFieldProperties> AutoGeneratedFieldProperties
		{
			get
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
				return 0;
			}
		}

		/// <summary>Gets or sets a value that indicates whether enumeration fields should be generated by this <see cref="T:System.Web.UI.WebControls.AutoFieldsGenerator" /> instance.</summary>
		/// <returns>true if fields should be generated; otherwise, false.</returns>
		// Token: 0x170017DB RID: 6107
		// (get) Token: 0x06004E7E RID: 20094 RVA: 0x000CB43C File Offset: 0x000C963C
		// (set) Token: 0x06004E7F RID: 20095 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public bool? AutoGenerateEnumFields
		{
			[CompilerGenerated]
			get
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
				return null;
			}
			[CompilerGenerated]
			set
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
			}
		}

		/// <summary>Gets a value that indicates whether view state changes are being tracked.</summary>
		/// <returns>true if view state is being tracked; otherwise, false.</returns>
		// Token: 0x170017DC RID: 6108
		// (get) Token: 0x06004E80 RID: 20096 RVA: 0x000CB458 File Offset: 0x000C9658
		protected bool IsTrackingViewState
		{
			get
			{
				global::Unity.ThrowStub.ThrowNotSupportedException();
				return default(bool);
			}
		}

		// Token: 0x06004E81 RID: 20097 RVA: 0x000CB474 File Offset: 0x000C9674
		bool IStateManager.get_IsTrackingViewState()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return default(bool);
		}

		/// <summary>Creates one or more autogenerated fields using the specified collection of field properties. </summary>
		/// <returns>The autogenerated field.</returns>
		/// <param name="fieldProperties">The list of properties to use when creating the field.</param>
		// Token: 0x06004E82 RID: 20098 RVA: 0x0000E80B File Offset: 0x0000CA0B
		protected virtual AutoGeneratedField CreateAutoGeneratedFieldFromFieldProperties(AutoGeneratedFieldProperties fieldProperties)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return null;
		}

		/// <summary>When implemented in a derived class, creates autogenerated fields based on the current data item.</summary>
		/// <returns>The autogenerated fields. </returns>
		/// <param name="dataItem">The current data item.</param>
		/// <param name="control">The data-bound control that will contain the autogenerated fields.</param>
		// Token: 0x06004E83 RID: 20099
		public abstract List<AutoGeneratedField> CreateAutoGeneratedFields(object dataItem, Control control);

		/// <summary>Creates <see cref="T:System.Web.DynamicData.DynamicField" /> objects based on metadata information for the table.</summary>
		/// <returns>A collection of <see cref="T:System.Web.DynamicData.DynamicField" /> objects.</returns>
		/// <param name="control">The data-bound control that will contain the autogenerated fields.</param>
		// Token: 0x06004E84 RID: 20100 RVA: 0x0000E80B File Offset: 0x0000CA0B
		public virtual ICollection GenerateFields(Control control)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return null;
		}

		/// <summary>Loads the state that was saved previously using the <see cref="M:System.Web.UI.WebControls.AutoFieldsGenerator.SaveViewState" /> method.</summary>
		/// <param name="savedState">The control state to restore.</param>
		// Token: 0x06004E85 RID: 20101 RVA: 0x0000B3E4 File Offset: 0x000095E4
		protected virtual void LoadViewState(object savedState)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Saves the changes to the class's state.</summary>
		/// <returns>The saved view state.</returns>
		// Token: 0x06004E86 RID: 20102 RVA: 0x0000E80B File Offset: 0x0000CA0B
		protected virtual object SaveViewState()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return null;
		}

		/// <summary>Loads the state that was saved previously using the <see cref="M:System.Web.UI.WebControls.AutoFieldsGenerator.SaveViewState" /> method.</summary>
		/// <param name="savedState">The view state changes saved previously.</param>
		// Token: 0x06004E87 RID: 20103 RVA: 0x0000B3E4 File Offset: 0x000095E4
		void IStateManager.LoadViewState(object savedState)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Saves the changes to a class's state.</summary>
		/// <returns>The view state changes.</returns>
		// Token: 0x06004E88 RID: 20104 RVA: 0x0000E80B File Offset: 0x0000CA0B
		object IStateManager.SaveViewState()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return null;
		}

		/// <summary>Instructs the class to track changes to its view state.</summary>
		// Token: 0x06004E89 RID: 20105 RVA: 0x0000B3E4 File Offset: 0x000095E4
		void IStateManager.TrackViewState()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Instructs the class to track changes to its view state.</summary>
		// Token: 0x06004E8A RID: 20106 RVA: 0x0000B3E4 File Offset: 0x000095E4
		protected virtual void TrackViewState()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}
	}
}
