using System;
using System.Collections.Generic;
using Unity;

namespace System.Web.UI.WebControls
{
	/// <summary>Provides a way to automatically generate fields that use ASP.NET Dynamic Data features for the <see cref="T:System.Web.UI.WebControls.DetailsView" /> control.</summary>
	// Token: 0x02000798 RID: 1944
	public class DetailsViewRowsGenerator : AutoFieldsGenerator
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.DetailsViewRowsGenerator" /> class. </summary>
		// Token: 0x06004E8B RID: 20107 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public DetailsViewRowsGenerator()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Generates fields based on the current data item.</summary>
		/// <returns>The list of generated fields.</returns>
		/// <param name="dataItem">The current data item.</param>
		/// <param name="control">The current control.</param>
		// Token: 0x06004E8C RID: 20108 RVA: 0x0000FAB7 File Offset: 0x0000DCB7
		public override List<AutoGeneratedField> CreateAutoGeneratedFields(object dataItem, Control control)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return 0;
		}
	}
}
