using System;
using System.Collections.Generic;
using Unity;

namespace System.Web.UI.WebControls
{
	/// <summary>Provides a way to automatically generate fields that use ASP.NET Dynamic Data features for the <see cref="T:System.Web.UI.WebControls.GridView" /> control.</summary>
	// Token: 0x02000799 RID: 1945
	public class GridViewColumnsGenerator : AutoFieldsGenerator
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.GridViewColumnsGenerator" /> class.</summary>
		// Token: 0x06004E8D RID: 20109 RVA: 0x0000B3E4 File Offset: 0x000095E4
		public GridViewColumnsGenerator()
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
		}

		/// <summary>Generates fields based on the current data item.</summary>
		/// <returns>The list of generated fields.</returns>
		/// <param name="dataObject">The current data item.</param>
		/// <param name="control">The current control.</param>
		// Token: 0x06004E8E RID: 20110 RVA: 0x0000FAB7 File Offset: 0x0000DCB7
		public override List<AutoGeneratedField> CreateAutoGeneratedFields(object dataObject, Control control)
		{
			global::Unity.ThrowStub.ThrowNotSupportedException();
			return 0;
		}
	}
}
