using System;
using System.Collections.Specialized;
using System.Configuration;
using System.Configuration.Provider;
using System.Data;
using System.Data.Common;
using System.Security.Cryptography;
using System.Text;
using System.Web.Configuration;
using System.Web.Hosting;
using System.Web.Properties;
using Mono.Data.Sqlite;

namespace System.Web.Security
{
	// Token: 0x020004D1 RID: 1233
	internal class SqliteMembershipProvider : MembershipProvider
	{
		// Token: 0x060037FE RID: 14334 RVA: 0x000940D9 File Offset: 0x000922D9
		private DbParameter AddParameter(DbCommand command, string parameterName, object parameterValue)
		{
			return this.AddParameter(command, parameterName, ParameterDirection.Input, parameterValue);
		}

		// Token: 0x060037FF RID: 14335 RVA: 0x000940E8 File Offset: 0x000922E8
		private DbParameter AddParameter(DbCommand command, string parameterName, ParameterDirection direction, object parameterValue)
		{
			DbParameter dbParameter = command.CreateParameter();
			dbParameter.ParameterName = parameterName;
			dbParameter.Value = parameterValue;
			dbParameter.Direction = direction;
			command.Parameters.Add(dbParameter);
			return dbParameter;
		}

		// Token: 0x06003800 RID: 14336 RVA: 0x00094120 File Offset: 0x00092320
		public override void Initialize(string name, NameValueCollection config)
		{
			if (config == null)
			{
				throw new ArgumentNullException("Config", Resources.ErrArgumentNull);
			}
			if (string.IsNullOrEmpty(name))
			{
				name = Resources.MembershipProviderDefaultName;
			}
			if (string.IsNullOrEmpty(config["description"]))
			{
				config.Remove("description");
				config.Add("description", Resources.MembershipProviderDefaultDescription);
			}
			base.Initialize(name, config);
			this.m_ApplicationName = this.GetConfigValue(config["applicationName"], HostingEnvironment.ApplicationVirtualPath);
			this.m_MaxInvalidPasswordAttempts = Convert.ToInt32(this.GetConfigValue(config["maxInvalidPasswordAttempts"], "5"));
			this.m_PasswordAttemptWindow = Convert.ToInt32(this.GetConfigValue(config["passwordAttemptWindow"], "10"));
			this.m_MinRequiredNonAlphanumericCharacters = Convert.ToInt32(this.GetConfigValue(config["minRequiredNonAlphanumericCharacters"], "1"));
			this.m_MinRequiredPasswordLength = Convert.ToInt32(this.GetConfigValue(config["minRequiredPasswordLength"], "7"));
			this.m_PasswordStrengthRegularExpression = Convert.ToString(this.GetConfigValue(config["passwordStrengthRegularExpression"], ""));
			this.m_EnablePasswordReset = Convert.ToBoolean(this.GetConfigValue(config["enablePasswordReset"], "true"));
			this.m_EnablePasswordRetrieval = Convert.ToBoolean(this.GetConfigValue(config["enablePasswordRetrieval"], "true"));
			this.m_RequiresQuestionAndAnswer = Convert.ToBoolean(this.GetConfigValue(config["requiresQuestionAndAnswer"], "false"));
			this.m_RequiresUniqueEmail = Convert.ToBoolean(this.GetConfigValue(config["requiresUniqueEmail"], "true"));
			string configValue = this.GetConfigValue(config["passwordFormat"], "Hashed");
			if (!(configValue == "Hashed"))
			{
				if (!(configValue == "Encrypted"))
				{
					if (!(configValue == "Clear"))
					{
						throw new ProviderException(Resources.ErrPwFormatNotSupported);
					}
					this.m_PasswordFormat = MembershipPasswordFormat.Clear;
				}
				else
				{
					this.m_PasswordFormat = MembershipPasswordFormat.Encrypted;
				}
			}
			else
			{
				this.m_PasswordFormat = MembershipPasswordFormat.Hashed;
			}
			string text = config["connectionStringName"];
			if (string.IsNullOrEmpty(text))
			{
				throw new ArgumentOutOfRangeException("ConnectionStringName", Resources.ErrArgumentNullOrEmpty);
			}
			ConnectionStringSettings connectionStringSettings = ConfigurationManager.ConnectionStrings[text];
			if (connectionStringSettings == null || string.IsNullOrEmpty(connectionStringSettings.ConnectionString.Trim()))
			{
				throw new ProviderException(Resources.ErrConnectionStringNullOrEmpty);
			}
			this.m_ConnectionString = connectionStringSettings.ConnectionString;
			this.m_MachineKey = (MachineKeySection)WebConfigurationManager.GetSection("system.web/machineKey", null);
			if (!this.m_PasswordFormat.Equals(MembershipPasswordFormat.Clear))
			{
				if (this.m_MachineKey == null)
				{
					throw new ArgumentNullException("system.web/machineKey", Resources.ErrArgumentNull);
				}
				if (this.m_MachineKey.ValidationKey.Contains("AutoGenerate"))
				{
					this.machineKeyIsAutoGenerated = true;
					if (this.m_PasswordFormat.Equals(MembershipPasswordFormat.Encrypted))
					{
						throw new ProviderException(Resources.ErrAutoGeneratedKeyNotSupported);
					}
				}
			}
		}

		// Token: 0x17001186 RID: 4486
		// (get) Token: 0x06003801 RID: 14337 RVA: 0x00094414 File Offset: 0x00092614
		// (set) Token: 0x06003802 RID: 14338 RVA: 0x0009441C File Offset: 0x0009261C
		public override string ApplicationName
		{
			get
			{
				return this.m_ApplicationName;
			}
			set
			{
				this.m_ApplicationName = value;
			}
		}

		// Token: 0x17001187 RID: 4487
		// (get) Token: 0x06003803 RID: 14339 RVA: 0x00094425 File Offset: 0x00092625
		public override bool EnablePasswordReset
		{
			get
			{
				return this.m_EnablePasswordReset;
			}
		}

		// Token: 0x17001188 RID: 4488
		// (get) Token: 0x06003804 RID: 14340 RVA: 0x0009442D File Offset: 0x0009262D
		public override bool EnablePasswordRetrieval
		{
			get
			{
				return this.m_EnablePasswordRetrieval;
			}
		}

		// Token: 0x17001189 RID: 4489
		// (get) Token: 0x06003805 RID: 14341 RVA: 0x00094435 File Offset: 0x00092635
		public override bool RequiresQuestionAndAnswer
		{
			get
			{
				return this.m_RequiresQuestionAndAnswer;
			}
		}

		// Token: 0x1700118A RID: 4490
		// (get) Token: 0x06003806 RID: 14342 RVA: 0x0009443D File Offset: 0x0009263D
		public override bool RequiresUniqueEmail
		{
			get
			{
				return this.m_RequiresUniqueEmail;
			}
		}

		// Token: 0x1700118B RID: 4491
		// (get) Token: 0x06003807 RID: 14343 RVA: 0x00094445 File Offset: 0x00092645
		public override int MaxInvalidPasswordAttempts
		{
			get
			{
				return this.m_MaxInvalidPasswordAttempts;
			}
		}

		// Token: 0x1700118C RID: 4492
		// (get) Token: 0x06003808 RID: 14344 RVA: 0x0009444D File Offset: 0x0009264D
		public override int PasswordAttemptWindow
		{
			get
			{
				return this.m_PasswordAttemptWindow;
			}
		}

		// Token: 0x1700118D RID: 4493
		// (get) Token: 0x06003809 RID: 14345 RVA: 0x00094455 File Offset: 0x00092655
		public override MembershipPasswordFormat PasswordFormat
		{
			get
			{
				return this.m_PasswordFormat;
			}
		}

		// Token: 0x1700118E RID: 4494
		// (get) Token: 0x0600380A RID: 14346 RVA: 0x0009445D File Offset: 0x0009265D
		public override int MinRequiredNonAlphanumericCharacters
		{
			get
			{
				return this.m_MinRequiredNonAlphanumericCharacters;
			}
		}

		// Token: 0x1700118F RID: 4495
		// (get) Token: 0x0600380B RID: 14347 RVA: 0x00094465 File Offset: 0x00092665
		public override int MinRequiredPasswordLength
		{
			get
			{
				return this.m_MinRequiredPasswordLength;
			}
		}

		// Token: 0x17001190 RID: 4496
		// (get) Token: 0x0600380C RID: 14348 RVA: 0x0009446D File Offset: 0x0009266D
		public override string PasswordStrengthRegularExpression
		{
			get
			{
				return this.m_PasswordStrengthRegularExpression;
			}
		}

		// Token: 0x0600380D RID: 14349 RVA: 0x00094478 File Offset: 0x00092678
		public override bool ChangePassword(string username, string oldPassword, string newPassword)
		{
			if (!this.ValidateUser(username, oldPassword))
			{
				return false;
			}
			ValidatePasswordEventArgs validatePasswordEventArgs = new ValidatePasswordEventArgs(username, newPassword, true);
			this.OnValidatingPassword(validatePasswordEventArgs);
			if (!validatePasswordEventArgs.Cancel)
			{
				int num = 0;
				using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
				{
					using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
					{
						sqliteCommand.CommandText = string.Format("UPDATE \"{0}\" SET \"Password\" = @Password, \"LastPasswordChangedDate\" = @LastPasswordChangedDate WHERE \"Username\" = @Username AND  \"ApplicationName\" = @ApplicationName", "Users");
						this.AddParameter(sqliteCommand, "@Password", this.EncodePassword(newPassword));
						this.AddParameter(sqliteCommand, "@LastPasswordChangedDate", DateTime.Now);
						this.AddParameter(sqliteCommand, "@Username", username);
						this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
						try
						{
							sqliteConnection.Open();
							sqliteCommand.Prepare();
							num = sqliteCommand.ExecuteNonQuery();
						}
						catch (SqliteException)
						{
							throw new ProviderException(Resources.ErrOperationAborted);
						}
						finally
						{
							if (sqliteConnection != null)
							{
								sqliteConnection.Close();
							}
						}
					}
				}
				return num > 0;
			}
			if (validatePasswordEventArgs.FailureInformation != null)
			{
				throw validatePasswordEventArgs.FailureInformation;
			}
			throw new MembershipPasswordException(Resources.ErrPasswordChangeCanceled);
		}

		// Token: 0x0600380E RID: 14350 RVA: 0x000945B4 File Offset: 0x000927B4
		public override bool ChangePasswordQuestionAndAnswer(string username, string password, string newPasswordQuestion, string newPasswordAnswer)
		{
			if (!this.ValidateUser(username, password))
			{
				return false;
			}
			int num = 0;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("UPDATE \"{0}\" SET \"PasswordQuestion\" = @PasswordQuestion, \"PasswordAnswer\" = @PasswordAnswer WHERE \"Username\" = @Username AND  \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@PasswordQuestion", newPasswordQuestion);
					this.AddParameter(sqliteCommand, "@PasswordAnswer", this.EncodePassword(newPasswordAnswer));
					this.AddParameter(sqliteCommand, "@Username", username);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						num = sqliteCommand.ExecuteNonQuery();
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return num > 0;
		}

		// Token: 0x0600380F RID: 14351 RVA: 0x000946B8 File Offset: 0x000928B8
		public override MembershipUser CreateUser(string username, string password, string email, string passwordQuestion, string passwordAnswer, bool isApproved, object providerUserKey, out MembershipCreateStatus status)
		{
			ValidatePasswordEventArgs validatePasswordEventArgs = new ValidatePasswordEventArgs(username, password, true);
			this.OnValidatingPassword(validatePasswordEventArgs);
			if (validatePasswordEventArgs.Cancel)
			{
				status = MembershipCreateStatus.InvalidPassword;
				return null;
			}
			if (this.RequiresUniqueEmail && string.IsNullOrEmpty(email))
			{
				status = MembershipCreateStatus.InvalidEmail;
				return null;
			}
			if (this.RequiresUniqueEmail && !string.IsNullOrEmpty(this.GetUserNameByEmail(email)))
			{
				status = MembershipCreateStatus.DuplicateEmail;
				return null;
			}
			if (this.GetUser(username, false) == null)
			{
				DateTime now = DateTime.Now;
				if (providerUserKey == null)
				{
					providerUserKey = Guid.NewGuid();
				}
				else if (!(providerUserKey is Guid))
				{
					status = MembershipCreateStatus.InvalidProviderUserKey;
					return null;
				}
				using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
				{
					using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
					{
						sqliteCommand.CommandText = string.Format("INSERT INTO \"{0}\" (\"pId\", \"Username\", \"Password\", \"Email\", \"PasswordQuestion\", \"PasswordAnswer\", \"IsApproved\", \"CreationDate\", \"LastPasswordChangedDate\", \"LastActivityDate\", \"ApplicationName\", \"IsLockedOut\", \"LastLockedOutDate\", \"FailedPasswordAttemptCount\", \"FailedPasswordAttemptWindowStart\", \"FailedPasswordAnswerAttemptCount\", \"FailedPasswordAnswerAttemptWindowStart\") Values (@pId, @Username, @Password, @Email, @PasswordQuestion, @PasswordAnswer, @IsApproved, @CreationDate, @LastPasswordChangedDate, @LastActivityDate, @ApplicationName, @IsLockedOut, @LastLockedOutDate, @FailedPasswordAttemptCount, @FailedPasswordAttemptWindowStart, @FailedPasswordAnswerAttemptCount, @FailedPasswordAnswerAttemptWindowStart)", "Users");
						this.AddParameter(sqliteCommand, "@pId", providerUserKey);
						this.AddParameter(sqliteCommand, "@Username", username);
						this.AddParameter(sqliteCommand, "@Password", this.EncodePassword(password));
						this.AddParameter(sqliteCommand, "@Email", email);
						this.AddParameter(sqliteCommand, "@PasswordQuestion", passwordQuestion);
						this.AddParameter(sqliteCommand, "@PasswordAnswer", this.EncodePassword(passwordAnswer));
						this.AddParameter(sqliteCommand, "@IsApproved", isApproved);
						this.AddParameter(sqliteCommand, "@CreationDate", now);
						this.AddParameter(sqliteCommand, "@LastPasswordChangedDate", now);
						this.AddParameter(sqliteCommand, "@LastActivityDate", now);
						this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
						this.AddParameter(sqliteCommand, "@IsLockedOut", false);
						this.AddParameter(sqliteCommand, "@LastLockedOutDate", now);
						this.AddParameter(sqliteCommand, "@FailedPasswordAttemptCount", 0);
						this.AddParameter(sqliteCommand, "@FailedPasswordAttemptWindowStart", now);
						this.AddParameter(sqliteCommand, "@FailedPasswordAnswerAttemptCount", 0);
						this.AddParameter(sqliteCommand, "@FailedPasswordAnswerAttemptWindowStart", now);
						try
						{
							sqliteConnection.Open();
							sqliteCommand.Prepare();
							if (sqliteCommand.ExecuteNonQuery() > 0)
							{
								status = MembershipCreateStatus.Success;
							}
							else
							{
								status = MembershipCreateStatus.UserRejected;
							}
						}
						catch (SqliteException)
						{
							status = MembershipCreateStatus.ProviderError;
							throw new ProviderException(Resources.ErrOperationAborted);
						}
						finally
						{
							if (sqliteConnection != null)
							{
								sqliteConnection.Close();
							}
						}
						return this.GetUser(username, false);
					}
				}
			}
			status = MembershipCreateStatus.DuplicateUserName;
			return null;
		}

		// Token: 0x06003810 RID: 14352 RVA: 0x00094970 File Offset: 0x00092B70
		public override bool DeleteUser(string username, bool deleteAllRelatedData)
		{
			int num = 0;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("DELETE FROM \"{0}\" WHERE \"Username\" = @Username AND  \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Username", username);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						num = sqliteCommand.ExecuteNonQuery();
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return num > 0;
		}

		// Token: 0x06003811 RID: 14353 RVA: 0x00094A44 File Offset: 0x00092C44
		public override MembershipUserCollection FindUsersByEmail(string emailToMatch, int pageIndex, int pageSize, out int totalRecords)
		{
			totalRecords = 0;
			MembershipUserCollection membershipUserCollection = new MembershipUserCollection();
			emailToMatch = emailToMatch.Replace('*', '%');
			emailToMatch = emailToMatch.Replace('?', '_');
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT Count(*) FROM \"{0}\" WHERE \"Email\" LIKE @Email AND  \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Email", emailToMatch);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						int.TryParse(sqliteCommand.ExecuteScalar().ToString(), out totalRecords);
						if (totalRecords <= 0)
						{
							return membershipUserCollection;
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
				using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
				{
					sqliteCommand2.CommandText = string.Format("SELECT \"pId\", \"Username\", \"Email\", \"PasswordQuestion\", \"Comment\", \"IsApproved\", \"IsLockedOut\", \"CreationDate\", \"LastLoginDate\", \"LastActivityDate\", \"LastPasswordChangedDate\", \"LastLockedOutDate\" FROM \"{0}\" WHERE \"Email\" LIKE @Email AND \"ApplicationName\" = @ApplicationName ORDER BY \"Username\" ASC LIMIT @MaxCount OFFSET @StartIndex", "Users");
					this.AddParameter(sqliteCommand2, "@Email", emailToMatch);
					this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
					this.AddParameter(sqliteCommand2, "@MaxCount", pageSize);
					this.AddParameter(sqliteCommand2, "@StartIndex", pageSize * pageIndex);
					try
					{
						sqliteConnection.Open();
						sqliteCommand2.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand2.ExecuteReader())
						{
							while (sqliteDataReader.Read())
							{
								MembershipUser userFromReader = this.GetUserFromReader(sqliteDataReader);
								membershipUserCollection.Add(userFromReader);
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return membershipUserCollection;
		}

		// Token: 0x06003812 RID: 14354 RVA: 0x00094CAC File Offset: 0x00092EAC
		public override MembershipUserCollection FindUsersByName(string usernameToMatch, int pageIndex, int pageSize, out int totalRecords)
		{
			totalRecords = 0;
			MembershipUserCollection membershipUserCollection = new MembershipUserCollection();
			usernameToMatch = usernameToMatch.Replace('*', '%');
			usernameToMatch = usernameToMatch.Replace('?', '_');
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT Count(*) FROM \"{0}\" WHERE \"Username\" LIKE @Username AND  \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Username", usernameToMatch);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						int.TryParse(sqliteCommand.ExecuteScalar().ToString(), out totalRecords);
						if (totalRecords <= 0)
						{
							return membershipUserCollection;
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
				using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
				{
					sqliteCommand2.CommandText = string.Format("SELECT \"pId\", \"Username\", \"Email\", \"PasswordQuestion\", \"Comment\", \"IsApproved\", \"IsLockedOut\", \"CreationDate\", \"LastLoginDate\", \"LastActivityDate\", \"LastPasswordChangedDate\", \"LastLockedOutDate\" FROM \"{0}\" WHERE \"Username\" LIKE @Username AND \"ApplicationName\" = @ApplicationName ORDER BY \"Username\" ASC LIMIT @MaxCount OFFSET @StartIndex", "Users");
					this.AddParameter(sqliteCommand2, "@Username", usernameToMatch);
					this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
					this.AddParameter(sqliteCommand2, "@MaxCount", pageSize);
					this.AddParameter(sqliteCommand2, "@StartIndex", pageSize * pageIndex);
					try
					{
						sqliteConnection.Open();
						sqliteCommand2.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand2.ExecuteReader())
						{
							while (sqliteDataReader.Read())
							{
								MembershipUser userFromReader = this.GetUserFromReader(sqliteDataReader);
								membershipUserCollection.Add(userFromReader);
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return membershipUserCollection;
		}

		// Token: 0x06003813 RID: 14355 RVA: 0x00094F14 File Offset: 0x00093114
		public override MembershipUserCollection GetAllUsers(int pageIndex, int pageSize, out int totalRecords)
		{
			totalRecords = 0;
			MembershipUserCollection membershipUserCollection = new MembershipUserCollection();
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT Count(*) FROM \"{0}\" WHERE \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						int.TryParse(sqliteCommand.ExecuteScalar().ToString(), out totalRecords);
						if (totalRecords <= 0)
						{
							return membershipUserCollection;
						}
					}
					catch (SqliteException ex)
					{
						throw ex;
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
				using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
				{
					sqliteCommand2.CommandText = string.Format("SELECT \"pId\", \"Username\", \"Email\", \"PasswordQuestion\", \"Comment\", \"IsApproved\", \"IsLockedOut\", \"CreationDate\", \"LastLoginDate\", \"LastActivityDate\", \"LastPasswordChangedDate\", \"LastLockedOutDate\" FROM \"{0}\" WHERE \"ApplicationName\" = @ApplicationName ORDER BY \"Username\" ASC LIMIT @MaxCount OFFSET @StartIndex", "Users");
					this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
					this.AddParameter(sqliteCommand2, "@MaxCount", pageSize);
					this.AddParameter(sqliteCommand2, "@StartIndex", pageSize * pageIndex);
					try
					{
						sqliteConnection.Open();
						sqliteCommand2.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand2.ExecuteReader())
						{
							while (sqliteDataReader.Read())
							{
								MembershipUser userFromReader = this.GetUserFromReader(sqliteDataReader);
								membershipUserCollection.Add(userFromReader);
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return membershipUserCollection;
		}

		// Token: 0x06003814 RID: 14356 RVA: 0x00095138 File Offset: 0x00093338
		public override int GetNumberOfUsersOnline()
		{
			int num = 0;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					TimeSpan timeSpan = new TimeSpan(0, Membership.UserIsOnlineTimeWindow, 0);
					DateTime dateTime = DateTime.Now.Subtract(timeSpan);
					sqliteCommand.CommandText = string.Format("SELECT Count(*) FROM \"{0}\" WHERE \"LastActivityDate\" > @CompareTime AND  \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@CompareTime", dateTime);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						num = (int)sqliteCommand.ExecuteScalar();
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return num;
		}

		// Token: 0x06003815 RID: 14357 RVA: 0x00095230 File Offset: 0x00093430
		public override string GetPassword(string username, string answer)
		{
			if (!this.EnablePasswordRetrieval)
			{
				throw new ProviderException(Resources.ErrPasswordRetrievalNotEnabled);
			}
			if (this.PasswordFormat == MembershipPasswordFormat.Hashed)
			{
				throw new ProviderException(Resources.ErrCantRetrieveHashedPw);
			}
			string text2;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT \"Password\", \"PasswordAnswer\", \"IsLockedOut\" FROM \"{0}\" WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Username", username);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand.ExecuteReader())
						{
							if (!sqliteDataReader.HasRows)
							{
								throw new MembershipPasswordException(Resources.ErrUserNotFound);
							}
							sqliteDataReader.Read();
							string text = sqliteDataReader.GetString(0);
							string @string = sqliteDataReader.GetString(1);
							bool boolean = sqliteDataReader.GetBoolean(2);
							sqliteDataReader.Close();
							if (boolean)
							{
								throw new MembershipPasswordException(Resources.ErrUserIsLoggedOut);
							}
							if (this.m_RequiresQuestionAndAnswer && !this.CheckPassword(answer, @string))
							{
								this.UpdateFailureCount(username, SqliteMembershipProvider.FailureType.PasswordAnswer);
								throw new MembershipPasswordException(Resources.ErrIncorrectPasswordAnswer);
							}
							if (this.m_PasswordFormat == MembershipPasswordFormat.Encrypted)
							{
								text = this.UnEncodePassword(text);
							}
							text2 = text;
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return text2;
		}

		// Token: 0x06003816 RID: 14358 RVA: 0x000953B8 File Offset: 0x000935B8
		public override MembershipUser GetUser(string username, bool userIsOnline)
		{
			MembershipUser membershipUser = null;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT \"pId\", \"Username\", \"Email\", \"PasswordQuestion\", \"Comment\", \"IsApproved\", \"IsLockedOut\", \"CreationDate\", \"LastLoginDate\", \"LastActivityDate\", \"LastPasswordChangedDate\", \"LastLockedOutDate\" FROM \"{0}\" WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Username", username);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand.ExecuteReader())
						{
							if (sqliteDataReader.HasRows)
							{
								sqliteDataReader.Read();
								membershipUser = this.GetUserFromReader(sqliteDataReader);
								if (userIsOnline)
								{
									using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
									{
										sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"LastActivityDate\" = @LastActivityDate WHERE \"pId\" = @pId", "Users");
										this.AddParameter(sqliteCommand2, "@LastActivityDate", DateTime.Now);
										this.AddParameter(sqliteCommand2, "@pId", membershipUser.ProviderUserKey);
										sqliteCommand2.Prepare();
										sqliteCommand2.ExecuteNonQuery();
									}
								}
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return membershipUser;
		}

		// Token: 0x06003817 RID: 14359 RVA: 0x0009552C File Offset: 0x0009372C
		public override MembershipUser GetUser(object providerUserKey, bool userIsOnline)
		{
			MembershipUser membershipUser = null;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT \"pId\", \"Username\", \"Email\", \"PasswordQuestion\", \"Comment\", \"IsApproved\", \"IsLockedOut\", \"CreationDate\", \"LastLoginDate\", \"LastActivityDate\", \"LastPasswordChangedDate\", \"LastLockedOutDate\" FROM \"{0}\" WHERE \"pId\" = @pId", "Users");
					this.AddParameter(sqliteCommand, "@pId", providerUserKey);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand.ExecuteReader())
						{
							if (sqliteDataReader.HasRows)
							{
								sqliteDataReader.Read();
								membershipUser = this.GetUserFromReader(sqliteDataReader);
								if (userIsOnline)
								{
									using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
									{
										sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"LastActivityDate\" = @LastActivityDate WHERE \"pId\" = @pId", "Users");
										this.AddParameter(sqliteCommand2, "@LastActivityDate", DateTime.Now);
										this.AddParameter(sqliteCommand2, "@pId", membershipUser.ProviderUserKey);
										sqliteCommand2.Prepare();
										sqliteCommand2.ExecuteNonQuery();
									}
								}
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return membershipUser;
		}

		// Token: 0x06003818 RID: 14360 RVA: 0x0009568C File Offset: 0x0009388C
		public override string GetUserNameByEmail(string email)
		{
			string text = string.Empty;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT \"Username\" FROM \"{0}\" WHERE \"Email\" = @Email AND \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Email", email);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						text = (sqliteCommand.ExecuteScalar() as string) ?? string.Empty;
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return text;
		}

		// Token: 0x06003819 RID: 14361 RVA: 0x0009576C File Offset: 0x0009396C
		public override string ResetPassword(string username, string answer)
		{
			if (!this.m_EnablePasswordReset)
			{
				throw new NotSupportedException(Resources.ErrPasswordResetNotEnabled);
			}
			if (string.IsNullOrEmpty(answer) && this.m_RequiresQuestionAndAnswer)
			{
				this.UpdateFailureCount(username, SqliteMembershipProvider.FailureType.PasswordAnswer);
				throw new ProviderException(Resources.ErrPasswordAnswerRequired);
			}
			string text = Membership.GeneratePassword(8, this.m_MinRequiredNonAlphanumericCharacters);
			ValidatePasswordEventArgs validatePasswordEventArgs = new ValidatePasswordEventArgs(username, text, true);
			this.OnValidatingPassword(validatePasswordEventArgs);
			if (validatePasswordEventArgs.Cancel)
			{
				if (validatePasswordEventArgs.FailureInformation != null)
				{
					throw validatePasswordEventArgs.FailureInformation;
				}
				throw new MembershipPasswordException(Resources.ErrPasswordResetCanceled);
			}
			else
			{
				int num = 0;
				using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
				{
					using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
					{
						sqliteCommand.CommandText = string.Format("SELECT \"PasswordAnswer\", \"IsLockedOut\" FROM \"{0}\" WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
						this.AddParameter(sqliteCommand, "@Username", username);
						this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
						try
						{
							string text2 = string.Empty;
							sqliteConnection.Open();
							sqliteCommand.Prepare();
							using (SqliteDataReader sqliteDataReader = sqliteCommand.ExecuteReader())
							{
								if (!sqliteDataReader.HasRows)
								{
									throw new MembershipPasswordException(Resources.ErrUserNotFound);
								}
								sqliteDataReader.Read();
								text2 = sqliteDataReader.GetString(0);
								bool boolean = sqliteDataReader.GetBoolean(1);
								sqliteDataReader.Close();
								if (boolean)
								{
									throw new MembershipPasswordException(Resources.ErrUserIsLoggedOut);
								}
								if (this.m_RequiresQuestionAndAnswer && !this.CheckPassword(answer, text2))
								{
									this.UpdateFailureCount(username, SqliteMembershipProvider.FailureType.PasswordAnswer);
									throw new MembershipPasswordException(Resources.ErrIncorrectPasswordAnswer);
								}
							}
							using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
							{
								sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"Password\" = @Password, \"LastPasswordChangedDate\" = @LastPasswordChangedDate WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName AND \"IsLockedOut\" = @IsLockedOut", "Users");
								this.AddParameter(sqliteCommand2, "@Password", this.EncodePassword(text));
								this.AddParameter(sqliteCommand2, "@LastPasswordChangedDate", DateTime.Now);
								this.AddParameter(sqliteCommand2, "@Username", username);
								this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
								this.AddParameter(sqliteCommand2, "@IsLockedOut", false);
								sqliteCommand2.Prepare();
								num = sqliteCommand2.ExecuteNonQuery();
							}
						}
						catch (SqliteException)
						{
							throw new ProviderException(Resources.ErrOperationAborted);
						}
						finally
						{
							if (sqliteConnection != null)
							{
								sqliteConnection.Close();
							}
						}
					}
				}
				if (num > 0)
				{
					return text;
				}
				throw new MembershipPasswordException(Resources.ErrPasswordResetAborted);
			}
		}

		// Token: 0x0600381A RID: 14362 RVA: 0x00095A44 File Offset: 0x00093C44
		public override bool UnlockUser(string userName)
		{
			int num = 0;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("UPDATE  \"{0}\" SET \"IsLockedOut\" = @IsLockedOut, \"LastLockedOutDate\" = @LastLockedOutDate WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@IsLockedOut", false);
					this.AddParameter(sqliteCommand, "@LastLockedOutDate", DateTime.Now);
					this.AddParameter(sqliteCommand, "@Username", userName);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						num = sqliteCommand.ExecuteNonQuery();
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
			return num > 0;
		}

		// Token: 0x0600381B RID: 14363 RVA: 0x00095B40 File Offset: 0x00093D40
		public override void UpdateUser(MembershipUser user)
		{
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("UPDATE  \"{0}\" SET \"Email\" = @Email, \"Comment\" = @Comment, \"IsApproved\" = @IsApproved WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Email", user.Email);
					this.AddParameter(sqliteCommand, "@Comment", user.Comment);
					this.AddParameter(sqliteCommand, "@IsApproved", user.IsApproved);
					this.AddParameter(sqliteCommand, "@Username", user.UserName);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						sqliteCommand.ExecuteNonQuery();
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
		}

		// Token: 0x0600381C RID: 14364 RVA: 0x00095C4C File Offset: 0x00093E4C
		public override bool ValidateUser(string username, string password)
		{
			string text = string.Empty;
			bool flag = false;
			bool flag2;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT \"Password\", \"IsApproved\" FROM \"{0}\" WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName AND \"IsLockedOut\" = @IsLockedOut", "Users");
					this.AddParameter(sqliteCommand, "@Username", username);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					this.AddParameter(sqliteCommand, "@IsLockedOut", false);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand.ExecuteReader())
						{
							if (!sqliteDataReader.HasRows)
							{
								return false;
							}
							sqliteDataReader.Read();
							text = sqliteDataReader.GetString(0);
							flag = sqliteDataReader.GetBoolean(1);
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
				if (this.CheckPassword(password, text) && flag)
				{
					using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
					{
						sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"LastLoginDate\" = @LastLoginDate WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
						this.AddParameter(sqliteCommand2, "@LastLoginDate", DateTime.Now);
						this.AddParameter(sqliteCommand2, "@Username", username);
						this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
						try
						{
							sqliteConnection.Open();
							sqliteCommand2.Prepare();
							sqliteCommand2.ExecuteNonQuery();
							return true;
						}
						catch (SqliteException)
						{
							throw new ProviderException(Resources.ErrOperationAborted);
						}
						finally
						{
							if (sqliteConnection != null)
							{
								sqliteConnection.Close();
							}
						}
					}
				}
				flag2 = false;
			}
			return flag2;
		}

		// Token: 0x0600381D RID: 14365 RVA: 0x00095EAC File Offset: 0x000940AC
		private string GetConfigValue(string configValue, string defaultValue)
		{
			if (string.IsNullOrEmpty(configValue))
			{
				return defaultValue;
			}
			return configValue;
		}

		// Token: 0x0600381E RID: 14366 RVA: 0x00095EBC File Offset: 0x000940BC
		private MembershipUser GetUserFromReader(SqliteDataReader reader)
		{
			object value = reader.GetValue(0);
			string @string = reader.GetString(1);
			string text = string.Empty;
			if (!reader.IsDBNull(2))
			{
				text = reader.GetString(2);
			}
			string text2 = string.Empty;
			if (!reader.IsDBNull(3))
			{
				text2 = reader.GetString(3);
			}
			string text3 = string.Empty;
			if (!reader.IsDBNull(4))
			{
				text3 = reader.GetString(4);
			}
			bool boolean = reader.GetBoolean(5);
			bool boolean2 = reader.GetBoolean(6);
			DateTime dateTime = reader.GetDateTime(7);
			DateTime dateTime2 = default(DateTime);
			if (!reader.IsDBNull(8))
			{
				dateTime2 = reader.GetDateTime(8);
			}
			DateTime dateTime3 = reader.GetDateTime(9);
			DateTime dateTime4 = reader.GetDateTime(10);
			DateTime dateTime5 = default(DateTime);
			if (!reader.IsDBNull(11))
			{
				dateTime5 = reader.GetDateTime(11);
			}
			return new MembershipUser(this.Name, @string, value, text, text2, text3, boolean, boolean2, dateTime, dateTime2, dateTime3, dateTime4, dateTime5);
		}

		// Token: 0x0600381F RID: 14367 RVA: 0x00095FA4 File Offset: 0x000941A4
		private bool CheckPassword(string password, string dbpassword)
		{
			string text = password;
			string text2 = dbpassword;
			MembershipPasswordFormat passwordFormat = this.PasswordFormat;
			if (passwordFormat != MembershipPasswordFormat.Hashed)
			{
				if (passwordFormat == MembershipPasswordFormat.Encrypted)
				{
					text2 = this.UnEncodePassword(dbpassword);
				}
			}
			else
			{
				text = this.EncodePassword(password);
			}
			return text.Equals(text2);
		}

		// Token: 0x06003820 RID: 14368 RVA: 0x00095FE4 File Offset: 0x000941E4
		private string EncodePassword(string password)
		{
			if (string.IsNullOrEmpty(password))
			{
				return password;
			}
			string text = password;
			switch (this.PasswordFormat)
			{
			case MembershipPasswordFormat.Clear:
				break;
			case MembershipPasswordFormat.Hashed:
			{
				HMACSHA1 hmacsha = new HMACSHA1();
				if (this.machineKeyIsAutoGenerated)
				{
					hmacsha.Key = MachineKeySection.Config.GetValidationKey();
				}
				else
				{
					hmacsha.Key = this.HexToByte(this.m_MachineKey.ValidationKey);
				}
				text = Convert.ToBase64String(hmacsha.ComputeHash(Encoding.Unicode.GetBytes(password)));
				break;
			}
			case MembershipPasswordFormat.Encrypted:
				text = Convert.ToBase64String(this.EncryptPassword(Encoding.Unicode.GetBytes(password)));
				break;
			default:
				throw new ProviderException(Resources.ErrPwFormatNotSupported);
			}
			return text;
		}

		// Token: 0x06003821 RID: 14369 RVA: 0x00096090 File Offset: 0x00094290
		private string UnEncodePassword(string encodedPassword)
		{
			string text = encodedPassword;
			switch (this.PasswordFormat)
			{
			case MembershipPasswordFormat.Clear:
				break;
			case MembershipPasswordFormat.Hashed:
				throw new ProviderException(Resources.ErrCantDecodeHashedPw);
			case MembershipPasswordFormat.Encrypted:
				text = Encoding.Unicode.GetString(this.DecryptPassword(Convert.FromBase64String(text)));
				break;
			default:
				throw new ProviderException(Resources.ErrPwFormatNotSupported);
			}
			return text;
		}

		// Token: 0x06003822 RID: 14370 RVA: 0x000960EC File Offset: 0x000942EC
		private byte[] HexToByte(string hexString)
		{
			byte[] array = new byte[hexString.Length / 2];
			for (int i = 0; i < array.Length; i++)
			{
				array[i] = Convert.ToByte(hexString.Substring(i * 2, 2), 16);
			}
			return array;
		}

		// Token: 0x06003823 RID: 14371 RVA: 0x0009612C File Offset: 0x0009432C
		private void UpdateFailureCount(string username, SqliteMembershipProvider.FailureType failType)
		{
			DateTime dateTime = default(DateTime);
			int num = 0;
			using (SqliteConnection sqliteConnection = new SqliteConnection(this.m_ConnectionString))
			{
				using (SqliteCommand sqliteCommand = sqliteConnection.CreateCommand())
				{
					sqliteCommand.CommandText = string.Format("SELECT \"FailedPasswordAttemptCount\", \"FailedPasswordAttemptWindowStart\", \"FailedPasswordAnswerAttemptCount\", \"FailedPasswordAnswerAttemptWindowStart\" FROM \"{0}\" WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
					this.AddParameter(sqliteCommand, "@Username", username);
					this.AddParameter(sqliteCommand, "@ApplicationName", this.m_ApplicationName);
					try
					{
						sqliteConnection.Open();
						sqliteCommand.Prepare();
						using (SqliteDataReader sqliteDataReader = sqliteCommand.ExecuteReader())
						{
							if (sqliteDataReader.HasRows)
							{
								sqliteDataReader.Read();
								if (failType.Equals(SqliteMembershipProvider.FailureType.Password))
								{
									num = sqliteDataReader.GetInt32(0);
									dateTime = sqliteDataReader.GetDateTime(1);
								}
								else if (failType.Equals(SqliteMembershipProvider.FailureType.PasswordAnswer))
								{
									num = sqliteDataReader.GetInt32(2);
									dateTime = sqliteDataReader.GetDateTime(3);
								}
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
				using (SqliteCommand sqliteCommand2 = sqliteConnection.CreateCommand())
				{
					DateTime dateTime2 = dateTime.AddMinutes((double)this.m_PasswordAttemptWindow);
					try
					{
						if (num == 0 || DateTime.Now > dateTime2)
						{
							if (failType.Equals(SqliteMembershipProvider.FailureType.Password))
							{
								sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"FailedPasswordAttemptCount\" = @Count, \"FailedPasswordAttemptWindowStart\" = @WindowStart WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
							}
							else if (failType.Equals(SqliteMembershipProvider.FailureType.PasswordAnswer))
							{
								sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"FailedPasswordAnswerAttemptCount\" = @Count, \"FailedPasswordAnswerAttemptWindowStart\" = @WindowStart WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
							}
							this.AddParameter(sqliteCommand2, "@Count", 1);
							this.AddParameter(sqliteCommand2, "@WindowStart", DateTime.Now);
							this.AddParameter(sqliteCommand2, "@Username", username);
							this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
							if (sqliteCommand2.ExecuteNonQuery() < 0)
							{
								throw new ProviderException(Resources.ErrCantUpdateFailtureCountAndWindowStart);
							}
						}
						else
						{
							num++;
							if (num >= this.m_MaxInvalidPasswordAttempts)
							{
								sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"IsLockedOut\" = @IsLockedOut, \"LastLockedOutDate\" = @LastLockedOutDate WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
								this.AddParameter(sqliteCommand2, "@IsLockedOut", true);
								this.AddParameter(sqliteCommand2, "@LastLockedOutDate", DateTime.Now);
								this.AddParameter(sqliteCommand2, "@Username", username);
								this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
								if (sqliteCommand2.ExecuteNonQuery() < 0)
								{
									throw new ProviderException(string.Format(Resources.ErrCantLogoutUser, username));
								}
							}
							else
							{
								if (failType.Equals(SqliteMembershipProvider.FailureType.Password))
								{
									sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"FailedPasswordAttemptCount\" = @Count WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
								}
								else if (failType.Equals(SqliteMembershipProvider.FailureType.PasswordAnswer))
								{
									sqliteCommand2.CommandText = string.Format("UPDATE \"{0}\" SET \"FailedPasswordAnswerAttemptCount\" = @Count WHERE \"Username\" = @Username AND \"ApplicationName\" = @ApplicationName", "Users");
								}
								this.AddParameter(sqliteCommand2, "@Count", num);
								this.AddParameter(sqliteCommand2, "@Username", username);
								this.AddParameter(sqliteCommand2, "@ApplicationName", this.m_ApplicationName);
								if (sqliteCommand2.ExecuteNonQuery() < 0)
								{
									throw new ProviderException(Resources.ErrCantUpdateFailtureCount);
								}
							}
						}
					}
					catch (SqliteException)
					{
						throw new ProviderException(Resources.ErrOperationAborted);
					}
					finally
					{
						if (sqliteConnection != null)
						{
							sqliteConnection.Close();
						}
					}
				}
			}
		}

		// Token: 0x04001E1C RID: 7708
		private const string m_TableName = "Users";

		// Token: 0x04001E1D RID: 7709
		private string m_ConnectionString = string.Empty;

		// Token: 0x04001E1E RID: 7710
		private const int m_NewPasswordLength = 8;

		// Token: 0x04001E1F RID: 7711
		private bool machineKeyIsAutoGenerated;

		// Token: 0x04001E20 RID: 7712
		private MachineKeySection m_MachineKey;

		// Token: 0x04001E21 RID: 7713
		private string m_ApplicationName = string.Empty;

		// Token: 0x04001E22 RID: 7714
		private bool m_EnablePasswordReset;

		// Token: 0x04001E23 RID: 7715
		private bool m_EnablePasswordRetrieval;

		// Token: 0x04001E24 RID: 7716
		private bool m_RequiresQuestionAndAnswer;

		// Token: 0x04001E25 RID: 7717
		private bool m_RequiresUniqueEmail;

		// Token: 0x04001E26 RID: 7718
		private int m_MaxInvalidPasswordAttempts;

		// Token: 0x04001E27 RID: 7719
		private int m_PasswordAttemptWindow;

		// Token: 0x04001E28 RID: 7720
		private MembershipPasswordFormat m_PasswordFormat;

		// Token: 0x04001E29 RID: 7721
		private int m_MinRequiredNonAlphanumericCharacters;

		// Token: 0x04001E2A RID: 7722
		private int m_MinRequiredPasswordLength;

		// Token: 0x04001E2B RID: 7723
		private string m_PasswordStrengthRegularExpression = string.Empty;

		// Token: 0x020004D2 RID: 1234
		private enum FailureType
		{
			// Token: 0x04001E2D RID: 7725
			Password,
			// Token: 0x04001E2E RID: 7726
			PasswordAnswer
		}
	}
}
