using System;
using System.Runtime.Serialization;

namespace System.ComponentModel.DataAnnotations
{
	/// <summary>Represents the exception that occurs during validation of a data field when the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class is used. </summary>
	// Token: 0x02000041 RID: 65
	[Serializable]
	public class ValidationException : Exception
	{
		/// <summary>Gets the instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class that triggered this exception.</summary>
		/// <returns>An instance of the validation attribute type that triggered this exception.</returns>
		// Token: 0x1700005D RID: 93
		// (get) Token: 0x0600017B RID: 379 RVA: 0x00005478 File Offset: 0x00003678
		// (set) Token: 0x0600017C RID: 380 RVA: 0x00005480 File Offset: 0x00003680
		public ValidationAttribute ValidationAttribute { get; private set; }

		/// <summary>Gets the <see cref="P:System.ComponentModel.DataAnnotations.ValidationException.ValidationResult" /> instance that describes the validation error.</summary>
		/// <returns>The <see cref="P:System.ComponentModel.DataAnnotations.ValidationException.ValidationResult" /> instance that describes the validation error.</returns>
		// Token: 0x1700005E RID: 94
		// (get) Token: 0x0600017D RID: 381 RVA: 0x00005489 File Offset: 0x00003689
		public ValidationResult ValidationResult
		{
			get
			{
				if (this._validationResult == null)
				{
					this._validationResult = new ValidationResult(this.Message);
				}
				return this._validationResult;
			}
		}

		/// <summary>Gets the value of the object that causes the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class to trigger this exception.</summary>
		/// <returns>The value of the object that caused the <see cref="T:System.ComponentModel.DataAnnotations.ValidationAttribute" /> class to trigger the validation error.</returns>
		// Token: 0x1700005F RID: 95
		// (get) Token: 0x0600017E RID: 382 RVA: 0x000054AA File Offset: 0x000036AA
		// (set) Token: 0x0600017F RID: 383 RVA: 0x000054B2 File Offset: 0x000036B2
		public object Value { get; private set; }

		/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class by using a validation result, a validation attribute, and the value of the current exception.</summary>
		/// <param name="validationResult">The list of validation results.</param>
		/// <param name="validatingAttribute">The attribute that caused the current exception.</param>
		/// <param name="value">The value of the object that caused the attribute to trigger the validation error.</param>
		// Token: 0x06000180 RID: 384 RVA: 0x000054BB File Offset: 0x000036BB
		public ValidationException(ValidationResult validationResult, ValidationAttribute validatingAttribute, object value)
			: this(validationResult.ErrorMessage, validatingAttribute, value)
		{
			this._validationResult = validationResult;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using a specified error message, a validation attribute, and the value of the current exception.</summary>
		/// <param name="errorMessage">The message that states the error.</param>
		/// <param name="validatingAttribute">The attribute that caused the current exception.</param>
		/// <param name="value">The value of the object that caused the attribute to trigger validation error.</param>
		// Token: 0x06000181 RID: 385 RVA: 0x000054D2 File Offset: 0x000036D2
		public ValidationException(string errorMessage, ValidationAttribute validatingAttribute, object value)
			: base(errorMessage)
		{
			this.Value = value;
			this.ValidationAttribute = validatingAttribute;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using an error message generated by the system.</summary>
		// Token: 0x06000182 RID: 386 RVA: 0x000054E9 File Offset: 0x000036E9
		public ValidationException()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using a specified error message.</summary>
		/// <param name="message">A specified message that states the error.</param>
		// Token: 0x06000183 RID: 387 RVA: 0x000054F1 File Offset: 0x000036F1
		public ValidationException(string message)
			: base(message)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using a specified error message and a collection of inner exception instances.</summary>
		/// <param name="message">The error message. </param>
		/// <param name="innerException">The collection of validation exceptions.</param>
		// Token: 0x06000184 RID: 388 RVA: 0x000054FA File Offset: 0x000036FA
		public ValidationException(string message, Exception innerException)
			: base(message, innerException)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.ComponentModel.DataAnnotations.ValidationException" /> class using serialized data.</summary>
		/// <param name="info">The object that holds the serialized data.</param>
		/// <param name="context">Context information about the source or destination of the serialized object.</param>
		// Token: 0x06000185 RID: 389 RVA: 0x00005504 File Offset: 0x00003704
		protected ValidationException(SerializationInfo info, StreamingContext context)
			: base(info, context)
		{
		}

		// Token: 0x040000C9 RID: 201
		private ValidationResult _validationResult;
	}
}
